### ISSUE TITLE
Filler Crashing World

### ISSUE THREAD

**Issue by cwalv2** [BuildCraft/BuildCraft#2356]
Player put filler at -353 65 -969 next to a flat landmarked area, I think he was making a road.  He then logged out, and when I walked close enough to load the chunk with the filler, this happened.

I went back in an replaced the filler with dirt via mcEdit after getting the following two crash logs, and everything was fine thereafter.

--- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/4/15 9:40 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 1
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplate(PatternFlatten.java:38)
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplateBuilder(PatternFlatten.java:50)
        at buildcraft.builders.TileFiller.initialize(TileFiller.java:78)
        at buildcraft.core.TileBuildCraft.func_145845_h(TileBuildCraft.java:58)
        at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:82)
        at buildcraft.builders.TileFiller.func_145845_h(TileFiller.java:93)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplate(PatternFlatten.java:38)
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplateBuilder(PatternFlatten.java:50)
        at buildcraft.builders.TileFiller.initialize(TileFiller.java:78)
        at buildcraft.core.TileBuildCraft.func_145845_h(TileBuildCraft.java:58)
        at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:82)
        at buildcraft.builders.TileFiller.func_145845_h(TileFiller.java:93)

-- Block entity being ticked --
Details:
        Name: Filler // buildcraft.builders.TileFiller
        Block type: ID #176 (tile.fillerBlock // buildcraft.builders.BlockFiller)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-353,65,-969), Chunk: (at 15,4,7 in -23,-61; contains blocks -368,0,-976 to -353,255,-961), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
        Actual block type: ID #176 (tile.fillerBlock // buildcraft.builders.BlockFiller)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
        Level name: forge
        All players: 3 total; [EntityPlayerMP['cwal'/6432653, l='forge', x=-176.30, y=65.75, z=-966.56], EntityPlayerMP['Garrison_Laforge'/6477696, l='forge', x=338.85, y=140.00, z=-354.59], EntityPlayerMP['gemshale'/6525357, l='forge', x=138.19, y=25.00, z=-134.30]]
        Chunk stats: ServerChunkCache: 1888 Drop: 0
        Level seed: -2147740131206721334
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options: 
        Level spawn location: World: (-68,64,135), Chunk: (at 12,4,7 in -5,8; contains blocks -80,0,128 to -65,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Level time: 85754575 game time, 24298 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 21351 (now: false), thunder time: 51349 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.2.0-4-amd64
        Java Version: 1.7.0_65, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 309031200 bytes (294 MB) / 997195776 bytes (951 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xms128M -Xmx2048M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 17, tallocated: 98
        FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 14 mods loaded, 14 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        enhancedbiomes{2.4.1 for MC 1.7.10} [Enhanced Biomes] (Enhanced Biomes 2.5 for MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 3 / 20; [EntityPlayerMP['cwal'/6432653, l='forge', x=-176.30, y=65.75, z=-966.56], EntityPlayerMP['Garrison_Laforge'/6477696, l='forge', x=338.85, y=140.00, z=-354.59], EntityPlayerMP['gemshale'/6525357, l='forge', x=138.19, y=25.00, z=-134.30]]
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

Upon server restart, still happens:
---- Minecraft Crash Report ----
// My bad.

Time: 1/4/15 9:42 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 1
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplate(PatternFlatten.java:38)
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplateBuilder(PatternFlatten.java:50)
        at buildcraft.builders.TileFiller.initialize(TileFiller.java:78)
        at buildcraft.core.TileBuildCraft.func_145845_h(TileBuildCraft.java:58)
        at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:82)
        at buildcraft.builders.TileFiller.func_145845_h(TileFiller.java:93)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplate(PatternFlatten.java:38)
        at buildcraft.core.builders.patterns.PatternFlatten.getTemplateBuilder(PatternFlatten.java:50)
        at buildcraft.builders.TileFiller.initialize(TileFiller.java:78)
        at buildcraft.core.TileBuildCraft.func_145845_h(TileBuildCraft.java:58)
        at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:82)
        at buildcraft.builders.TileFiller.func_145845_h(TileFiller.java:93)

-- Block entity being ticked --
Details:
        Name: Filler // buildcraft.builders.TileFiller
        Block type: ID #176 (tile.fillerBlock // buildcraft.builders.BlockFiller)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-353,65,-969), Chunk: (at 15,4,7 in -23,-61; contains blocks -368,0,-976 to -353,255,-961), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
        Actual block type: ID #176 (tile.fillerBlock // buildcraft.builders.BlockFiller)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
        Level name: forge
        All players: 1 total; [EntityPlayerMP['cwal'/800, l='forge', x=-176.30, y=65.75, z=-966.56]]
        Chunk stats: ServerChunkCache: 1091 Drop: 0
        Level seed: -2147740131206721334
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options: 
        Level spawn location: World: (-68,64,135), Chunk: (at 12,4,7 in -5,8; contains blocks -80,0,128 to -65,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Level time: 85754648 game time, 24298 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 21278 (now: false), thunder time: 51276 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.2.0-4-amd64
        Java Version: 1.7.0_65, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 654556480 bytes (624 MB) / 1065877504 bytes (1016 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xms128M -Xmx2048M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 19, tcache: 0, allocated: 17, tallocated: 98
        FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 14 mods loaded, 14 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        enhancedbiomes{2.4.1 for MC 1.7.10} [Enhanced Biomes] (Enhanced Biomes 2.5 for MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 1 / 20; [EntityPlayerMP['cwal'/800, l='forge', x=-176.30, y=65.75, z=-966.56]]
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by MineWIZ** [comment]
@asiekierka already fixed this issue in 6.3.0 branch.
