### ISSUE TITLE
Bc transport and silicon errored? server won't boot!

### ISSUE THREAD

**Issue by TheMrCaveman** [BuildCraft/BuildCraft#2359]
---- Minecraft Crash Report ----
// My bad.

Time: 06/01/15 17:37
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerPipePluggable(Ljava/lang/Class;Ljava/lang/String;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerPipePluggable(Ljava/lang/Class;Ljava/lang/String;)V
	at buildcraft.BuildCraftTransport.init(BuildCraftTransport.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 642071096 bytes (612 MB) / 1840250880 bytes (1755 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 1 total; -Xmx6g
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 40 mods loaded, 40 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.85.1277} [Forge Mod Loader] (forge.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.2.1277} [Minecraft Forge] (forge.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	backpacks16840{3.0.1} [Backpacks!] (zz-backpacks 1.7.10 - 3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Core{6.3.0} [BuildCraft] (buildcraft-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Transport{6.3.0} [BC Transport] (buildcraft-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Errored
	BuildCraft|Silicon{6.3.0} [BC Silicon] (buildcraft-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Errored
	BuildCraft|Builders{6.3.0} [BC Builders] (buildcraft-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Energy{6.3.0} [BC Energy] (buildcraft-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Factory{6.3.0} [BC Factory] (buildcraft-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Compat{6.3.0} [BuildCraft Compat] (buildcraft-compat-6.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	eureka{2.2} [Eureka] (Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bcadditions{1.8.3} [Buildcraft Additions] (BuildcraftAdditions-1.7.10-1.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CarpentersBlocks{3.3.4.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.2 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Dynmap{2.0.0-61} [Dynmap] (Dynmap-2.0.0-forge-10.13.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ImmibisCore{59.0.5} [Immibis Core] (immibis-core-59.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	RedLogic{59.1.6} [RedLogic] (redlogic-59.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	OpenComputers{1.4.2.16} [OpenComputers] (OpenComputers-MC1.7.10-1.4.2.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	PneumaticCraft{1.5.1-49} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.1-49-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by asiekierka** [comment]
Outdated BC API in one of the mods. Not sure which one - could be RailCraft or Forestry (Forestry unstable fixes it).

Try renaming BC to "AAA_BUILDCRAFT_6.3.0.jar".

**Comment by grydian** [comment]
Buildcraft Additions updated and I believe thats the file that has the old api.  Here is a link to his twitter.

https://twitter.com/AEnterprise1/status/552486919742193665

**Comment by asiekierka** [comment]
@grydian - Many mods have the old API

**Comment by grydian** [comment]
Yeah upon further testing I would concur, sorry about that.

**Comment by TheMrCaveman** [comment]
It was indeed buildcraft additions!

**Comment by AEnterprise** [comment]
@TheMrCaveman and @grydian there is already a new BCA released with the new BC api
