### ISSUE TITLE
World crash when attemping to use an assemby laser

### ISSUE THREAD

**Issue by Endag** [BuildCraft/BuildCraft#2369]
Tried to make chipsets at assembly table but when selected item to craft server immediately crashes and keep crash every restart

Laser was placed at EnderIO energy conduit

Modpack: DireWolf20 1.7 pack
Crash log:
```
[07:32:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: buildcraft.api.power.ILaserTarget.getXCoord()D
        at buildcraft.silicon.TileLaser.updateLaser(TileLaser.java:234) ~[TileLaser.class:?]
        at buildcraft.silicon.TileLaser.func_145845_h(TileLaser.java:106) ~[TileLaser.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
```

**Comment by asiekierka** [comment]
Have you added or removed any mods from/to the pack? What version of the pack it is?

**Comment by Endag** [comment]
Based on v1.0.3 DW20 pack
Buildcraft version in pack 6.2.6
Was added IguanaTweaks/ThinkerTweaks, removed Hats , all which i assume cannot interfere

Added mods: RotaryCraft(+etc Reika mods, e.g ReactorCraft etc.), GregTech, LogisticPipes

**Comment by asiekierka** [comment]
@Endag - Reika's mods often distribute outdated APIs. If it works on vanilla DW20 (NO CHANGES!), report to the FTB pack team; if not, report to the mod authors of the mods you added?
