### ISSUE TITLE
sealer related bug

### ISSUE THREAD

**Issue by Cracks777** [BuildCraft/BuildCraft#2399]
[07:29:59] [Server thread/ERROR] [FML/]: A TileEntity type buildcraft.transport.TileGenericPipe has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class buildcraft.transport.TileGenericPipe is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:84) ~[aor.class:?]
	at buildcraft.transport.TileGenericPipe.func_145841_b(TileGenericPipe.java:263) ~[TileGenericPipe.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:391) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:418) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1052) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
[07:29:59] [Server thread/INFO] [/]: Ruins chunks logged: 50717

**Comment by Kubuxu** [comment]
Which version of BC are you using?

**Comment by Cracks777** [comment]
BuildCraft 6.3.1

**Comment by Cracks777** [comment]
but the error is arising from a galacticraft block i think.

**Comment by asiekierka** [comment]
I THINK that was fixed?
