### ISSUE TITLE
Assembly Table Crash

### ISSUE THREAD

**Issue by aidenatt** [BuildCraft/BuildCraft#2453]
Hi, just got to the stage of building lasers and an assembly table. I tried creating a Diamond Chipset, but my game crashed. This is what I was given -

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2/10/15 1:22 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: buildcraft.api.power.ILaserTarget.getXCoord()D
	at buildcraft.silicon.TileLaser.updateLaser(TileLaser.java:236)
	at buildcraft.silicon.TileLaser.func_145845_h(TileLaser.java:108)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I am playing 1.7.10 with Forge 10.13.2.1291 & Buildcraft 6.3.6.

**Comment by aidenatt** [comment]
Worked out what was wrong. DragonAPI V3d was using an outdated 'ILaserTarget.class' file from the Buildcraft API. I fixed this by opening up the DragonAPI .jar file and replacing the old .class file with the new one located inside the Buildcraft .jar.
