### ISSUE TITLE
Not a clue

### ISSUE THREAD

**Issue by O13SC3N3** [BuildCraft/BuildCraft#2562]
[00:37:35] [Client thread/WARN] [redgear_brewcraft]: Plugin BuildcraftPlugin failed during the Initialization.
[00:37:35] [Client thread/WARN] [redgear_brewcraft]: catching
java.lang.NoClassDefFoundError: buildcraft/api/fuels/IronEngineFuel
	at redgear.brewcraft.plugins.compat.BuildcraftPlugin.Init(BuildcraftPlugin.java:40) ~[BuildcraftPlugin.class:?]
	at redgear.core.mod.ModUtils.Initialization(ModUtils.java:107) [RedGearCore-1.7.10-2.2.1.jar:?]
	at redgear.brewcraft.core.Brewcraft.Initialization(Brewcraft.java:110) [Brewcraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: buildcraft.api.fuels.IronEngineFuel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 47 more
Caused by: java.lang.NullPointerException

**Comment by O13SC3N3** [comment]
and

[00:38:16] [Client thread/WARN] [OpenMods]: Something went terribly wrong while adding internal adapter 'class openperipheral.integration.buildcraft.AdapterPowerReceptor'. It will be disabled
java.lang.NoClassDefFoundError: buildcraft/api/power/IPowerReceptor
	at openperipheral.integration.buildcraft.AdapterPowerReceptor.getTargetClass(AdapterPowerReceptor.java:16) ~[AdapterPowerReceptor.class:?]
	at openperipheral.adapter.peripheral.PeripheralExternalAdapterWrapper.<init>(PeripheralExternalAdapterWrapper.java:42) ~[PeripheralExternalAdapterWrapper.class:?]
	at openperipheral.adapter.AdapterManager$4.wrapExternalAdapter(AdapterManager.java:73) ~[AdapterManager$4.class:?]
	at openperipheral.adapter.AdapterManager.addAdapter(AdapterManager.java:123) [AdapterManager.class:?]
	at openperipheral.adapter.AdapterManager.addPeripheralAdapter(AdapterManager.java:97) [AdapterManager.class:?]
	at openperipheral.adapter.AdapterRegistryWrapper.register(AdapterRegistryWrapper.java:13) [AdapterRegistryWrapper.class:?]
	at openperipheral.integration.buildcraft.ModuleBuildCraftPower.load(ModuleBuildCraftPower.java:17) [ModuleBuildCraftPower.class:?]
	at openmods.integration.Integration.loadModules(Integration.java:29) [Integration.class:?]
	at openmods.OpenMods.postInit(OpenMods.java:89) [OpenMods.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: buildcraft.api.power.IPowerReceptor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 53 more

**Comment by liach** [comment]
It seems some mods use outdated buildcraft api.

**Comment by asiekierka** [comment]
Yeah. One of the mods is.
