### ISSUE TITLE
Planter robot ConcurrentModificationException spam

### ISSUE THREAD

**Issue by Wykks** [BuildCraft/BuildCraft#2566]
Not sure why but I get these messages in log (It eat a bit my server tps too) : 

        [21:34:24] [Path Finding/WARN]: java.util.ConcurrentModificationException
        [21:34:24] [Path Finding/WARN]:         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        [21:34:24] [Path Finding/WARN]:         at java.util.ArrayList$Itr.next(ArrayList.java:851)
        [21:34:24] [Path Finding/WARN]:         at net.minecraft.world.World.func_147439_a(World.java:650)
        [21:34:24] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:101)
        [21:34:24] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.isTarget(PathFindingSearch.java:87)
        [21:34:24] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterateSearch(PathFindingSearch.java:72)
        [21:34:24] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterate(PathFindingSearch.java:56)
        [21:34:24] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:43)
        [21:35:00] [Path Finding/WARN]: java.util.ConcurrentModificationException
        [21:35:00] [Path Finding/WARN]:         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        [21:35:00] [Path Finding/WARN]:         at java.util.ArrayList$Itr.next(ArrayList.java:851)
        [21:35:00] [Path Finding/WARN]:         at net.minecraft.world.World.func_147439_a(World.java:650)
        [21:35:00] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:101)
        [21:35:00] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.isTarget(PathFindingSearch.java:87)
        [21:35:00] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterateSearch(PathFindingSearch.java:72)
        [21:35:00] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterate(PathFindingSearch.java:56)
        [21:35:00] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:43)

My robot setup : 3 planter 3 picker 3 lumberjack, each configured "Work in area" and "Wake Up" as long as the lever is turned on.

![Robot setup](http://i.gyazo.com/20babdaea983677a8fed4f1b0044bec8.png)

Buildcraft version 6.4.3
Java version 1.8.0_31

**Comment by asiekierka** [comment]
@hea3ven - ?
