### ISSUE TITLE
Planter robot ConcurrentModificationException spam (again)

### ISSUE THREAD

**Issue by Wykks** [BuildCraft/BuildCraft#2577]
#2566 not fixed in builcraft 6.4.4 (same setup)

Edit : Seems to happend only when the zone is full of sapling

        [13:14:54] [Path Finding/WARN]: java.util.ConcurrentModificationException
        [13:14:54] [Path Finding/WARN]:         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        [13:14:54] [Path Finding/WARN]:         at java.util.ArrayList$Itr.next(ArrayList.java:851)
        [13:14:54] [Path Finding/WARN]:         at net.minecraft.world.World.func_147439_a(World.java:650)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter.isPlantable(BoardRobotPlanter.java:176)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter.access$200(BoardRobotPlanter.java:43)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:100)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.isTarget(PathFindingSearch.java:87)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterateSearch(PathFindingSearch.java:72)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterate(PathFindingSearch.java:56)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:43)
        [13:14:54] [Path Finding/WARN]: java.util.ConcurrentModificationException
        [13:14:54] [Path Finding/WARN]:         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        [13:14:54] [Path Finding/WARN]:         at java.util.ArrayList$Itr.next(ArrayList.java:851)
        [13:14:54] [Path Finding/WARN]:         at net.minecraft.world.World.func_147439_a(World.java:650)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter.isPlantable(BoardRobotPlanter.java:176)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter.access$200(BoardRobotPlanter.java:43)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:100)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.isTarget(PathFindingSearch.java:87)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterateSearch(PathFindingSearch.java:72)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterate(PathFindingSearch.java:56)
        [13:14:54] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:43)
        [13:15:07] [Path Finding/WARN]: java.util.ConcurrentModificationException
        [13:15:07] [Path Finding/WARN]:         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        [13:15:07] [Path Finding/WARN]:         at java.util.ArrayList$Itr.next(ArrayList.java:851)
        [13:15:07] [Path Finding/WARN]:         at net.minecraft.world.World.func_147439_a(World.java:650)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter.isPlantable(BoardRobotPlanter.java:176)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter.access$200(BoardRobotPlanter.java:43)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.robots.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:100)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.isTarget(PathFindingSearch.java:87)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterateSearch(PathFindingSearch.java:72)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.PathFindingSearch.iterate(PathFindingSearch.java:56)
        [13:15:07] [Path Finding/WARN]:         at buildcraft.core.utils.concurrency.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:43)

**Comment by hea3ven** [comment]
What version of forge are you using?, and what other mods are you using?

**Comment by Wykks** [comment]
I am running Cauldron 1.7.10-1.1307.06.218 (unoffical fork) and I know it's not supported anymore blablabla. I just use this because of the performance improvement (don't care about bukkit plugin).

Soooo I did test it on a forge server (1307) and it doesn't throw  java.util.ConcurrentModificationException.

My bad, I guess I'll have to play without planter... Not the end of the world.

**Comment by asiekierka** [comment]
Possibly disable any option that has to do with threading? I think Cauldron threads chunkloads and Orebfuscator...
