### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2607]
On game start, it crashed. BC 7, MC 1.7.10
Crash Report/Log
[09:40:16] [main/INFO] [GradleStart]: Extra: []
[09:40:16] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, , --assetIndex, 1.7.10, --accessToken, {REDACTED}, --version, 1.7.10, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[09:40:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[09:40:16] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[09:40:16] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_31
[09:40:16] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[09:40:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[09:40:16] [main/INFO] [GradleStart]: Injecting location in coremod cpw.mods.fml.relauncher.FMLCorePlugin
[09:40:16] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[09:40:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:40:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:40:16] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[09:40:17] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[09:40:17] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:40:17] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[09:40:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[09:40:18] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[09:40:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[09:40:18] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[09:40:18] [main/INFO]: Setting user: Player24
[09:40:20] [Client thread/INFO]: LWJGL Version: 2.9.1
[09:40:20] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[09:40:20] [Client thread/INFO] [FML]: MinecraftForge v10.13.2.1291 Initialized
[09:40:20] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[09:40:20] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[09:40:20] [Client thread/INFO] [FML]: Searching for mods
[09:40:24] [Client thread/INFO] [FML]: Forge Mod Loader has identified 10 mods to load
[09:40:25] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, BuildCraft|Silicon, BuildCraft|Core, BuildCraft|Transport, BuildCraft|Builders, BuildCraft|Robotics, BuildCraft|Energy, BuildCraft|Factory] at CLIENT
[09:40:25] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, BuildCraft|Silicon, BuildCraft|Core, BuildCraft|Transport, BuildCraft|Builders, BuildCraft|Robotics, BuildCraft|Energy, BuildCraft|Factory] at SERVER
[09:40:25] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BuildCraft Robotics, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory
[09:40:26] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[09:40:26] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[09:40:26] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[09:40:26] [Client thread/INFO] [BuildCraft]: Starting BuildCraft 7.0.0
[09:40:26] [Client thread/INFO] [BuildCraft]: Copyright (c) SpaceToad, 2011-2015
[09:40:26] [Client thread/INFO] [BuildCraft]: http://www.mod-buildcraft.com
[09:40:26] [Client thread/ERROR] [BuildCraft|Silicon]: Skipping event FMLPreInitializationEvent and marking errored mod BuildCraft|Silicon since required dependency BuildCraft|Core has errored
[09:40:26] [Client thread/ERROR] [BuildCraft|Transport]: Skipping event FMLPreInitializationEvent and marking errored mod BuildCraft|Transport since required dependency BuildCraft|Core has errored
[09:40:26] [Client thread/ERROR] [BuildCraft|Builders]: Skipping event FMLPreInitializationEvent and marking errored mod BuildCraft|Builders since required dependency BuildCraft|Core has errored
[09:40:26] [Client thread/ERROR] [BuildCraft|Robotics]: Skipping event FMLPreInitializationEvent and marking errored mod BuildCraft|Robotics since required dependency BuildCraft|Core has errored
[09:40:26] [Client thread/ERROR] [BuildCraft|Energy]: Skipping event FMLPreInitializationEvent and marking errored mod BuildCraft|Energy since required dependency BuildCraft|Core has errored
[09:40:26] [Client thread/ERROR] [BuildCraft|Factory]: Skipping event FMLPreInitializationEvent and marking errored mod BuildCraft|Factory since required dependency BuildCraft|Core has errored
[09:40:26] [Client thread/INFO] [FML]: Applying holder lookups
[09:40:26] [Client thread/INFO] [FML]: Holder lookups applied
[09:40:26] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[09:40:26] [Client thread/ERROR] [FML]: 
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forgeSrc-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{7.0.0} [BuildCraft] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Silicon{7.0.0} [BC Silicon] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Transport{7.0.0} [BC Transport] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Builders{7.0.0} [BC Builders] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Robotics{7.0.0} [BuildCraft Robotics] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Energy{7.0.0} [BC Energy] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Factory{7.0.0} [BC Factory] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
[09:40:26] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[09:40:26] [Client thread/ERROR] [FML]: Caught exception from BuildCraft|Core
java.lang.NoSuchMethodError: buildcraft.core.lib.items.ItemBuildCraft.func_77637_a(Lnet/minecraft/creativetab/CreativeTabs;)Lnet/minecraft/item/Item;
	at buildcraft.core.lib.items.ItemBuildCraft.<init>(ItemBuildCraft.java:34) ~[ItemBuildCraft.class:?]
	at buildcraft.core.lib.items.ItemBuildCraft.<init>(ItemBuildCraft.java:28) ~[ItemBuildCraft.class:?]
	at buildcraft.core.ItemWrench.<init>(ItemWrench.java:29) ~[ItemWrench.class:?]
	at buildcraft.BuildCraftCore.loadConfiguration(BuildCraftCore.java:273) ~[BuildCraftCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forgeSrc-1.7.10-10.13.2.1291.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[forgeSrc-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[forgeSrc-1.7.10-10.13.2.1291.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:522) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:931) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
[09:40:26] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 4/1/15 9:40 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.core.lib.items.ItemBuildCraft.func_77637_a(Lnet/minecraft/creativetab/CreativeTabs;)Lnet/minecraft/item/Item;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:522)
	at net.minecraft.client.Minecraft.run(Minecraft.java:931)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.NoSuchMethodError: buildcraft.core.lib.items.ItemBuildCraft.func_77637_a(Lnet/minecraft/creativetab/CreativeTabs;)Lnet/minecraft/item/Item;
	at buildcraft.core.lib.items.ItemBuildCraft.<init>(ItemBuildCraft.java:34)
	at buildcraft.core.lib.items.ItemBuildCraft.<init>(ItemBuildCraft.java:28)
	at buildcraft.core.ItemWrench.<init>(ItemWrench.java:29)
	at buildcraft.BuildCraftCore.loadConfiguration(BuildCraftCore.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 91918128 bytes (87 MB) / 364904448 bytes (348 MB) up to 947388416 bytes (903 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forgeSrc-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{7.0.0} [BuildCraft] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Silicon{7.0.0} [BC Silicon] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Transport{7.0.0} [BC Transport] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Builders{7.0.0} [BC Builders] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Robotics{7.0.0} [BuildCraft Robotics] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Energy{7.0.0} [BC Energy] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
	BuildCraft|Factory{7.0.0} [BC Factory] (buildcraft-7.0.0.jar) Unloaded->Constructed->Errored
[09:40:26] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:398]: #@!@# Game crashed! Crash report saved to: #@!@# (Deleted b/c personal Info) 
[09:40:26] [Thread-7/INFO] [BuildCraft]: Beginning version check

**Comment by AgentK9** [comment]
Btw, did this in eclipse

**Comment by AEnterprise** [comment]
don't use an obfucated build in a deobfuscated environment
