### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SuddenReality** [BuildCraft/BuildCraft#2612]
Hope this is were they go and if I am wrong... SORRY :D
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 03/04/15 16:49
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/api/fuels/IronEngineCoolant$Coolant
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/fuels/IronEngineCoolant$Coolant
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at stanhebben.zenscript.type.ZenTypeNative.complete(ZenTypeNative.java:157)
	at minetweaker.runtime.GlobalRegistry.registerNativeClass(GlobalRegistry.java:95)
	at minetweaker.MineTweakerAPI.registerClass(MineTweakerAPI.java:335)
	at minetweaker.MineTweakerAPI.registerClassRegistry(MineTweakerAPI.java:276)
	at minetweaker.MineTweakerAPI.registerClassRegistry(MineTweakerAPI.java:312)
	at minetweaker.mc1710.MineTweakerMod.onPostInit(MineTweakerMod.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.fuels.IronEngineCoolant$Coolant
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at lumien.perfectspawn.Transformer.PSClassTransformer.transform(PSClassTransformer.java:43)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 640098360 bytes (610 MB) / 1009778688 bytes (963 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 39 mods loaded, 39 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{6.4.5} [BuildCraft] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{6.4.5} [BC Transport] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{6.4.5} [BC Silicon] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{6.4.5} [BC Builders] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{6.4.5} [BC Energy] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{6.4.5} [BC Factory] (buildcraft-6.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	chisel{2.3.9.36} [Chisel 2] (Chisel2-2.3.9.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0RC7} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC7-62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraUtilities{1.2.3} [Extra Utilities] (extrautilities-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-The Journey (4.2.2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MineTweaker3{3.0.9} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	Mystcraft{0.11.2.01} [Mystcraft] (mystcraft-1.7.10-0.11.2.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OreRegen{0.0.9} [OreRegen] (OreRegen-0.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PerfectSpawn{1.1} [Perfect Spawn] (PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TabulaRasa{1.7.10R1.0.1} [Tabula Rasa] (TabulaRasa-[1.7.10]1.0.1-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalDynamics{1.7.10R1.0.0RC8} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC8-105.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0RC7} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC7-141.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	craftingmanager{0.7.4} [Crafting Manager] (zCraftingManager 0.7.5 mc1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore: -[1.7.10]3.0.0RC7-211
	ThermalFoundation: -[1.7.10]1.0.0RC7-62
	ThermalDynamics: -[1.7.10]1.0.0RC8-105
	ThermalExpansion: -[1.7.10]4.0.0RC7-141

**Comment by liach** [comment]
@Stanhebben MineTweaker uses outdated Buildcraft API or used new but didn't update?

**Comment by SuddenReality** [comment]
Ahh So? Downgrade Buildcraft- Can you reccomend a version?

**Comment by liach** [comment]
The best idea is to remove or update Minetweaker-- As I see the class was removed long long ago.

**Comment by SuddenReality** [comment]
Merci :D Thanks

**Comment by liach** [comment]
Works? That's nice.
