### ISSUE TITLE
Crash to title with rotarycraft (wooden fluid pipe + reservoir)

### ISSUE THREAD

**Issue by BionicFelps** [BuildCraft/BuildCraft#2617]
http://pastebin.com/bxF83mXs (minecraft log output)

Steps to reproduce:
Running most current (at time of this post) buildcraft, rotarycraft, (reactorcraft was also installed)
Creative mode
grab a reservoir with water
Put wooden fluid pipe on reservoir
wait a few seconds. (game should crash to title screen)

posted here because of this section naming BC-TRANSPORT:

[16:23:35] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel BC-TRANSPORT
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
        at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by asiekierka** [comment]
Bug with Forge 1355 and BC, see https://github.com/BuildCraft/BuildCraft/issues/2621
