### ISSUE TITLE
Buildcraft fatal error from water pipes

### ISSUE THREAD

**Issue by amainiero** [BuildCraft/BuildCraft#2621]
So im having this issue on my server running some mods where when I place a buildcraft water pipe of any kind my game gives the error "fatal error connection removed" and I am returned to the title screen. Logging back in repeats with the crash, and it seems if im on or near the chunk of the pipe, myself, and any other players near it are kicked from the game. Im on build 6.4.8 if that is needed.

**Comment by austinv900** [comment]
Thanks amainiero. I'm having the same issue with my servers also. its only client side as far as i can tell. I've tried to see if its just a mod incompatibility with another mod by testing buildcraft all by its self in single player and still get the same issue. I don't know if its a incompatibility between forge and build craft. My sugestion is to blacklist pipes in general on your server till another update comes out.

-----------------LATEST FML CLIENT LOG------------------------------
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58) ~[FluidStack.class:?]
	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 18 more
[22:19:18] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel BC-TRANSPORT
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:97) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58) ~[FluidStack.class:?]
	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 18 more
[22:19:18] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppingEvent to mod mcp
[22:19:18] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppingEvent to mod mcp
[22:19:18] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppingEvent to mod FML
[22:19:18] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppingEvent to mod FML
[22:19:18] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppingEvent to mod Forge
[22:19:18] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppingEvent to mod Forge
[22:19:18] [Server thread/TRACE] [BuildCraft|Core/BuildCraft|Core]: Sending event FMLServerStoppingEvent to mod BuildCraft|Core
[22:19:18] [Server thread/TRACE] [BuildCraft|Core/BuildCraft|Core]: Sent event FMLServerStoppingEvent to mod BuildCraft|Core
[22:19:18] [Server thread/TRACE] [BuildCraft|Factory/BuildCraft|Factory]: Sending event FMLServerStoppingEvent to mod BuildCraft|Factory
[22:19:18] [Server thread/TRACE] [BuildCraft|Factory/BuildCraft|Factory]: Sent event FMLServerStoppingEvent to mod BuildCraft|Factory
[22:19:18] [Server thread/TRACE] [BuildCraft|Transport/BuildCraft|Transport]: Sending event FMLServerStoppingEvent to mod BuildCraft|Transport
[22:19:18] [Server thread/TRACE] [BuildCraft|Transport/BuildCraft|Transport]: Sent event FMLServerStoppingEvent to mod BuildCraft|Transport
[22:19:18] [Server thread/TRACE] [BuildCraft|Silicon/BuildCraft|Silicon]: Sending event FMLServerStoppingEvent to mod BuildCraft|Silicon
[22:19:18] [Server thread/TRACE] [BuildCraft|Silicon/BuildCraft|Silicon]: Sent event FMLServerStoppingEvent to mod BuildCraft|Silicon
[22:19:18] [Server thread/TRACE] [BuildCraft|Energy/BuildCraft|Energy]: Sending event FMLServerStoppingEvent to mod BuildCraft|Energy
[22:19:18] [Server thread/TRACE] [BuildCraft|Energy/BuildCraft|Energy]: Sent event FMLServerStoppingEvent to mod BuildCraft|Energy
[22:19:18] [Server thread/TRACE] [BuildCraft|Builders/BuildCraft|Builders]: Sending event FMLServerStoppingEvent to mod BuildCraft|Builders
[22:19:18] [Server thread/TRACE] [BuildCraft|Builders/BuildCraft|Builders]: Sent event FMLServerStoppingEvent to mod BuildCraft|Builders
[22:19:18] [Server thread/TRACE] [BuildCraft|Compat/BuildCraft|Compat]: Sending event FMLServerStoppingEvent to mod BuildCraft|Compat
[22:19:18] [Server thread/TRACE] [BuildCraft|Compat/BuildCraft|Compat]: Sent event FMLServerStoppingEvent to mod BuildCraft|Compat
[22:19:18] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Copy of New World
[22:19:20] [Server thread/INFO] [FML/]: Unloading dimension 0
[22:19:20] [Server thread/INFO] [FML/]: Unloading dimension -1
[22:19:20] [Server thread/INFO] [FML/]: Unloading dimension 1
[22:19:20] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.
[22:19:20] [Server thread/INFO] [FML/]: Applying holder lookups
[22:19:20] [Server thread/INFO] [FML/]: Holder lookups applied
[22:19:20] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppedEvent to mod mcp
[22:19:20] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppedEvent to mod mcp
[22:19:20] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppedEvent to mod FML
[22:19:20] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppedEvent to mod FML
[22:19:20] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppedEvent to mod Forge
[22:19:20] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppedEvent to mod Forge
[22:19:20] [Server thread/TRACE] [BuildCraft|Core/BuildCraft|Core]: Sending event FMLServerStoppedEvent to mod BuildCraft|Core
[22:19:20] [Server thread/TRACE] [BuildCraft|Core/BuildCraft|Core]: Sent event FMLServerStoppedEvent to mod BuildCraft|Core
[22:19:20] [Server thread/TRACE] [BuildCraft|Factory/BuildCraft|Factory]: Sending event FMLServerStoppedEvent to mod BuildCraft|Factory
[22:19:20] [Server thread/TRACE] [BuildCraft|Factory/BuildCraft|Factory]: Sent event FMLServerStoppedEvent to mod BuildCraft|Factory
[22:19:20] [Server thread/TRACE] [BuildCraft|Transport/BuildCraft|Transport]: Sending event FMLServerStoppedEvent to mod BuildCraft|Transport
[22:19:20] [Server thread/TRACE] [BuildCraft|Transport/BuildCraft|Transport]: Sent event FMLServerStoppedEvent to mod BuildCraft|Transport
[22:19:20] [Server thread/TRACE] [BuildCraft|Silicon/BuildCraft|Silicon]: Sending event FMLServerStoppedEvent to mod BuildCraft|Silicon
[22:19:20] [Server thread/TRACE] [BuildCraft|Silicon/BuildCraft|Silicon]: Sent event FMLServerStoppedEvent to mod BuildCraft|Silicon
[22:19:20] [Server thread/TRACE] [BuildCraft|Energy/BuildCraft|Energy]: Sending event FMLServerStoppedEvent to mod BuildCraft|Energy
[22:19:20] [Server thread/TRACE] [BuildCraft|Energy/BuildCraft|Energy]: Sent event FMLServerStoppedEvent to mod BuildCraft|Energy
[22:19:20] [Server thread/TRACE] [BuildCraft|Builders/BuildCraft|Builders]: Sending event FMLServerStoppedEvent to mod BuildCraft|Builders
[22:19:20] [Server thread/TRACE] [BuildCraft|Builders/BuildCraft|Builders]: Sent event FMLServerStoppedEvent to mod BuildCraft|Builders
[22:19:20] [Server thread/TRACE] [BuildCraft|Compat/BuildCraft|Compat]: Sending event FMLServerStoppedEvent to mod BuildCraft|Compat
[22:19:20] [Server thread/TRACE] [BuildCraft|Compat/BuildCraft|Compat]: Sent event FMLServerStoppedEvent to mod BuildCraft|Compat

**Comment by amainiero** [comment]
Does anyone know of an older build that doesnt have this issue on servers?

**Comment by squ1b3r** [comment]
I think it's related to the changes that were made in forge 10.13.3.1355. Worked for me before I updated to it

**Comment by iTitus** [comment]
Forge changed the FluidRegistry. I suggest using an older version of Forge.

**Comment by modmuss50** [comment]
I can also confirm this.

**Comment by asiekierka** [comment]
Oh. Yeah. Apparently the BuildCraft code was doing a certain semi-terrible hack with using a dummy fluid ID to represent no fluid, and cpw's check for whether the fluid is actually registered caught that.

Will release 6.4.9 this evening, hopefully.

**Comment by austinv900** [comment]
Thanks asiekierka. Can't wait for the update

**Comment by asiekierka** [comment]
Thanks for looking into it! Please try http://asie.pl/bc649a.jar.

**Comment by austinv900** [comment]
this is from the jar you linked

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/10/15 1:27 AM
Description: Initializing game

java.lang.NoClassDefFoundError: buildcraft/api/robots/IRobotRegistryProvider
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.FMLModContainer.parseSimpleFieldAnnotation(FMLModContainer.java:383)
	at cpw.mods.fml.common.FMLModContainer.processFieldAnnotations(FMLModContainer.java:338)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: buildcraft.api.robots.IRobotRegistryProvider
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.FMLModContainer.parseSimpleFieldAnnotation(FMLModContainer.java:383)
	at cpw.mods.fml.common.FMLModContainer.processFieldAnnotations(FMLModContainer.java:338)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 102293376 bytes (97 MB) / 259682304 bytes (247 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.104.1358 Minecraft Forge 10.13.3.1358 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.104.1358} [Forge Mod Loader] (forge-1.7.10-10.13.3.1358-1.7.10.jar) Unloaded->Constructed
	Forge{10.13.3.1358} [Minecraft Forge] (forge-1.7.10-10.13.3.1358-1.7.10.jar) Unloaded->Constructed
	BuildCraft|Core{6.4.8} [BuildCraft] (buildcraft-beta.jar) Unloaded
	BuildCraft|Transport{6.4.8} [BC Transport] (buildcraft-beta.jar) Unloaded
	BuildCraft|Silicon{6.4.8} [BC Silicon] (buildcraft-beta.jar) Unloaded
	BuildCraft|Builders{6.4.8} [BC Builders] (buildcraft-beta.jar) Unloaded
	BuildCraft|Robotics{7.0.1} [BuildCraft Robotics] (buildcraft-beta.jar) Unloaded
	BuildCraft|Energy{6.4.8} [BC Energy] (buildcraft-beta.jar) Unloaded
	BuildCraft|Factory{6.4.8} [BC Factory] (buildcraft-beta.jar) Unloaded
	Launched Version: 1.7.10-Forge10.13.3.1358-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6750M GL version 4.3.12615 Compatibility Profile Context 13.250.28.2000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by asiekierka** [comment]
Corrupt JAR?

Try http://asie.pl/bc649b.jar

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/5c767249a6f36bf41a55dd8c1a5973a9338a957b

**Comment by austinv900** [comment]
Seems like its working now. Thanks!

**Comment by sorcero2002** [comment]
if you have this problem you can just download the Forge build 1352


link: http://adfoc.us/serve/?id=27122855011644

**Comment by asiekierka** [comment]
@sorcero2002 - Why would you downgrade to an older version of Forge, breaking tens of mods in the process, when the issue has been fixed in BuildCraft 6.4.9 as pointed to in this issue?

**Comment by sorcero2002** [comment]
i have that version of buildcraft and it still occured the same error

i downgraded it and it was over XD

**Comment by sorcero2002** [comment]
LOL if i play on build 6.4.9 and now place a fluid pipe and let oil go through the oil will glitch out XD and after a few seconds my game crashes XD
