### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2625]
I have been experimenting with different mods and I just added a few more cool mods and it started crashing
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/9/15 7:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraftAdditions/items/ItemPoweredBase
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:522)
	at net.minecraft.client.Minecraft.run(Minecraft.java:931)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: buildcraftAdditions/items/ItemPoweredBase
	at buildcraftAdditions.BuildcraftAdditions.preInit(BuildcraftAdditions.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 12 more
Caused by: java.lang.ClassNotFoundException: buildcraftAdditions.items.ItemPoweredBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 297324960 bytes (283 MB) / 491782144 bytes (469 MB) up to 947388416 bytes (903 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 29 mods loaded, 29 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forgeSrc-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized
	doggytalents{v1.8.2a} [Doggy Talents] ([1.7.10] Doggy Talents - v1.8.2a.zip) Unloaded->Constructed->Pre-initialized
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized
	B0bGrowsOre{2.3.0} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.3.0 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.4.8} [BuildCraft] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.4.8} [BC Transport] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.4.8} [BC Silicon] (buildcraft-6.4.8.jar) Unloaded->Constructed->Errored
	BuildCraft|Builders{6.4.8} [BC Builders] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.4.8} [BC Energy] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.4.8} [BC Factory] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.2.jar) Unloaded->Constructed->Pre-initialized
	eureka{3.0.1} [Eureka] (Eureka-1.7.10-3.0.1.jar) Unloaded->Constructed->Pre-initialized
	bcadditions{2.1.1} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.1.1.jar) Unloaded->Constructed->Errored
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ganyssurface{1.9.6} [Gany's Surface] (Ganys Surface-1.9.6.jar) Unloaded->Constructed->Pre-initialized
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	minepainter{0.2.6} [MinePainter] (minepainter-0.2.6.jar) Unloaded->Constructed->Pre-initialized
	modularsystemsapi{0.0.1} [Modular Systems API] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	modularsystems{1.7.1} [Modular Systems] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized
	StevesCarts{2.0.0.b16} [Steve's Carts 2] (Steves-Carts-2-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
the report

**Comment by AgentK9** [comment]
of all the mods that errored, I would have thought it was a new mod. I already had BC aand BCA in there. @AEnterprise @asiekierka

**Comment by AEnterprise** [comment]
seems like one of the mods in there is shipping an outdated RF api

**Comment by AgentK9** [comment]
I removed the growable ores and it worked. strange. i don't think it does anything w/ RF
