### ISSUE TITLE
Interacting with Combustion Engines full of oil and water crashes to desktop

### ISSUE THREAD

**Issue by adudney** [BuildCraft/BuildCraft#2628]
This is on Buildcraft 6.4.9, freshly downloaded from mod-buildcraft.com. Forge is version 10.13.3.1355-1.7.10, and I have a bunch of other mods installed as well. The engine is full of water and oil.

I had expected this to be fixed with the fluid pipe fix, which is why I didn't create an issue earlier, and I just now got the time to test it.

Important bit of crash log (as far as I know, the full crash log is too big for pastebin) is:

http://pastebin.com/Z7TB48SJ

EDIT: Confirmed on Forge 10.13.3.1362-1.7.10 as well.

**Comment by adudney** [comment]
Note a similar error also occurs on a freshly placed combustion engine in a creative world:

[16:21:28] [Server thread/INFO] [FML]: Holder lookups applied
[16:21:29] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:91) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58) ~[FluidStack.class:?]
	at buildcraft.energy.TileEngineIron.getGUINetworkData(TileEngineIron.java:300) ~[TileEngineIron.class:?]
	at buildcraft.energy.gui.ContainerEngine.func_75137_b(ContainerEngine.java:58) ~[ContainerEngine.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151) ~[bjb.class:?]
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26) ~[gp.class:?]
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9) ~[gp.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[16:21:29] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 4/10/15 4:21 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:91)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at buildcraft.energy.TileEngineIron.getGUINetworkData(TileEngineIron.java:300)
	at buildcraft.energy.gui.ContainerEngine.func_75137_b(ContainerEngine.java:58)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:91)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58)
	at buildcraft.energy.TileEngineIron.getGUINetworkData(TileEngineIron.java:300)
	at buildcraft.energy.gui.ContainerEngine.func_75137_b(ContainerEngine.java:58)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

**Comment by asiekierka** [comment]
https://github.com/BuildCraft/BuildCraft/commit/6af362a89d153d4a78788620d9598c1d8f2b8385
