### ISSUE TITLE
Server crashing after because of a bugged filler

### ISSUE THREAD

**Issue by JamMasterz** [BuildCraft/BuildCraft#2650]
Hello. I tried to use a filler on top of the nether roof, and i was circling through the modes while the filler was working, which crashed the server. Now everytime i try to log in i get this errror (sorry pastebin is hanging itself everytime i try to paste the error):

[15:45:24] [Server thread/INFO] [FML/]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:45:24] [Client thread/INFO] [FML/]: Server terminated.

Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 0
	at buildcraft.core.builders.patterns.PatternHorizon.getTemplate(PatternHorizon.java:40)
	at buildcraft.core.builders.patterns.PatternHorizon.getTemplateBuilder(PatternHorizon.java:52)
	at buildcraft.builders.TileFiller.initialize(TileFiller.java:86)
	at buildcraft.core.TileBuildCraft.func_145845_h(TileBuildCraft.java:71)
	at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:85)
	at buildcraft.builders.TileFiller.func_145845_h(TileFiller.java:100)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.core.builders.patterns.PatternHorizon.getTemplate(PatternHorizon.java:40)
	at buildcraft.core.builders.patterns.PatternHorizon.getTemplateBuilder(PatternHorizon.java:52)
	at buildcraft.builders.TileFiller.initialize(TileFiller.java:86)
	at buildcraft.core.TileBuildCraft.func_145845_h(TileBuildCraft.java:71)
	at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:85)
	at buildcraft.builders.TileFiller.func_145845_h(TileFiller.java:100)

-- Block entity being ticked --
Details:
	Name: Filler // buildcraft.builders.TileFiller
	Block type: ID #1172 (tile.fillerBlock // buildcraft.builders.BlockFiller)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-99,130,301), Chunk: (at 13,8,13 in -7,18; contains blocks -112,0,288 to -97,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1172 (tile.fillerBlock // buildcraft.builders.BlockFiller)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 31 Drop: 25
	Level seed: -2825233071758776111
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

The weird thing is that this occurs even after i removed that block using mcedit. How can i fix this?

**Comment by JamMasterz** [comment]
Yepp, github doesnt have spoilers and the markdown tutorial recommended i send a link instead, sorry for this mess.

**Comment by Kubuxu** [comment]
@JamMasterz hastebin.com is great service.
