### ISSUE TITLE
Crash on login after placing Void Fluid Pipe

### ISSUE THREAD

**Issue by Lilylicious** [BuildCraft/BuildCraft#2662]
After placing a void fluid pipe connected to an MFR harvester (pipe taking sludge), the player that placed it gets disconnected from the server upon entering the game. Forge version is 7.10.118.1389.

```
[16:50:39] [Client thread/WARN] [FML/]: ****************************************
[16:50:39] [Client thread/WARN] [FML/]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[16:50:39] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[16:50:39] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[16:50:39] [Client thread/WARN] [FML/]: *  at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87)
[16:50:39] [Client thread/WARN] [FML/]: *  at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47)
[16:50:39] [Client thread/WARN] [FML/]: *  at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22)
[16:50:39] [Client thread/WARN] [FML/]: *  at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77)...
[16:50:39] [Client thread/WARN] [FML/]: ****************************************
```

[Partial log](http://pastebin.com/uRJw5DkQ), because the full log somehow managed to become 192k lines long and causes pastebin to freeze upon trying to paste it. The very end of the log, with the errors, are in that log. Upon request I could figure out how to get the full log available. Why it's 192k lines is beyond me.

**Comment by asiekierka** [comment]
Because packets are sent a bit more often.

This is fixed in the 7.0 branch, but we'll backport it to 6.4.x soon enough.

**Comment by Lilylicious** [comment]
Fair enough. Any tips on making our player able to get back on? Removing
the pipe?

**Comment by asiekierka** [comment]
@Lilylicious - downgrade Forge below 1355 or give me a few minutes...

**Comment by asiekierka** [comment]
@Lilylicious - wait. Why are you using an old version of BuildCraft?

**Comment by Lilylicious** [comment]
Good question, updating is first on the list. We are using a custom pack
based on an existing one, which included a requirement of a newer forge.

**Comment by asiekierka** [comment]
Update.

**Comment by Lilylicious** [comment]
Updated to 6.4.11, problem solved. Why do I forget to update before making issues?

**Comment by asiekierka** [comment]
Check the changelogs next time. They specifically mention fixing bugs for newer Forge.

(Also, update to 6.4.13 already.)
