### ISSUE TITLE
writeToNBT IndexOutOfBounds

### ISSUE THREAD

**Issue by fagcinsk** [BuildCraft/BuildCraft#2707]
When i put golden/other pipe anywhere, i got:
```
java.lang.ArrayIndexOutOfBoundsException: 6
	at buildcraft.transport.PipeTransportFluids.writeToNBT(PipeTransportFluids.java:357) ~[PipeTransportFluids.class:?]
	at buildcraft.transport.Pipe.writeToNBT(Pipe.java:226) ~[Pipe.class:?]
```
Using ```minecraft Forge 1.8``` on ```Windows 8 x64``` and ```buildcraft-6.2.6``` from ```mc1.8``` branch

**Comment by asiekierka** [comment]
The mc1.8 branch is hilariously broken.
