### ISSUE TITLE
[BC 7.0.5] Game crashes when quarry has 2 outputs

### ISSUE THREAD

**Issue by sokarcreative** [BuildCraft/BuildCraft#2748]
Hi everyone,

Using BC 7.0.5, below you can see a simple example when game crashes : 
![buildcraft-bug-quarry-2-outputs](https://cloud.githubusercontent.com/assets/7457032/8019040/9f1a6d24-0c3a-11e5-93e3-faf92c38fd71.png)

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/06/15 10:40
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at buildcraft.core.lib.utils.Utils.addToRandomInjectableAround(Utils.java:154)
	at buildcraft.core.lib.utils.BlockMiner.mineStack(BlockMiner.java:49)
	at buildcraft.core.lib.utils.BlockMiner.acceptEnergy(BlockMiner.java:99)
	at buildcraft.builders.TileQuarry.dig(TileQuarry.java:240)
	at buildcraft.builders.TileQuarry.func_145845_h(TileQuarry.java:196)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I played minecraft with 3 mods : Buildcraft, Optifine and TMI.
When the game crashed, I removed Optifine and TMI, ran the launcher, created a new world and reproduced the bug like screenshot above (still there).

**Comment by asiekierka** [comment]
Fixed in 7.0.6.
