### ISSUE TITLE
[BC 7.0.6] Compatibility with Forestry

### ISSUE THREAD

**Issue by kremsy** [BuildCraft/BuildCraft#2749]
Hello, as soon as I put buildcraft "buildcraft-7.0.6" in my mods folder together with forestry "forestry_1.7.10-3.5.6.15" my minecraft does not startup and crash during startup.

Would be cool if this could investigated and fixed as I want to setup a new server with some modes and BC 7 :).

Here the Log:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 06.06.15 11:25
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:35)
	at forestry.pipes.proxy.ClientProxyPipes.initPropolisPipe(ClientProxyPipes.java:28)
	at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:64)
	at forestry.plugins.PluginManager.runPostInit(PluginManager.java:296)
	at forestry.core.ForestryCore.postInit(ForestryCore.java:118)
	at forestry.core.ForestryClient.postInit(ForestryClient.java:41)
	at forestry.Forestry.postInit(Forestry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 113475104 bytes (108 MB) / 305573888 bytes (291 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 11 mods loaded, 11 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{7.0.6} [BuildCraft] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{7.0.6} [BC Builders] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{7.0.6} [BC Energy] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{7.0.6} [BC Factory] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{7.0.6} [BC Silicon] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{7.0.6} [BC Transport] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Robotics{7.0.6} [BC Robotics] (buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.5.6.15} [Forestry for Minecraft] (forestry_1.7.10-3.5.6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored

**Comment by asiekierka** [comment]
I said "update to Forestry 3.5.7" in the blog post.

**Comment by kremsy** [comment]
Good to know that its fixed, sorry that Ive overreaden that.

Do you know where can I get forestry 3.5.7, on git as well on their website they only have 3.5.6.

**Comment by kremsy** [comment]
found it, thank you!
