### ISSUE TITLE
Buildcraft and Minetweaker bug ?

### ISSUE THREAD

**Issue by Dream-Master** [BuildCraft/BuildCraft#2767]
Try to remove the Quarry with Minetweaker:
recipes.remove(<BuildCraft|Factory:machineBlock>);
This is the error I get.

Line 446: ERROR: Build-Craft.zs:120: Could not resolve <BuildCraft | Factory : machineBlock>

They make spaces between the double point. I have the same issue with Logistic Pipes some times before. in Version 6 all works fine.

``````````````````````````````````````
ERROR: Error executing Build-Craft.zs: null
java.lang.NullPointerException
	at minetweaker.mc1710.recipes.MCRecipeManager.remove(MCRecipeManager.java:94)
	at Build-Craft.__script__(Build-Craft.zs:120)
	at __ZenMain__.run(Build-Craft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:838)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:91)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by asiekierka** [comment]
The Quarry moved to Builders, as the blog post warned

**Comment by Dream-Master** [comment]
Sorry my post deleting some letters. (Get the Quarry in 7.08 and use /mt hand and copy that value to the scripts). Every Recipes i try to remove have this issue (Have space befor and after the : ) so every single block or item cant be touched any more. The Quarry ist just an example. I'm using Minetweaker for a while and got a lot of experience with that. (writing nearly to 1mb of scripts)https://github.com/Dream-Master/NewHorizons/tree/master/scripts.

**Comment by Dream-Master** [comment]
Thank you for your great help!!!

**Comment by Dream-Master** [comment]
@asiekierka i would need some help with it because if the the error with Minetweaker and the New BC 7 still exist i cant update. You need some more infos or testing?

**Comment by AEnterprise** [comment]
the error is at line 120, if i look at that in your script i see you are trying to remove the wrong block, the quarry is no longer in factory, you want to use <BuildCraft|Builders:machineBlock> iirc, if that doesn't work dissable the script and use /mt hand to identfy the quarry again

**Comment by Dream-Master** [comment]
Ok i will check it again this evening.

**Comment by Dream-Master** [comment]
Ok works for me now. Thanks
