### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Ramyskie** [BuildCraft/BuildCraft#2773]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/9/15 1:52 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:30)
	at forestry.pipes.proxy.ClientProxyPipes.initPropolisPipe(ClientProxyPipes.java:25)
	at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:59)
	at forestry.plugins.PluginManager.runPostInit(PluginManager.java:257)
	at forestry.core.ForestryCore.postInit(ForestryCore.java:123)
	at forestry.core.ForestryClient.postInit(ForestryClient.java:40)
	at forestry.Forestry.postInit(Forestry.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 134363144 bytes (128 MB) / 966393856 bytes (921 MB) up to 966393856 bytes (921 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2g
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 25 mods loaded, 25 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{7.0.8} [BuildCraft] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{7.0.8} [BC Builders] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{7.0.8} [BC Energy] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Robotics{7.0.8} [BC Robotics] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{7.0.8} [BC Silicon] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{7.0.8} [BC Transport] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{7.0.8} [BC Factory] (buildcraft-7.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	StealthwareCore{2.0} [StealthwareCore] (StealthwareCore-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Explodables{1.9} [Explodables] (Explodables-1.7.10-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	instahouse{8.0} [Insta House] (InstaHousev8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ironbackpacks{0.5.0} [Iron Backpacks] (Iron Backpacks-1.7.10-1.0.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	cfm{3.4.7} [?9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	telepads{1.7.10 v1} [Teleportation Pads] (Telepads 1.7.10 v2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized

It works fine without Buildcraft. I am using forestry and it required buildcraft to work. It might just be one of my other mods clashing with build craft. But no sure which one

**Comment by AEnterprise** [comment]
you need to update your forestry

**Comment by Ramyskie** [comment]
Thank you!!! Instant fix. Though I downloaded forestry yesterday and updated today XD wouldn't have thought it was because one day difference in update. Again thank for fast response.
