### ISSUE TITLE
Crash buildcraft 7.0.8

### ISSUE THREAD

**Issue by LemonNick** [BuildCraft/BuildCraft#2774]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 9
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at net.minecraft.world.World.func_147438_o(World.java:3108)
	at buildcraft.transport.BlockGenericPipe.getPipe(BlockGenericPipe.java:903)
	at buildcraft.transport.BlockGenericPipe.func_149709_b(BlockGenericPipe.java:828)
	at net.minecraft.world.World.func_72878_l(World.java:4091)
	at net.minecraft.world.World.func_72864_z(World.java:4096)
	at forestry.core.gadgets.TileForestry.isActivated(TileForestry.java:216)
	at forestry.energy.gadgets.EngineTin.generateHeat(EngineTin.java:161)
	at forestry.core.gadgets.Engine.updateServerSide(Engine.java:170)
	at forestry.energy.gadgets.EngineTin.updateServerSide(EngineTin.java:183)
	at forestry.core.gadgets.TileBase.func_145845_h(TileBase.java:39)
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:744)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at net.minecraft.world.World.func_147438_o(World.java:3108)
	at buildcraft.transport.BlockGenericPipe.getPipe(BlockGenericPipe.java:903)
	at buildcraft.transport.BlockGenericPipe.func_149709_b(BlockGenericPipe.java:828)
	at net.minecraft.world.World.func_72878_l(World.java:4091)
	at net.minecraft.world.World.func_72864_z(World.java:4096)
	at forestry.core.gadgets.TileForestry.isActivated(TileForestry.java:216)
	at forestry.energy.gadgets.EngineTin.generateHeat(EngineTin.java:161)
	at forestry.core.gadgets.Engine.updateServerSide(Engine.java:170)
	at forestry.energy.gadgets.EngineTin.updateServerSide(EngineTin.java:183)
	at forestry.core.gadgets.TileBase.func_145845_h(TileBase.java:39)

-- Block entity being ticked --
Details:
	Name: forestry.EngineTin // forestry.energy.gadgets.EngineTin
	Block type: ID #562 (tile.for.engine // forestry.core.gadgets.BlockBase)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1658,87,773), Chunk: (at 10,5,5 in 103,48; contains blocks 1648,0,768 to 1663,255,783), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
	Actual block type: ID #562 (tile.for.engine // forestry.core.gadgets.BlockBase)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 23 total; [EntityPlayerMP['Foxy87'/438, l='world', x=1785.20, y=64.00, z=-1148.04](Foxy87 at 1785.2043091288172,64.0,-1148.0446324275133), EntityPlayerMP['TerRoristka'/461, l='world', x=1779.75, y=73.00, z=-1121.67](TerRoristka at 1779.7542825797943,73.0,-1121.6710969184292), EntityPlayerMP['MrKris'/980, l='world', x=1780.30, y=69.85, z=-1136.42](MrKris at 1780.3011649521068,69.84920034185511,-1136.415837770265), EntityPlayerMP['Windrana'/23427, l='world', x=1780.98, y=71.50, z=-1121.53](Windrana at 1780.9811126888326,71.5,-1121.5320470744678), EntityPlayerMP['_Stalin_'/18471, l='world', x=891.71, y=70.88, z=635.49](_Stalin_ at 891.7087624377176,70.875,635.4864038591377), EntityPlayerMP['Survivor3'/37443, l='world', x=491.30, y=75.00, z=629.98](Survivor3 at 491.30073739748303,75.0,629.9829015135737), EntityPlayerMP['serega178rus'/2282, l='world', x=637.98, y=110.00, z=892.30](serega178rus at 637.9824468564389,110.0,892.3025153561098), EntityPlayerMP['xew095'/41532, l='world', x=1423.38, y=84.15, z=1263.79](xew095 at 1423.380645673943,84.15382134367731,1263.7890245180304), EntityPlayerMP['igor23345'/43561, l='world', x=1678.04, y=64.00, z=279.58](igor23345 at 1678.0420981731743,64.0,279.5826944137023), EntityPlayerMP['AstridL02'/36956, l='world', x=731.50, y=73.00, z=493.39](AstridL02 at 731.5026675102044,73.0,493.39140626840225), EntityPlayerMP['spryt'/45320, l='world', x=-2696.48, y=60.00, z=1585.84](spryt at -2696.480898260515,60.0,1585.8400224182851), EntityPlayerMP['Crest'/46793, l='world', x=1009.62, y=63.20, z=1087.14](Crest at 1009.6190331580776,63.200000047683695,1087.1361995726907), EntityPlayerMP['Podzik'/43521, l='world', x=-399.04, y=76.42, z=-136.81](Podzik at -399.0432148688467,76.41799634940732,-136.81223926953436), EntityPlayerMP['HighDragonHigh'/58798, l='world', x=-2740.20, y=68.00, z=2367.84](HighDragonHigh at -2740.2010623426177,68.0,2367.8440893007864), EntityPlayerMP['mrFrost2'/44874, l='world', x=1671.20, y=64.00, z=288.02](mrFrost2 at 1671.2006679543742,64.0,288.0241515508063), EntityPlayerMP['NiggaRaf'/76799, l='world', x=658.17, y=64.00, z=722.82](NiggaRaf at 658.1685808283708,64.0,722.8162605237799), EntityPlayerMP['MiSTiK25'/82913, l='world', x=1280.18, y=65.00, z=-2116.26](MiSTiK25 at 1280.1778717242116,65.0,-2116.2565141719115), EntityPlayerMP['Mr_Freedom'/84248, l='world', x=2410.50, y=63.00, z=1407.76](Mr_Freedom at 2410.496653899676,63.0,1407.7578024411234), EntityPlayerMP['Scoul360'/79151, l='world', x=1660.00, y=106.46, z=761.06](Scoul360 at 1659.9998967729043,106.4618042395542,761.0553295578824), EntityPlayerMP['firestraick'/34048, l='world', x=563.06, y=65.00, z=1626.20](firestraick at 563.0647832881806,65.0,1626.1968738701405), EntityPlayerMP['oleika'/89175, l='world', x=657.27, y=65.55, z=730.45](oleika at 657.267435880636,65.54973123499414,730.4526749239027), EntityPlayerMP['stasin26'/90170, l='world', x=39.70, y=133.00, z=982.30](stasin26 at 39.703208713742065,133.0,982.2984360810945), EntityPlayerMP['Odin'/90385, l='world', x=841.21, y=70.36, z=963.82](Odin at 841.2140862790689,70.36294178383888,963.8243602727393)]
	Chunk stats: ServerChunkCache: 1636 Drop: 0
	Level seed: -4539267679952214255
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (639,110,891), Chunk: (at 15,6,11 in 39,55; contains blocks 624,0,880 to 639,255,895), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 25418839 game time, 25505368 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 36802 (now: false), thunder time: 4312 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:744)

**Comment by asiekierka** [comment]
This seems like one of those rare in-Minecraft race conditions out of our control, as the crash happens in World.getTileEntity (!?)
