### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ScratchnTavi** [BuildCraft/BuildCraft#2783]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10.06.15 21:06
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.api.core.StackKey.stack(Lnet/minecraft/block/Block;)Lbuildcraft/api/core/StackKey;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:535)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.core.StackKey.stack(Lnet/minecraft/block/Block;)Lbuildcraft/api/core/StackKey;
	at buildcraft.BuildCraftEnergy.preInit(BuildCraftEnergy.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 87833976 bytes (83 MB) / 381296640 bytes (363 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 37 mods loaded, 36 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.140.1401} [Forge Mod Loader] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1401} [Minecraft Forge] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{7.0.5} [BuildCraft] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{7.0.5} [BC Silicon] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{7.0.5} [BC Factory] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{7.0.5} [BC Energy] (buildcraft-7.0.5.jar) Unloaded->Constructed->Errored
	BuildCraft|Builders{7.0.5} [BC Builders] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Robotics{7.0.5} [BC Robotics] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{7.0.5} [BC Transport] (buildcraft-7.0.5.jar) Unloaded->Constructed->Pre-initialized
	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) Unloaded->Constructed->Pre-initialized
	bcadditions{2.1.4} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized
	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) Unloaded->Constructed->Pre-initialized
	EE3{0.3.501} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.501.jar) Unloaded->Constructed->Pre-initialized
	IC2{2.2.727-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.727-experimental.jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.41.729} [Iron Chest] (ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded->Constructed->Pre-initialized
	UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (universal-electricity-4.0.0.9-core.jar) Unloaded->Constructed->Pre-initialized
	ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine] (resonant-engine-2.0.0.32-core.jar) Unloaded->Constructed->Pre-initialized
	MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System] (mffs-4.0.0.18-core.jar) Unloaded->Constructed->Pre-initialized
	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.7.10-1.0.8.16-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.6.2.82} [ProjectRed] (ProjectRed-1.7.10-4.6.2.82-Base.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.6.2.82} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.6.2.82} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.6.2.82} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.6.2.82-World.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.6.2.82} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.6.2.82-Compat.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.6.2.82} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.6.2.82} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.2.82-Lighting.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.6.2.82} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized
	concurrentmodificationfix{} [ConcurrentModificationFix] (minecraft.jar) Unloaded->Disabled
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce GT 240/PCIe/SSE2'

---------

I tried buildcraft 7.0.5 and 7.0.8 now. Same error with Energy everytime

**Comment by asiekierka** [comment]
One of these mods is providing an outdated BuildCraft API. Find it and remove its buildcraft/api folder.
