### ISSUE TITLE
Shift + Right click = Crash the Game

### ISSUE THREAD

**Issue by mimic2300** [BuildCraft/BuildCraft#2807]
Hi, i found bug. If i press and hold the shift and then right click on robot station so game crash! Maybe this "works" for more BC objects, i dont try it. Can you fix it?

BC 7.0.9 for MC 1.7.10 forge 10.13.3.1428

**Comment by LouisHutch** [comment]
Posting a Crash log may help :)

**Comment by mimic2300** [comment]
Ok.. problem occurred, when use BC Wrench for pickup robot station (with empty hand is ok)

java.lang.NullPointerException: Ticking memory connection
	at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:625)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by asiekierka** [comment]
Fixed in BC 7.0.10. It's going to come out soon but I'm busy with school right now.
