### ISSUE TITLE
Crash the game after placing dirt on golden pipe

### ISSUE THREAD

**Issue by mimic2300** [BuildCraft/BuildCraft#2809]
Next exception and crash the game.. i just try place dirt on golden pipe

java.lang.NullPointerException: Ticking memory connection
	at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:674)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by asiekierka** [comment]
Same bug as reported fifty times now, I'd release a new version but seriously can't. Too much schoolwork.

Use http://nallar.me/buildservice/job/Buildcraft/727/
