### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by superzanti** [BuildCraft/BuildCraft#2818]
Can you add a handler for nulls?

Every once and a while players on my server will get booted.

Here's the stacktrace:

```
java.lang.NullPointerException
        at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:674) ~[BlockGenericPipe.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:456) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
```

Luckily the server keeps running. It just boots the player that was close to the buildcraft stuff.

**Comment by asiekierka** [comment]
Update to 7.0.11
