### ISSUE TITLE
Robot Integration Recipe crash with latest Buildcraft 7

### ISSUE THREAD

**Issue by cocopuffs99** [BuildCraft/BuildCraft#2836]
---- Minecraft Crash Report ----
// Oops.

Time: 6/24/15 10:42 AM
Description: Updating screen events

java.lang.ClassCastException: buildcraft.robotics.RobotIntegrationRecipe cannot be cast to buildcraft.api.recipes.IFlexibleRecipe
	at buildcraft.compat.nei.RecipeHandlerIntegrationTable.loadCraftingRecipes(RecipeHandlerIntegrationTable.java:83)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
	at buildcraft.compat.nei.RecipeHandlerBase.loadCraftingRecipes(RecipeHandlerBase.java:80)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------

full crash log: http://pastebin.com/cuy9dqkC

**Comment by hea3ven** [comment]
Update BuildCraft-Compat.

**Comment by cocopuffs99** [comment]
updated to buildcraft compat 7.08 and now it works like a charm! thank you
