### ISSUE TITLE
Crash during mod initialization

### ISSUE THREAD

**Issue by sonikfyre** [BuildCraft/BuildCraft#2844]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27/06/15 12:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/energy/BlockEngine
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: buildcraft/energy/BlockEngine
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.energy.BlockEngine
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 176144840 bytes (167 MB) / 446517248 bytes (425 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 145 mods loaded, 145 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UC	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UC	appliedenergistics2-core{rv2-stable-8} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UC	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) 
	UC	OpenModsCore{0.7} [OpenModsCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	debug{1.0} [debug] (denseores-1.5.jar) 
	UC	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UC	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UC	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
	UC	BuildCraft|Core{7.0.12} [BuildCraft] (buildcraft-7.0.12.jar) 
	UC	BuildCraft|Energy{7.0.12} [BC Energy] (buildcraft-7.0.12.jar) 
	UC	BuildCraft|Factory{7.0.12} [BC Factory] (buildcraft-7.0.12.jar) 
	UC	BuildCraft|Transport{7.0.12} [BC Transport] (buildcraft-7.0.12.jar) 
	UC	BuildCraft|Builders{7.0.12} [BC Builders] (buildcraft-7.0.12.jar) 
	UC	BuildCraft|Silicon{7.0.12} [BC Silicon] (buildcraft-7.0.12.jar) 
	UE	Additional-Buildcraft-Objects{MC1.7.10-BC6.4release2.7.1} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC6.4-release2.7.1.jar) 
	UC	appliedenergistics2{rv2-stable-8} [Applied Energistics 2] (appliedenergistics2-rv2-stable-8.jar) 
	UC	bdlib{1.8.1.87} [BD Lib] (bdlib-1.8.1.87-mc1.7.10.jar) 
	UC	ae2stuff{0.3.1.33} [AE2 Stuff] (ae2stuff-0.3.1.33-mc1.7.10.jar) 
	UC	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UC	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UC	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UC	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UC	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UC	AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) 
	UC	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UC	bluepower{0.2.947} [Blue Power] (BluePower-1.7.10-0.2.947-universal.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	Botania{r1.6-192} [Botania] (Botania r1.6-192.jar) 
	UC	BuildCraft|Robotics{7.0.12} [BC Robotics] (buildcraft-7.0.12.jar) 
	UC	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UC	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UC	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UC	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UC	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UC	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UC	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) 
	UC	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UC	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UC	EnderTech{1.7.10-0.3.2.388} [EnderTech] (EnderTech-1.7.10-0.3.2.388.jar) 
	UC	EnderZoo{1.7.10-1.0.11.28} [Ender Zoo] (EnderZoo-1.7.10-1.0.11.28.jar) 
	UC	EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) 
	UC	exnihilo{1.38-41} [Ex Nihilo] (Ex-Nihilo-1.38-41.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UC	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) 
	UC	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
	UC	exastris{MC1.7.10-1.16-35} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-35.jar) 
	UC	extracells{2.2.71} [Extra Cells 2] (ExtraCells-1.7.10-2.2.71b121.jar) 
	UC	ExtraUtilities{1.2.6} [Extra Utilities] (extrautilities-1.2.6.jar) 
	UC	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UC	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UC	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-5a.jar) 
	UC	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UC	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UC	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UC	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
	UC	ImmersiveEngineering{0.3.1} [Immersive Engineering] (ImmersiveEngineering-0.3.1.jar) 
	UC	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UC	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UC	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
	UC	LookingGlass{0.1.0.00} [Looking Glass] (lookingglass-1.7.10-0.1.0.00.jar) 
	UC	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UC	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.7.10-universal.jar) 
	UC	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6-1.7.10-universal.jar) 
	UC	MekanismGenerators{8.1.5} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.5.246.jar) 
	UC	MekanismTools{8.1.5} [MekanismTools] (MekanismTools-1.7.10-8.1.5.246.jar) 
	UC	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	Mystcraft{0.11.13.00} [Mystcraft] (mystcraft-1.7.10-0.11.13.00.jar) 
	UC	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MrTJPCoreMod{1.0.9.18} [MrTJPCore] (MrTJPCore-1.7.10-1.0.9.18-universal.jar) 
	UC	ProjRed|Core{4.7.0pre1.84} [ProjectRed] (ProjectRed-1.7.10-4.7.0pre1.84-Base.jar) 
	UC	ProjRed|Exploration{4.7.0pre1.84} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.7.0pre1.84-World.jar) 
	UC	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) 
	UC	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) 
	UC	Morpheus{1.7.10-1.6.4} [Morpheus] (Morpheus-1.7.10-1.6.4.jar) 
	UC	NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UC	NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UC	NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UC	NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UC	NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UC	NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) 
	UC	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
	UC	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UC	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UC	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) 
	UC	OpenMods{0.7} [OpenMods] (OpenModsLib-1.7.10-0.7.jar) 
	UC	OpenBlocks{1.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.jar) 
	UC	OpenPeripheralCore{1.1.1} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.1.1.jar) 
	UC	OpenPeripheral{0.3} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.3.jar) 
	UC	OpenPeripheralIntegration{0.2} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.2.jar) 
	UC	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.1.jar) 
	UC	PeripheralsPlusPlus{1.2.9} [Peripherals++] (Peripherals++-1.2.9.jar) 
	UC	PneumaticCraft{1.8.1-83} [PneumaticCraft] (PneumaticCraft-1.7.10-1.8.1-83-universal.jar) 
	UC	ProjRed|Transmission{4.7.0pre1.84} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.7.0pre1.84-Integration.jar) 
	UC	ProjRed|Transportation{4.7.0pre1.84} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.7.0pre1.84-Mechanical_beta.jar) 
	UC	ProjRed|Compatibility{4.7.0pre1.84} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.7.0pre1.84-Compat.jar) 
	UC	ProjRed|Integration{4.7.0pre1.84} [ProjectRed-Integration] (ProjectRed-1.7.10-4.7.0pre1.84-Integration.jar) 
	UC	ProjRed|Illumination{4.7.0pre1.84} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.7.0pre1.84-Lighting.jar) 
	UC	ProjRed|Expansion{4.7.0pre1.84} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.7.0pre1.84-Mechanical_beta.jar) 
	UC	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UC	StevesAddons{0.10.12} [Steve's Addons] (StevesAddons-1.7.10-0.10.12.jar) 
	UC	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UC	thaumicenergistics{0.8.10.5} [Thaumic Energistics] (thaumicenergistics-0.8.10.5.jar) 
	UC	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) 
	UC	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UC	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) 
	UC	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UC	ttCore{MC1.7.10-0.1.0-56} [ttCore] (ttCore-MC1.7.10-0.1.0-56.jar) 
	UC	VersionChecker{1.1.9} [Version Checker] (VersionChecker-1.1.9.jar) 
	UC	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UC	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-14.jar) 
	UC	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UC	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) 
	UC	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UC	denseores{1.0} [Dense Ores] (denseores-1.5.jar) 
	UC	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UC	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GT 520MX/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
	CoFHCore: -[1.7.10]3.0.2-262
	AE2 Version: stable rv2-stable-8 for Forge 10.13.2.1291
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0-80
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.0.0-122

**Comment by sonikfyre** [comment]
Issue was caused by Additional Buildcraft Objects.
