### ISSUE TITLE
Problems running MC with BC + BC additions 2.0

### ISSUE THREAD

**Issue by dcitrigno** [BuildCraft/BuildCraft#2912]
first off i don't have this problem with Buildcraft  on it's own it runs fine with version 1.7.10 of minecraft with Forge the Eureka file is also fine it only happens with i run MC with  BC additons 2.0 the eariler version of Additions didn't to this it also didn't need Eureka to run either.

what follows is a copy and paste of my Error Log:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/23/15 7:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerExtractionHandler(Lbuildcraft/api/transport/IExtractionHandler;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerExtractionHandler(Lbuildcraft/api/transport/IExtractionHandler;)V
	at buildcraft.BuildCraftTransport.preInit(BuildCraftTransport.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 89042536 bytes (84 MB) / 245395456 bytes (234 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCH	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCH	BuildCraft|Core{5.0.7} [BuildCraft] (01BuildCraft-Mod-1.7.10.jar) 
	UCH	BuildCraft|Builders{5.0.7} [BC Builders] (01BuildCraft-Mod-1.7.10.jar) 
	UCE	BuildCraft|Energy{5.0.7} [BC Energy] (01BuildCraft-Mod-1.7.10.jar) 
	UCH	BuildCraft|Factory{5.0.7} [BC Factory] (01BuildCraft-Mod-1.7.10.jar) 
	UCE	BuildCraft|Transport{5.0.7} [BC Transport] (01BuildCraft-Mod-1.7.10.jar) 
	UCE	BuildCraft|Silicon{5.0.7} [BC Silicon] (01BuildCraft-Mod-1.7.10.jar) 
	UCH	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCH	bcadditions{2.0} [Buildcraft Additions] (BuildcraftAdditions-1.7.10-2.0.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 760/PCIe/SSE2'

As you can see Energy, Transport and Silicon all error don't understand why they don't error when BC is being excuted without Addition since it obviously these modules have a problem.

**Comment by psxlover** [comment]
You do realise that BC 5.0.7 is ancient right? 
Also bcadditions 1.7.2 needed BC 6.1.5 and up...

**Comment by asiekierka** [comment]
Where'd you get 5.0.7 from?

**Comment by AEnterprise** [comment]
also please in the future report BCA bugs on the BCA issue tracker, not the BC one

**Comment by dcitrigno** [comment]
Majority of my mods came from  9minecraft.net, I'd like to see versions of both MC and RC for 1.8

Date: Thu, 23 Jul 2015 23:34:15 -0700

**Comment by dcitrigno** [comment]
To PSXlover, no i didn't realize this was an older version I had a copy of BC from when i use to play a couple of years ago version 1.4.1 or2  of MC at any rate i fixed the problem myself by completely updating to 1.7.10 of  both  BC and BCA  problem i do have is now with the upgrade to version 2.0 of BSA

Date: Thu, 23 Jul 2015 16:58:48 -0700

**Comment by asiekierka** [comment]
Use our official site: http://mod-buildcraft.com/. 9minecraft is a trap!

**Comment by dcitrigno** [comment]
@ Adrian, without me getting into an argument, how is 9minecraft.net a trap usually if a site is bad a program like Malwarebytes or even a plugin like Web of Trust would warn me. however i've not had any problems but as with anything with usage problems will show. P.S. i've not used the newer version of BCA yet will see if i can grab a good copy from the website (mod.buildcraft.com)

David.

Date: Sun, 26 Jul 2015 10:13:01 -0700

**Comment by gjgfuj** [comment]
9minecraft is unofficial and a repost that is not approved at all. You
never know what they'll do to it. Don't trust them at all. Malwarebytes
probably just doesn't know about them.
