### ISSUE TITLE
Game can not start (buildcraft-7.0.25 with buildcraft-compat-7.0.12)

### ISSUE THREAD

**Issue by oldjunyi** [BuildCraft/BuildCraft#3031]
If I only place these in mods folder, everything goes right:
* buildcraft-7.0.25-core.jar
* buildcraft-7.0.25-energy.jar
* buildcraft-7.0.25-factory.jar
* buildcraft-7.0.25-silicon.jar
* buildcraft-7.0.25-transport.jar

But If I add:**buildcraft-compat-7.0.12.jar** to mods folder, the game shows:
![temp](https://cloud.githubusercontent.com/assets/641817/10046153/a2c2b1de-6239-11e5-9370-b82a401b07b3.png)

fml logs here:
https://gist.github.com/oldjunyi/cfa95b04281a490cfe80

**Comment by liach** [comment]
```
21:24:38] [Client thread/TRACE] [FML/]: Located mcmod.info file in file buildcraft-7.0.25-core.jar
[21:24:38] [Client thread/WARN] [FML/]: Zip file buildcraft-7.0.25-core.jar failed to read properly, it will be ignored
java.lang.NullPointerException
	at cpw.mods.fml.common.MetadataCollection.parseModMetadataList(MetadataCollection.java:88) ~[MetadataCollection.class:?]
	at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:71) ~[MetadataCollection.class:?]
	at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [JarDiscoverer.class:?]
	at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
	at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
	at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:131) [ModDiscoverer.class:?]
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by gabor6505** [comment]
I also have this issue, I just updated the mods, and now I can't launch the game.

**Comment by liach** [comment]
Actually #3034 has a better description of this bug.
