### ISSUE TITLE
[BC7.1] Crash when using electronic library

### ISSUE THREAD

**Issue by Furchendackel** [BuildCraft/BuildCraft#3045]
I encountered an error using the electronic library.

If I try to use the library to store a blueprint, the client crashes as soon as I drop the blueprint in the approriate slot.
Retrieving blueprints (writing a construction plan to a blank blueprint) works fine.
It doesn't matter which structure is stored on the blueprint, it even happens with a blank one.

BC version: 7.1.5
Forge version: 10.13.4.1492
Other mods (all at latest stable releases):
BC compat, Forestry, IC2 experimental, CoFH-Core, Thermal Series (Foundation, Expansion, Dynamics), MinecraftReloaded, NetherOres, AppliedEnergistics 2, Railcraft

The crash only affects the client, the server continues to run fine.

Here's the crash log:
````
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 01.10.15 07:33
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at buildcraft.builders.LibraryDatabase.exists(LibraryDatabase.java:177)
	at buildcraft.builders.ItemBlueprint.getId(ItemBlueprint.java:118)
	at buildcraft.builders.ItemBlueprint.isContentReadable(ItemBlueprint.java:107)
	at buildcraft.builders.LibraryBlueprintTypeHandler.isHandler(LibraryBlueprintTypeHandler.java:22)
	at buildcraft.builders.TileBlueprintLibrary.findHandler(TileBlueprintLibrary.java:194)
	at buildcraft.builders.TileBlueprintLibrary.func_70299_a(TileBlueprintLibrary.java:141)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at buildcraft.core.lib.gui.BuildCraftContainer.func_75144_a(BuildCraftContainer.java:96)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at buildcraft.core.lib.gui.GuiBuildCraft.func_146286_b(GuiBuildCraft.java:264)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.builders.LibraryDatabase.exists(LibraryDatabase.java:177)
	at buildcraft.builders.ItemBlueprint.getId(ItemBlueprint.java:118)
	at buildcraft.builders.ItemBlueprint.isContentReadable(ItemBlueprint.java:107)
	at buildcraft.builders.LibraryBlueprintTypeHandler.isHandler(LibraryBlueprintTypeHandler.java:22)
	at buildcraft.builders.TileBlueprintLibrary.findHandler(TileBlueprintLibrary.java:194)
	at buildcraft.builders.TileBlueprintLibrary.func_70299_a(TileBlueprintLibrary.java:141)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at buildcraft.core.lib.gui.BuildCraftContainer.func_75144_a(BuildCraftContainer.java:96)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at buildcraft.core.lib.gui.GuiBuildCraft.func_146286_b(GuiBuildCraft.java:264)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: buildcraft.builders.gui.GuiBlueprintLibrary

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Furchendackel'/3584311, l='MpServer', x=290,52, y=65,62, z=-95,04]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,256), Chunk: (at 8,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25672028 game time, 6165 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 110 total; [EntityPainting['Painting'/3584310, l='MpServer', x=301,00, y=95,00, z=-140,94], EntityPainting['Painting'/3584308, l='MpServer', x=308,94, y=95,00, z=-131,50], EntityCreeper['Creeper'/3498038, l='MpServer', x=315,84, y=73,00, z=-89,53], EntityPainting['Painting'/3584309, l='MpServer', x=308,94, y=95,00, z=-134,00], EntityPainting['Painting'/3324215, l='MpServer', x=311,00, y=95,00, z=-92,06], EntitySheep['Sheep'/3584307, l='MpServer', x=311,91, y=64,00, z=-136,94], EntityCreeper['Creeper'/3584319, l='MpServer', x=233,97, y=59,00, z=-54,66], EntityClientPlayerMP['Furchendackel'/3584311, l='MpServer', x=290,52, y=65,62, z=-95,04], EntityBat['Bat'/3584316, l='MpServer', x=256,63, y=59,10, z=-44,47], EntityPainting['Painting'/3324216, l='MpServer', x=311,00, y=95,00, z=-104,94], EntityBlitz['Blitz'/3584317, l='MpServer', x=263,13, y=60,00, z=-43,50], EntityBat['Bat'/3584314, l='MpServer', x=269,53, y=62,10, z=-48,47], EntityCreeper['Creeper'/3584315, l='MpServer', x=348,50, y=64,00, z=-85,50], EntityBat['Bat'/3584313, l='MpServer', x=268,00, y=62,10, z=-48,56], EntityZombie['Zombie'/3507236, l='MpServer', x=316,88, y=73,00, z=-89,69], EntityZombie['Zombie'/3507235, l='MpServer', x=310,59, y=73,00, z=-86,69], EntityPainting['Painting'/2193719, l='MpServer', x=305,06, y=86,00, z=-103,50], EntityPainting['Painting'/2193720, l='MpServer', x=293,06, y=86,00, z=-86,00], EntityPainting['Painting'/2195202, l='MpServer', x=311,00, y=86,00, z=-92,06], EntityPainting['Painting'/2193415, l='MpServer', x=293,06, y=87,00, z=-103,00], EntityPainting['Painting'/2196230, l='MpServer', x=311,00, y=86,00, z=-104,94], EntityPainting['Painting'/2193417, l='MpServer', x=293,06, y=86,00, z=-111,00], EntityPainting['Painting'/2193416, l='MpServer', x=298,06, y=86,00, z=-91,00], EntityPainting['Painting'/2193419, l='MpServer', x=298,06, y=86,00, z=-106,00], EntitySheep['Sheep'/3584284, l='MpServer', x=333,78, y=64,00, z=-103,63], EntityCreeper['Creeper'/3520287, l='MpServer', x=304,66, y=82,00, z=-121,06], EntityPainting['Painting'/2193418, l='MpServer', x=305,06, y=86,00, z=-93,50], EntityItem['item.item.rottenFlesh'/3584285, l='MpServer', x=327,97, y=72,63, z=-102,56], EntityPainting['Painting'/2193420, l='MpServer', x=296,00, y=85,50, z=-112,94], EntityPainting['Painting'/2194719, l='MpServer', x=308,94, y=86,00, z=-89,00], EntityZombie['Zombie'/3584374, l='MpServer', x=224,50, y=63,00, z=-30,50], EntityPainting['Painting'/2193416, l='MpServer', x=298,06, y=86,00, z=-91,00], EntityPainting['Painting'/2194541, l='MpServer', x=300,00, y=86,00, z=-84,06], EntityPainting['Painting'/2193720, l='MpServer', x=293,06, y=86,00, z=-86,00], EntityCreeper['Creeper'/3584380, l='MpServer', x=215,50, y=63,00, z=-37,50], EntityPainting['Painting'/2193418, l='MpServer', x=305,06, y=86,00, z=-93,50], EntityPainting['Painting'/2194541, l='MpServer', x=300,00, y=86,00, z=-84,06], EntityPainting['Painting'/3324215, l='MpServer', x=311,00, y=95,00, z=-92,06], EntityPainting['Painting'/2194719, l='MpServer', x=308,94, y=86,00, z=-89,00], EntityPainting['Painting'/2195202, l='MpServer', x=311,00, y=86,00, z=-92,06], EntityItem['item.tile.torch'/3584358, l='MpServer', x=237,53, y=64,13, z=-131,59], EntityPainting['Painting'/2196307, l='MpServer', x=308,94, y=85,50, z=-86,00], EntityItem['item.tile.torch'/3584359, l='MpServer', x=240,88, y=63,13, z=-156,63], EntityItem['item.tile.torch'/3584356, l='MpServer', x=237,66, y=63,13, z=-143,69], EntityPainting['Painting'/2193415, l='MpServer', x=293,06, y=87,00, z=-103,00], EntityPainting['Painting'/2193417, l='MpServer', x=293,06, y=86,00, z=-111,00], EntityItem['item.tile.torch'/3584354, l='MpServer', x=239,88, y=62,13, z=-131,81], EntityPainting['Painting'/2193419, l='MpServer', x=298,06, y=86,00, z=-106,00], EntityItem['item.tile.torch'/3584355, l='MpServer', x=239,50, y=63,13, z=-141,56], EntityPainting['Painting'/2193746, l='MpServer', x=298,06, y=86,50, z=-111,00], EntityZombie['Zombie'/3584352, l='MpServer', x=238,34, y=64,00, z=-44,84], EntityItem['item.tile.torch'/3584353, l='MpServer', x=239,84, y=63,13, z=-128,03], EntityPainting['Painting'/3324216, l='MpServer', x=311,00, y=95,00, z=-104,94], EntityPainting['Painting'/2193719, l='MpServer', x=305,06, y=86,00, z=-103,50], EntityBat['Bat'/3584367, l='MpServer', x=214,09, y=62,10, z=-60,75], EntityPainting['Painting'/2195957, l='MpServer', x=308,94, y=86,00, z=-109,00], EntityZombie['Zombie'/3584364, l='MpServer', x=296,13, y=64,00, z=-19,28], EntityPig['Pig'/3584365, l='MpServer', x=317,53, y=64,00, z=-159,22], EntityItem['item.tile.torch'/3584362, l='MpServer', x=244,63, y=64,13, z=-157,28], EntityPainting['Painting'/2196230, l='MpServer', x=311,00, y=86,00, z=-104,94], EntityZombie['Zombie'/3584363, l='MpServer', x=338,31, y=73,00, z=-18,41], EntityItem['item.tile.torch'/3584360, l='MpServer', x=240,00, y=63,13, z=-154,88], EntitySheep['Sheep'/3583848, l='MpServer', x=317,16, y=64,00, z=-124,84], EntityPainting['Painting'/2193420, l='MpServer', x=296,00, y=85,50, z=-112,94], EntityZombie['Zombie'/3584343, l='MpServer', x=255,50, y=60,00, z=-31,50], EntityPainting['Painting'/3584310, l='MpServer', x=301,00, y=95,00, z=-140,94], EntityPainting['Painting'/3584308, l='MpServer', x=308,94, y=95,00, z=-131,50], EntitySkeleton['Skeleton'/3584338, l='MpServer', x=245,44, y=57,00, z=-56,06], EntityPainting['Painting'/3584309, l='MpServer', x=308,94, y=95,00, z=-134,00], EntityBat['Bat'/3584339, l='MpServer', x=231,47, y=62,10, z=-50,25], EntityZombie['Zombie'/3584336, l='MpServer', x=232,31, y=57,00, z=-50,50], EntityBlitz['Blitz'/3546192, l='MpServer', x=314,34, y=83,00, z=-109,34], EntitySkeleton['Skeleton'/3584337, l='MpServer', x=229,91, y=60,00, z=-58,56], EntityZombie['Zombie'/3584350, l='MpServer', x=234,50, y=58,00, z=-42,94], EntityItem['item.tile.torch'/3584351, l='MpServer', x=234,72, y=64,13, z=-40,41], EntityItem['item.tile.torch'/3584348, l='MpServer', x=229,50, y=62,13, z=-33,56], EntityCreeper['Creeper'/3584349, l='MpServer', x=235,47, y=57,00, z=-44,69], EntityItem['item.tile.torch'/3584347, l='MpServer', x=227,34, y=62,13, z=-32,66], EntitySquid['Squid'/3584344, l='MpServer', x=244,50, y=60,00, z=-33,06], EntityItem['item.tile.torch'/3584345, l='MpServer', x=239,25, y=59,13, z=-35,88], EntityItem['item.tile.torch'/3584326, l='MpServer', x=242,16, y=59,13, z=-34,88], EntityItem['item.tile.torch'/3584327, l='MpServer', x=254,19, y=59,13, z=-34,44], EntityZombie['Zombie'/3584324, l='MpServer', x=249,50, y=60,00, z=-35,50], EntityPainting['Painting'/2196307, l='MpServer', x=308,94, y=85,50, z=-86,00], EntityItem['item.tile.torch'/3584325, l='MpServer', x=245,16, y=60,13, z=-35,69], EntityPainting['Painting'/2193746, l='MpServer', x=298,06, y=86,50, z=-111,00], EntitySkeleton['Skeleton'/3584322, l='MpServer', x=290,50, y=73,00, z=-146,50], EntityBat['Bat'/3584323, l='MpServer', x=254,75, y=60,10, z=-43,25], EntityCreeper['Creeper'/3584320, l='MpServer', x=241,50, y=58,00, z=-56,50], EntityCreeper['Creeper'/3584321, l='MpServer', x=232,50, y=126,00, z=-92,50], EntityItem['item.tile.torch'/3584334, l='MpServer', x=242,63, y=64,13, z=-139,06], EntityItem['item.tile.torch'/3584335, l='MpServer', x=243,97, y=64,13, z=-143,91], EntityItem['item.tile.torch'/3584332, l='MpServer', x=242,81, y=61,13, z=-131,53], EntityItem['item.tile.torch'/3584333, l='MpServer', x=241,69, y=62,13, z=-137,09], EntityCreeper['Creeper'/3584330, l='MpServer', x=244,50, y=61,00, z=-36,50], EntityItem['item.tile.torch'/3584331, l='MpServer', x=241,38, y=62,13, z=-129,09], EntityZombie['Zombie'/3584328, l='MpServer', x=245,50, y=56,00, z=-43,50], EntitySkeleton['Skeleton'/3584329, l='MpServer', x=251,16, y=58,00, z=-39,50], EntityZombie['Zombie'/3584436, l='MpServer', x=221,50, y=63,00, z=-30,50], EntitySkeleton['Skeleton'/3584437, l='MpServer', x=215,09, y=62,00, z=-31,50], EntityCreeper['Creeper'/3584432, l='MpServer', x=217,50, y=63,00, z=-27,50], EntitySkeleton['Skeleton'/3584447, l='MpServer', x=239,31, y=62,04, z=-160,25], EntityCreeper['Creeper'/3584442, l='MpServer', x=218,13, y=31,06, z=-153,31], EntityZombie['Zombie'/3497621, l='MpServer', x=314,14, y=73,00, z=-107,83], EntityItem['item.item.dyePowder.black'/3584906, l='MpServer', x=244,37, y=60,13, z=-34,29], EntitySkeleton['Skeleton'/3546877, l='MpServer', x=316,69, y=73,00, z=-107,75], EntitySkeleton['Skeleton'/3482617, l='MpServer', x=315,91, y=73,00, z=-88,44], EntityPainting['Painting'/2195957, l='MpServer', x=308,94, y=86,00, z=-109,00], EntityCreeper['Creeper'/3584964, l='MpServer', x=302,50, y=82,00, z=-137,50], EntityCreeper['Creeper'/3500750, l='MpServer', x=314,78, y=73,00, z=-89,47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.2.0-13-generic
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 585643544 bytes (558 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	BuildCraft|Core{7.1.5} [BuildCraft] (buildcraft-7.1.5.jar) 
	UCHIJA	BuildCraft|Builders{7.1.5} [BC Builders] (buildcraft-7.1.5.jar) 
	UCHIJA	BuildCraft|Transport{7.1.5} [BC Transport] (buildcraft-7.1.5.jar) 
	UCHIJA	BuildCraft|Energy{7.1.5} [BC Energy] (buildcraft-7.1.5.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.5} [BC Silicon] (buildcraft-7.1.5.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.5} [BC Robotics] (buildcraft-7.1.5.jar) 
	UCHIJA	BuildCraft|Factory{7.1.5} [BC Factory] (buildcraft-7.1.5.jar) 
	UCHIJA	IC2{2.2.780-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.780-experimental.jar) 
	UCHIJA	Forestry{4.0.2.30} [Forestry for Minecraft] (forestry_1.7.10-3.6.9.28.jar) 
	UCHIJA	BuildCraft|Compat{7.1.0} [BuildCraft Compat] (buildcraft-compat-7.1.0.jar) 
	UCHIJA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 352.41' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.1.0-161
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 352.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
````

**Comment by asiekierka** [comment]
Could you send me your config/buildcraft/main.cfg?

**Comment by Furchendackel** [comment]
Config of the server (client should be identical, never changed anything there):


# Configuration file

blueprints {
    # Location for the client blueprint database (used by the Electronic Library).
    S:clientDatabaseDirectory="$MINECRAFT/blueprints"

    # blocks that should be excluded from the builder.
    S:excludedBlocks <
     >

    # mods that should be excluded from the builder.
    S:excludedMods <
     >

    # DEPRECATED - USED ONLY FOR COMPATIBILITY
    S:serverDatabaseDirectory="$MINECRAFT/config/buildcraft/blueprints/server"
}


builders {
    # Should the builder and filler drop the cleared blocks?
    B:dropBrokenBlocks=false
}


debug {
    B:printBlueprintSchematicList=false

    # Print a list of all registered facades.
    B:printFacadeList=false
}


display {
    # Should I enable colorblind mode?
    B:colorBlindMode=false

    # Should all fluid values (mB, mB/t) be hidden?
    B:hideFluidValues=false

    # Should all power values (RF, RF/t) be hidden?
    B:hidePowerValues=false
}


experimental {
    B:disableThreadedZoneMapGen=false

    # Should kinesis pipes lose power over distance (think IC2 or BC pre-3.7)?
    B:kinesisPowerLossOnTravel=false
}


general {
    # Blacklisted robots boards
    S:boards.blacklist <
     >

    # Should engines explode upon overheat?
    B:canEnginesExplode=false

    # adjust energy value of Fuel in Combustion Engines
    D:fuel.fuel.combustion=1.0

    # adjust output energy by Fuel in Combustion Engines
    I:fuel.fuel.combustion.energyOutput=60

    # adjust energy value of Oil in Combustion Engines
    D:fuel.oil.combustion=1.0

    # adjust output energy by Oil in Combustion Engines
    I:fuel.oil.combustion.energyOutput=30

    # How long, in seconds, should items stay on the ground? (Vanilla = 300, default = 60)
    I:itemLifespan=60

    # Set the maximum marker range.
    I:markerRange=64

    # Should the mining well only be usable once after placing?
    I:miningDepth=256

    # Should oil burn when lit on fire?
    B:oilCanBurn=true

    # Should oil be dense and drag entities down?
    B:oilIsDense=true

    # Allows admins to whitelist or blacklist pumping of specific fluids in specific dimensions.
    # Eg. "-/-1/Lava" will disable lava in the nether. "-/*/Lava" will disable lava in any dimension. "+/0/*" will enable any fluid in the overworld.
    # Entries are comma seperated, banned fluids have precedence over allowed ones.Default is "+/*/*,+/-1/Lava" - the second redundant entry ("+/-1/lava") is there to show the format.
    S:pumpDimensionControl=+/*/*,+/-1/lava

    # Should pumps consume water? Enabling this might cause performance issues!
    B:pumpsConsumeWater=false

    # Do pumps need real (non-redstone) power?
    B:pumpsNeedRealPower=false

    # Should I check the BuildCraft version on startup?
    B:updateCheck=true
    S:version=7.1.5

    pipes {
        # What should the base flow rate of a fluid pipe be?
        I:baseFluidRate=10

        # What block types should be blacklisted from being a facade?
        S:facadeBlacklist <
            minecraft:end_portal_frame
            minecraft:grass
            minecraft:leaves
            minecraft:leaves2
            minecraft:lit_pumpkin
            minecraft:lit_redstone_lamp
            minecraft:mob_spawner
            minecraft:monster_egg
            minecraft:redstone_lamp
            minecraft:double_stone_slab
            minecraft:double_wooden_slab
            minecraft:sponge
         >

        # Should the blacklist be treated as a whitelist instead?
        B:facadeBlacklistAsWhitelist=false

        # Should non-laser (crafting table) facade recipes be forced?
        B:facadeNoLaserRecipe=false

        # Should all BC facades be shown in Creative/NEI, or just a few carefully chosen ones?
        B:facadeShowAllInCreative=true

        # How hard to break should a pipe be?
        D:hardness=0.25

        # Should I enable an alternate Waterproof recipe, based on slimeballs?
        B:slimeballWaterproofRecipe=false
    }

    quarry {
        # Should the quarry keep the chunks it is working on loaded?
        B:doChunkLoading=true

        # Should the quarry only be usable once after placing?
        B:oneTimeUse=false
    }

}


network {
    # How often, in ticks, should full network sync packets be sent? Increasing this might help network performance.
    I:longUpdateFactor=40

    # How often, in ticks, should network update packets be sent? Increasing this might help network performance.
    I:updateFactor=10
}


power {
    # The cost multiplier for Chipsets
    D:chipsetCostMultiplier=1.0

    # What should be the multiplier of all gate power costs?
    D:gateCostMultiplier=1.0

    # What should the multiplier of all mining-related power usage be?
    D:miningUsageMultiplier=1.0
}


vars {
}


worldgen {
    # Should BuildCraft generate anything in the world?
    B:enable=true

    # Should BuildCraft generate water springs?
    B:generateWaterSprings=true

    # How high should be the probability of an oil well generating?
    D:oilWellGenerationRate=1.0

    # Should I spawn oil springs?
    B:spawnOilSprings=true

    biomes {
        # The id for the Oil Desert biome
        I:biomeOilDesert=127

        # The id for the Oil Ocean biome
        I:biomeOilOcean=126

        # IDs or Biome Types (e.g. SANDY,OCEAN) of biomes that should have GREATLY increased oil generation rates.
        S:excessiveOilIDs <
         >

        # IDs or Biome Types (e.g. SANDY,OCEAN) of biomes that are excluded from generating oil.
        S:excludeOilIDs <
            Sky
            Hell
         >

        # IDs or Biome Types (e.g. SANDY,OCEAN) of biomes that should have increased oil generation rates.
        S:increasedOilIDs <
            SANDY
            Taiga
         >
    }

}

**Comment by asiekierka** [comment]
And your complete fml-client-latest.log? I'm confused by this bug...

**Comment by Furchendackel** [comment]
I've investigated a little further... If I download the world from the server and start it locally, it works. No crash, blueprint is saved correctly.

I have removed the contents of the buildcraft/blueprints folder inside the world folder. Now it works fine, no crash anymore.

Do you still need the fml-client-latest.log?

**Comment by asiekierka** [comment]
No. Try this build: http://asie.pl/bc716a.jar

**Comment by asiekierka** [comment]
Fixed via https://github.com/BuildCraft/BuildCraft/commit/97295767359039ddc70d2d3c09738d1ba8581f2a
