### ISSUE TITLE
Delivery robot gone after chunk unload

### ISSUE THREAD

**Issue by dj3520** [BuildCraft/BuildCraft#3048]
I was watching my server's console while playing. After I left my base I saw this text fly by. Afterwords my delivery robot disappeared. Cheating another one in has everything working again, but I'm the only one who can do that. BC 7.1.5 on KCauldron-1.7.10-1492.155, though this happens on Cauldron-1.7.10-1.1307.06.218 as well.

[13:31:25] [Server thread/ERROR] [FML/]: An Entity type buildcraft.robotics.EntityRobot has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1588) ~[sa.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1507) ~[sa.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:367) [aqk.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.dynmap.forge.ForgeMapChunkCache.getLoadedChunks(ForgeMapChunkCache.java:1411) [ForgeMapChunkCache.class:?]
	at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:760) [DynmapPlugin$ForgeServer$1.class:?]
	at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:755) [DynmapPlugin$ForgeServer$1.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:852) [DynmapPlugin$ForgeServer.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_278_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) [?:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at buildcraft.robotics.StackRequest.writeToNBT(StackRequest.java:89) ~[StackRequest.class:?]
	at buildcraft.robotics.boards.BoardRobotDelivery.writeSelfToNBT(BoardRobotDelivery.java:109) ~[BoardRobotDelivery.class:?]
	at buildcraft.api.robots.AIRobot.writeToNBT(AIRobot.java:169) ~[AIRobot.class:?]
	at buildcraft.api.robots.AIRobot.writeToNBT(AIRobot.java:175) ~[AIRobot.class:?]
	at buildcraft.robotics.EntityRobot.func_70014_b(EntityRobot.java:534) ~[EntityRobot.class:?]
	at net.minecraft.entity.Entity.func_70109_d(Entity.java:1571) ~[sa.class:?]
	... 18 more
[13:31:25]

**Comment by liach** [comment]
Try remove dynmap?

**Comment by dj3520** [comment]
Strange I didn't see that and strange that dynmap of all things is what could be causing this.

**Comment by liach** [comment]
Really? I guessed this because
> ```
at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:760) [DynmapPlugin$ForgeServer$1.class:?]
at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:755) [DynmapPlugin$ForgeServer$1.class:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:852) [DynmapPlugin$ForgeServer.class:?]
```

**Comment by dj3520** [comment]
I know I saw that as soon as you said something. I was like "Dynmap? Wait, how did you know I even had that." Slipped right past me.

**Comment by liach** [comment]
I think I need to refer [Thog's words] (https://github.com/BuildCraft/BuildCraft/issues/2934#issuecomment-127085059)... That might be the issue.

**Comment by dj3520** [comment]
Seems similar. Though I am running BCC 7.1.0

Waiting to see if removing dynmap will fix things. Unfortunately I can't fire off the event on command so I can only wait and see if it goes off again.

**Comment by asiekierka** [comment]
Fixed in BC 7.1.6, I believe.

2015-10-02 17:30 GMT+02:00 dj3520 <notifications@github.com>:

**Comment by dj3520** [comment]
Guess I'll see. Updated to BC 7.1.7 & BCC 7.1.1
