### ISSUE TITLE
KCauldron server crashed with Buildcraft 7.1.6

### ISSUE THREAD

**Issue by kenvix** [BuildCraft/BuildCraft#3049]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 10/2/15 11:17 PM
Description: Ticking block entity

java.lang.NoSuchFieldError: texture
	at buildcraft.core.lib.EntityBlock.<init>(EntityBlock.java:21)
	at buildcraft.factory.FactoryProxy.newPumpTube(FactoryProxy.java:28)
	at buildcraft.factory.TilePump.createTube(TilePump.java:179)
	at buildcraft.factory.TilePump.func_145845_h(TilePump.java:83)
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.core.lib.EntityBlock.<init>(EntityBlock.java:21)
	at buildcraft.factory.FactoryProxy.newPumpTube(FactoryProxy.java:28)
	at buildcraft.factory.TilePump.createTube(TilePump.java:179)
	at buildcraft.factory.TilePump.func_145845_h(TilePump.java:83)

-- Block entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.factory.TilePump // buildcraft.factory.TilePump
	Block type: ID #454 (tile.pumpBlock // buildcraft.factory.BlockPump)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (727,128,3003), Chunk: (at 7,8,11 in 45,187; contains blocks 720,0,2992 to 735,255,3007), Region: (1,5; contains chunks 32,160 to 63,191, blocks 512,0,2560 to 1023,255,3071)
	Actual block type: ID #454 (tile.pumpBlock // buildcraft.factory.BlockPump)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: Spawn
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 531 Drop: 38
	Level seed: -8018635123058746059
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (47,88,340), Chunk: (at 15,5,4 in 2,21; contains blocks 32,0,336 to 47,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 176136022 game time, 153572739 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 46881 (now: false), thunder time: 40054 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1481.144
	Operating System: Linux (amd64) version 2.6.32-573.1.1.el6.x86_64
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1292097232 bytes (1232 MB) / 2839019520 bytes (2707 MB) up to 2839019520 bytes (2707 MB)

**Comment by dj3520** [comment]
extracells?

**Comment by kenvix** [comment]
oh,it's a wrong crash report

**Comment by kenvix** [comment]
I have re-edited

**Comment by asiekierka** [comment]
Ouch.

**Comment by asiekierka** [comment]
Fixed in 7.1.7.
