### ISSUE TITLE
Minecraft 1.7.10 Won't Launch

### ISSUE THREAD

**Issue by kriv02** [BuildCraft/BuildCraft#3067]
Time: 10/7/15 6:20 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.api.recipes.IRefineryRecipeManager.addRecipe(Ljava/lang/String;Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraftforge/fluids/FluidStack;II)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.recipes.IRefineryRecipeManager.addRecipe(Ljava/lang/String;Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraftforge/fluids/FluidStack;II)V
	at buildcraft.BuildCraftEnergy.preInit(BuildCraftEnergy.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 326193608 bytes (311 MB) / 674574336 bytes (643 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCH	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCH	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCH	monnef-core{0.7.0} [monnef Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.4.79} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.79-universal.jar) 
	UCH	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCH	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util-1.7.10-1.7.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCH	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCH	BuildCraft|Core{7.0.25} [BuildCraft] (buildcraft-7.0.25.jar) 
	UCE	BuildCraft|Energy{7.0.25} [BC Energy] (buildcraft-7.0.25.jar) 
	UCH	IC2{2.2.781-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.781-experimental.jar) 
	UCH	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.357.jar) 
	UCH	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCH	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCH	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCH	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCH	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCH	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCH	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCH	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCH	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCH	BuildCraft|Transport{7.0.25} [BC Transport] (buildcraft-7.0.25.jar) 
	UCH	BuildCraft|Silicon{7.0.25} [BC Silicon] (buildcraft-7.0.25.jar) 
	UCH	BuildCraft|Factory{7.0.25} [BC Factory] (buildcraft-7.0.25.jar) 
	UCH	additionalpipes{4.6.0} [Additional Pipes] (additionalpipes-4.6.1.jar) 
	UCH	aether{1.7.10-1.5.1} [Aether II] (aether-1.7.10-1.5.1.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCH	AetherAspects{Alpha 1.7.10-1.2} [Aether Aspects] (AetherAspects-1.7.10-1.2.jar) 
	UCH	alchemyplusplus{1.2.0.89} [AlchemyPlusPlus] (AlchemyPlusPlus-1.7.10-1.2.0.89.jar) 
	UCH	AncientWarfare{2.4.113-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareAutomation{2.4.113-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareNEIPlugin{2.4.113-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareNpc{2.4.113-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	AncientWarfareStructure{2.4.113-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCH	aquaticabyss{1.1.1} [Aquatic Abyss] (AquaticAbyss-1.7.10-1.1.1.jar) 
	UCH	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCH	aura{unspecified} [Aura Cascade] (AuraCascade-552.jar) 
	UCH	BuildCraft|Builders{7.0.25} [BC Builders] (buildcraft-7.0.25.jar) 
	UCH	BuildCraft|Robotics{7.0.25} [BC Robotics] (buildcraft-7.0.25.jar) 
	UCH	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UCH	CrossbowMod2{a0.1.6} [Crossbow Mod 2] (Crossbow-Mod-2-1.7-0.2.13.jar) 
	UCH	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCH	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.357.jar) 
	UCH	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCH	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCH	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCH	millenaire{6.0.0} [MillÃ©naire] (millenaire-6.0.0.jar) 
	UCH	monnef-core-helper{0.7.0} [monnef Core ~] (monnef_core_0.7.0.jar) 
	UCH	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCH	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCH	wuppy29_peacefulpack{1.1.8.5} [Peacefulpack] (Peacefulpack 1.7.10-1.1.8.5.jar) 
	UCH	polycraft{1.3.5} [Polycraft] (polycraft-1.3.5.jar) 
	UCH	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.2.jar) 
	UCH	shipwrecks{1.7.0} [Shipwrecks!] (shipwrecks-1.7.10-1.7.1.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCH	XaeroMinimap{1.6.5} [Xaero's Minimap] (xaeros_minimap_v1.6.5_Forge_1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 2000'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291

**Comment by loordgek** [comment]
your bc is a bit old try updating

**Comment by asiekierka** [comment]
It should be fine. It looks more like one of the other mods is outdated.

2015-10-08 16:49 GMT+02:00 loordgek <notifications@github.com>:

**Comment by kriv02** [comment]
Is it a bc addon that is outdated?

**Comment by LuigiHutch** [comment]
Probably additional pipes :)

**Comment by kriv02** [comment]
Thanks.
