### ISSUE TITLE
Unable to load the world since 7.1.11

### ISSUE THREAD

**Issue by FinalPast** [BuildCraft/BuildCraft#3092]
I have this crashlog, All is working in 7.1.9. 
I notice that the problem is not present on new world. There is a strange thing on the crashlog : A entity is under y= -46000.

Sorry for this ugly text, I can't join it.

Thanks for all 

---- Minecraft Crash Report ----
// My bad.

Time: 23/10/15 22:23
Description: Ticking entity

java.lang.IndexOutOfBoundsException: bitIndex < 0: -774741
	at java.util.BitSet.get(BitSet.java:623)
	at buildcraft.core.properties.ChunkProperty.get(ChunkProperty.java:31)
	at buildcraft.core.properties.DimensionProperty.get(DimensionProperty.java:49)
	at buildcraft.core.properties.WorldProperty.get(WorldProperty.java:25)
	at buildcraft.api.core.BuildCraftAPI.isSoftBlock(BuildCraftAPI.java:54)
	at buildcraft.robotics.EntityRobot.func_70030_z(EntityRobot.java:364)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.BitSet.get(BitSet.java:623)
	at buildcraft.core.properties.ChunkProperty.get(ChunkProperty.java:31)
	at buildcraft.core.properties.DimensionProperty.get(DimensionProperty.java:49)
	at buildcraft.core.properties.WorldProperty.get(WorldProperty.java:25)
	at buildcraft.api.core.BuildCraftAPI.isSoftBlock(BuildCraftAPI.java:54)
	at buildcraft.robotics.EntityRobot.func_70030_z(EntityRobot.java:364)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)

-- Entity being ticked --
Details:
	Entity Type: BuildCraft|Robotics.bcRobot (buildcraft.robotics.EntityRobot)
	Entity ID: 149
	Entity Name: Robot
	Entity's Exact location: -1183,50, -48421,03, 4683,50
	Entity's Block location: World: (-1184,-48422,4683), Chunk: (at 0,-3027,11 in -74,292; contains blocks -1184,0,4672 to -1169,255,4687), Region: (-3,9; contains chunks -96,288 to -65,319, blocks -1536,0,4608 to -1025,255,5119)
	Entity's Momentum: 0,00, -0,08, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Moi et Clarisse
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -5660933991790455267
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1170,62,4739), Chunk: (at 14,3,3 in -74,296; contains blocks -1184,0,4736 to -1169,255,4751), Region: (-3,9; contains chunks -96,288 to -65,319, blocks -1536,0,4608 to -1025,255,5119)
	Level time: 4277975 game time, 5353305 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 133866 (now: false), thunder time: 35225 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 320059912 bytes (305 MB) / 597954560 bytes (570 MB) up to 3179282432 bytes (3032 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn400M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 104
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_B8 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.11} [BuildCraft] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.11} [BC Builders] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.11} [BC Transport] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.11} [BC Energy] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.11} [BC Silicon] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.11} [BC Robotics] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.11} [BC Factory] (buildcraft-7.1.11.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	exoticbirds{1.0} [Exotic Birds] (Exotic Birds for 1.7.10 by Pavocado.jar) 
	UCHIJAAAA	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dj3520** [comment]
You're probably going to have to use MCEdit to remove the entity

**Comment by FinalPast** [comment]
@dj3520 Thank you for your answer, But It still works in Buildcraft 7.1.9, When I downgrade to this version I can play without problems. 
I will investigate this idea if I have no solution.
Sorry for my english.

**Comment by AEnterprise** [comment]
the best fix for this would probably be to teleport a robot to it's home station or to max world height and dead so the robot lands on solid ground for it's owner to pick it up

**Comment by FinalPast** [comment]
Good idea but can you explain me how to do this miracle ?
I tried McEDIT, it does not work.

**Comment by AEnterprise** [comment]
@FinalPast that was mainly ment for @asiekierka it's something to be done from the mod code, i don't know if McEdit can do it or not, never tried it.

**Comment by iTitus** [comment]
You could also set the forge config option 'remove erroring entities' temporarily to true

**Comment by FinalPast** [comment]
@iTitus :+1:  You are absolutely right. It's working !
I close this issue, Thank you a lot.

**Comment by iTitus** [comment]
Why can't you turn it off?

**Comment by FinalPast** [comment]
If I do that, It crash again :/
