### ISSUE TITLE
minecraft crash with BC7.1.12

### ISSUE THREAD

**Issue by Antecer** [BuildCraft/BuildCraft#3099]
here is crash report:
http://openeye.openmods.info/crashes/943116f1c6b3c0c6e10121f24462d35a

"
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid

    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
    at forestry.factory.tiles.TileFermenter.drain(TileFermenter.java:419)
    at buildcraft.transport.pipes.PipeFluidsWood.extractFluid(PipeFluidsWood.java:113)
    at buildcraft.transport.pipes.PipeFluidsWood.updateEntity(PipeFluidsWood.java:94)
    at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:388)
    at buildcraft.transport.TileGenericPipeCompat.func_145845_h(TileGenericPipeCompat.java:85)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
"

**Comment by Antecer** [comment]
"
-- Block entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipeCompat
	Block type: ID #227 (tile.pipeBlock // buildcraft.transport.BlockGenericPipeCompat)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (184,65,42), Chunk: (at 8,4,10 in 11,2; contains blocks 176,0,32 to 191,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #227 (tile.pipeBlock // buildcraft.transport.BlockGenericPipeCompat)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
"

**Comment by liach** [comment]
Forestry bug actually. :palm_tree:

**Comment by 3TUSK** [comment]
Why not close it? Ref: ForestryMC/ForestryMC#925

**Comment by Antecer** [comment]
My server is constantly restart...

**Comment by asiekierka** [comment]
Not our bug. We can't fix it.

**Comment by 3TUSK** [comment]
@Antecer You need unstable version. Grab one [here](http://jenkins.ic2.player.to/job/Forestry_Dev/)

**Comment by Antecer** [comment]
@3TUSK  thanks ,I'll try it.
