### ISSUE TITLE
Server going absolutely ballistic with robot spam...

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BuildCraft/BuildCraft#3112]
Woke up this morning, couldnt connect to my server as the player count said ??? instead of a number, so I checked the server and it was streaming hundreds of lines a second, so fast I couldn't even read a line from the console. The log is a couple hundred megabytes since last night.

```
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.DockingStationPipe.getPipe(DockingStationPipe.java:73)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.DockingStationPipe.getRequestProvider(DockingStationPipe.java:201)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.StackRequest.getRequester(StackRequest.java:56)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.ai.AIRobotDeliverRequested.delegateAIEnded(AIRobotDeliverRequested.java:64)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.terminate(AIRobot.java:100)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.ai.AIRobotGotoStation.delegateAIEnded(AIRobotGotoStation.java:74)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.terminate(AIRobot.java:100)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.ai.AIRobotGotoBlock.setNextInPath(AIRobotGotoBlock.java:125)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.ai.AIRobotGotoBlock.loadSelfFromNBT(AIRobotGotoBlock.java:185)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.loadFromNBT(AIRobot.java:181)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.loadFromNBT(AIRobot.java:200)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.loadFromNBT(AIRobot.java:200)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.loadFromNBT(AIRobot.java:200)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.loadFromNBT(AIRobot.java:200)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.api.robots.AIRobot.loadAI(AIRobot.java:223)
[12:20:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.robotics.EntityRobot.func_70037_a(EntityRobot.java:644)
```

I can upload the log files somewhere if it would help. 

Seems to be quite a few log spam errors with robots normally though, server log is otherwise quite clean.

**Comment by asiekierka** [comment]
I'm going to need to see a somewhat longer bit.

Dnia 5 lis 2015 o godz. 02:24 The Quantum General <notifications@github.com> napisał(a):

**Comment by TheQuantumGeneral** [comment]
uploading a log now

**Comment by TheQuantumGeneral** [comment]
https://www.dropbox.com/s/d39mhtd4wleqnig/fml-server-latest.log?dl=0

heres a log

server wont start currently, just crazy amounts of robo spam

**Comment by TheQuantumGeneral** [comment]
Could it possibly be robots not liking my indestructable tinker tools?

**Comment by TheQuantumGeneral** [comment]
I used MC edit to destroy my robots, just the robots not the stations or anything, fixed the issue.
