### ISSUE TITLE
Crash report form BuildCraft7.1.12

### ISSUE THREAD

**Issue by Antecer** [BuildCraft/BuildCraft#3121]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 15-11-8 下午5:33
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:371)
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
	at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
	at net.minecraft.nbt.CompressedStreamTools.func_74798_a(CompressedStreamTools.java:82)
	at buildcraft.core.lib.utils.NBTUtils.save(NBTUtils.java:72)
	at buildcraft.builders.LibraryDatabase.save(LibraryDatabase.java:110)
	at buildcraft.builders.LibraryDatabase.add(LibraryDatabase.java:101)
	at buildcraft.builders.blueprints.RecursiveBlueprintReader.createBlueprint(RecursiveBlueprintReader.java:214)
	at buildcraft.builders.blueprints.RecursiveBlueprintReader.iterate(RecursiveBlueprintReader.java:200)
	at buildcraft.builders.TileArchitect.func_145845_h(TileArchitect.java:83)
	at net.minecraft.world.World.func_72939_s(World.java:2467)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:672)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:939)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:371)
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
	at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
	at net.minecraft.nbt.CompressedStreamTools.func_74798_a(CompressedStreamTools.java:82)
	at buildcraft.core.lib.utils.NBTUtils.save(NBTUtils.java:72)
	at buildcraft.builders.LibraryDatabase.save(LibraryDatabase.java:110)
	at buildcraft.builders.LibraryDatabase.add(LibraryDatabase.java:101)
	at buildcraft.builders.blueprints.RecursiveBlueprintReader.createBlueprint(RecursiveBlueprintReader.java:214)
	at buildcraft.builders.blueprints.RecursiveBlueprintReader.iterate(RecursiveBlueprintReader.java:200)
	at buildcraft.builders.TileArchitect.func_145845_h(TileArchitect.java:83)

-- Block entity being ticked --
Details:
	Name: net.minecraft.src.builders.TileTemplate // buildcraft.builders.TileArchitect
	Block type: ID #235 (tile.architectBlock // buildcraft.builders.BlockArchitect)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (15,81,92), Chunk: (at 15,5,12 in 0,5; contains blocks 0,0,80 to 15,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #235 (tile.architectBlock // buildcraft.builders.BlockArchitect)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2467)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:672)

-- Affected level --
Details:
	Level name: 主界
	All players: 2 total; [EntityPlayerMP['NBTP'/2072, l='主界', x=-62.56, y=63.69, z=111.55](NBTP at -62.55505257779156,63.6875,111.55032101901786), EntityPlayerMP['xiaohei'/771, l='主界', x=15.91, y=81.00, z=93.30](xiaohei at 15.908419375757965,81.0,93.30000001192093)]
	Chunk stats: ServerChunkCache: 636 Drop: 0
	Level seed: 236028205079173237
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (24,64,-24), Chunk: (at 8,4,8 in 1,-2; contains blocks 16,0,-32 to 31,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 146835048 game time, 147063645 day time
	Level dimension: 3
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 71738 (now: false), thunder time: 4879 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:939)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1517.168
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2700925064 bytes (2575 MB) / 4261412864 bytes (4064 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms4G -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1517.168-server.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (KCauldron-1.7.10-1517.168-server.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	OmniOcularCore{1.0} [Omni Ocular Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] ([NEI]NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] ([AE]appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] ([TE]CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.12} [BuildCraft] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.12} [BC Builders] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.12} [BC Transport] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	IC2{2.2.791-experimental} [IndustrialCraft 2] ([IC]industrialcraft-2-2.2.791-experimental.jar) 
	UCHIJAAAA	Forestry{4.1.0.795-unstable} [Forestry for Minecraft] ([F]forestry_1.7.10-4.1.0.795-unstable.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] ([TE]ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] ([TE]ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.2} [BuildCraft Compat] ([BC+]buildcraft-compat-7.1.2.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.12} [BC Energy] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.12} [BC Silicon] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.12} [BC Robotics] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.12} [BC Factory] ([BC]buildcraft-7.1.12.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.67} [Logistics Pipes] ([LP]logisticspipes-0.9.3.67.jar) 
	UCHIJAAAA	NBTEdit{1.7.2.2} [In-game NBTEdit] ([NEI+]NBTEdit_1.7.10.jar) 
	UCHIJAAAA	NEIAddons{1.12.13.38} [NEI Addons] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] ([NEI+]neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.13} [NEI Integration] ([NEI+]NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] ([NEI+]Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	OmniOcular{1.7.10-1.0build60} [Omni Ocular] ([NEI+]OmniOcular-1.7.10-1.0build60.jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.5} [Doomlike Dungeons] ([RPG]DoomlikeDungeons-1.8.5-MC1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] ([TE]ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 32; [EntityPlayerMP['NBTP'/2072, l='主界', x=-62.56, y=63.69, z=111.55](NBTP at -62.55505257779156,63.6875,111.55032101901786), EntityPlayerMP['xiaohei'/771, l='主界', x=15.91, y=81.00, z=93.30](xiaohei at 15.908419375757965,81.0,93.30000001192093)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Nucleria** [comment]
Just a suggestion based on what the crash report says, if you can, try running your mods without Bukkit, KCauldron, or Cauldron. If it still crashes report back here. I might be stupid and there might be no correlation, but try it if you can.

**Comment by AEnterprise** [comment]
outdated BC version and running bukkit/cualdron

can be closed
