### ISSUE TITLE
Robot error appears in console sometimes (java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by Nentify** [BuildCraft/BuildCraft#3161]
```
[19:20:38 WARN]: java.util.ConcurrentModificationException
[19:20:38 WARN]:        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
[19:20:38 WARN]:        at java.util.ArrayList$Itr.next(ArrayList.java:851)
[19:20:38 WARN]:        at net.minecraft.world.World.func_147439_a(World.java:662)
[19:20:38 WARN]:        at buildcraft.core.crops.CropHandlerPlantable.canSustainPlant(CropHandlerPlantable.java:46)
[19:20:38 WARN]:        at buildcraft.api.crops.CropManager.canSustainPlant(CropManager.java:47)
[19:20:38 WARN]:        at buildcraft.robotics.boards.BoardRobotPlanter.isPlantable(BoardRobotPlanter.java:98)
[19:20:38 WARN]:        at buildcraft.robotics.boards.BoardRobotPlanter.access$000(BoardRobotPlanter.java:32)
[19:20:38 WARN]:        at buildcraft.robotics.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:63)
[19:20:38 WARN]:        at buildcraft.core.lib.utils.PathFindingSearch.isTarget(PathFindingSearch.java:88)
[19:20:38 WARN]:        at buildcraft.core.lib.utils.PathFindingSearch.iterateSearch(PathFindingSearch.java:73)
[19:20:38 WARN]:        at buildcraft.core.lib.utils.PathFindingSearch.iterate(PathFindingSearch.java:57)
[19:20:38 WARN]:        at buildcraft.core.lib.utils.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:42)

```

**Comment by Nentify** [comment]
```
[11:14:40 WARN]: java.lang.NullPointerException
[11:14:40 WARN]:        at net.minecraft.world.World.func_147439_a(World.java:664)
[11:14:40 WARN]:        at buildcraft.core.crops.CropHandlerPlantable.canSustainPlant(CropHandlerPlantable.java:46)
[11:14:40 WARN]:        at buildcraft.api.crops.CropManager.canSustainPlant(CropManager.java:47)
[11:14:40 WARN]:        at buildcraft.robotics.boards.BoardRobotPlanter.isPlantable(BoardRobotPlanter.java:98)
[11:14:40 WARN]:        at buildcraft.robotics.boards.BoardRobotPlanter.access$000(BoardRobotPlanter.java:32)
[11:14:40 WARN]:        at buildcraft.robotics.boards.BoardRobotPlanter$2.matches(BoardRobotPlanter.java:63)
[11:14:40 WARN]:        at buildcraft.core.lib.utils.PathFindingSearch.isTarget(PathFindingSearch.java:88)
[11:14:40 WARN]:        at buildcraft.core.lib.utils.PathFindingSearch.iterateSearch(PathFindingSearch.java:73)
[11:14:40 WARN]:        at buildcraft.core.lib.utils.PathFindingSearch.iterate(PathFindingSearch.java:57)
[11:14:40 WARN]:        at buildcraft.core.lib.utils.IterableAlgorithmRunner.run(IterableAlgorithmRunner.java:42)
```
Seeing this too at times

**Comment by AEnterprise** [comment]
old report has never been looked at but i think this is fixed, nobody else has had thsi problem in 6 months and with the MC version changes since i think this would have been spotted during port testing

can be closed

**Comment by AlexIIL** [comment]
Feel free to re-open though if this happens again @Nentify
