### ISSUE TITLE
MineTweaker multiple OreDirectories results in invalid recipe

### ISSUE THREAD

**Issue by Tencao** [BuildCraft/BuildCraft#3197]
I originally posted this on the ModTweaker issue tracker, but was told to post it here as Buildcraft adds support directly. 

So I was trying to make some custom recipes for minetweaker using the assembly table, but when I try to do multiples of, lets say ore:ingotGold, it results in an invalid ingredient, however, doing it with no multiples or doing multiples as the actual item instead of the ore directory name works. To show what I mean below.

This errors
`AssemblyTable.addRecipe(<appliedenergistics2:item.ItemMultiMaterial:25> * 2, 1000, [<ore:ingotGold> * 2, <ore:dustRedstone>, <appliedenergistics2:item.ItemMultiMaterial:23>, <ore:ingotIron> * 3]);`

This works
`AssemblyTable.addRecipe(<appliedenergistics2:item.ItemMultiMaterial:25> * 2, 1000, [<ore:ingotGold>, <ore:dustRedstone>, <appliedenergistics2:item.ItemMultiMaterial:23>, <ore:ingotIron>]);`

This also works
`AssemblyTable.addRecipe(<appliedenergistics2:item.ItemMultiMaterial:25> * 2, 1000, [<minecraft:gold_ingot> * 2, <minecraft:redstone>, <appliedenergistics2:item.ItemMultiMaterial:23>, <minecraft:iron_ingot> * 3]);`

This is the error that gets displayed in the console.

> ERROR: Error executing MineTweakerRecipeMaker: Not a valid assembly table ingredient
java.lang.IllegalArgumentException: Not a valid assembly table ingredient
	at buildcraft.compat.minetweaker.AssemblyTable$AddRecipeAction.<init>(AssemblyTable.java:123)
	at buildcraft.compat.minetweaker.AssemblyTable.addRecipe(AssemblyTable.java:37)
	at scripts.Crafting.__script__(\scripts\Crafting.zs:104)
	at __ZenMain__.run(MineTweakerRecipeMaker)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:566)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:859)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:277)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
	at java.lang.Thread.run(Unknown Source)

>

**Comment by asiekierka** [comment]
It is impossible to do multi-OreDict entries without a ton of custom
handling on both our and MT3's side.
2 lut 2016 13:20 "Tencao" <notifications@github.com> napisał(a):
