### ISSUE TITLE
1.7.10 Buildcraft 7.1.15/7.1.16

### ISSUE THREAD

**Issue by 1skandar** [BuildCraft/BuildCraft#3271]
Not sure if this is on your end, or what, I do know this behavior is new as of the latest few updates of Buildcraft. My log file is basically getting filled up with:

[23:51:59] [NEI Item Filtering/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@44aa32ae:
java.lang.NullPointerException
[23:51:59] [NEI Item Filtering/ERROR]: Index: 6 Listeners:
[23:51:59] [NEI Item Filtering/ERROR]: 0: HIGHEST
[23:51:59] [NEI Item Filtering/ERROR]: 1: ASM: witchinggadgets.client.ClientEventHandler@1332d702 getTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 2: NORMAL
[23:51:59] [NEI Item Filtering/ERROR]: 3: ASM: net.bdew.lib.tooltip.TooltipHandler$@5cab9e4b handleTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 4: ASM: buildcraft.core.list.ListTooltipHandler@671c7ebe itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 5: ASM: thaumcraft.common.lib.events.EventHandlerRunic@98c350d tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 6: ASM: DummyCore.Utils.DummyEventHandler@719e36d5 onDescrAdded(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 7: ASM: mcp.mobius.betterbarrels.bspace.BBEventHandler@79a9c437 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 8: ASM: com.cout970.magneticraft.handlers.TooltipHandler@5aab5f7f onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 9: ASM: minetweaker.mc1710.ForgeEventHandler@7944b930 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 10: ASM: tonius.neiintegration.mods.mcforge.MCForgeTooltipHandler@7395a3b0 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 11: ASM: openblocks.enchantments.flimflams.LoreFlimFlam$DisplayHandler@6709707e onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 12: ASM: pneumaticCraft.client.ClientEventHandler@1b072178 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 13: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@56a7b088 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 14: ASM: buildcraft.builders.BuilderTooltipHandler@43da44eb itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 15: ASM: com.enderio.core.client.handlers.OreDictTooltipHandler@5c4aaead onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 16: ASM: com.enderio.core.client.handlers.EnchantTooltipHandler@7394f673 handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 17: ASM: INSTANCE addTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 18: ASM: ec3.utils.common.PlayerTracker@d0abf86 onDescrAdded(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 19: ASM: com.rwtema.extrautils.EventHandlerClient@611171a7 generatorTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 20: ASM: fox.spiteful.forbidden.FMEventHandler@5efeccc5 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 21: ASM: invtweaks.forge.ClientProxy@19f6fc7d onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 22: ASM: matteroverdrive.handler.TooltipHandler@74ffcf0e onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 23: ASM: net.blay09.mods.tcinventoryscan.client.ClientProxy@7f4bc736 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[23:51:59] [NEI Item Filtering/ERROR]: 24: LOWEST
[23:51:59] [NEI Item Filtering/ERROR]: 25: ASM: travellersgear.client.ClientProxy@3aabd77a onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V

Again, this behavior is brand new over the past three days or so and the only mod listed in the log that has been updated during that time would be Buildcraft.

**Comment by AlexIIL** [comment]
I'd just like to point out that this isn't the actual exception that's being thrown (which would tell us what is going on) but a list of what "event handlers" are being added to listen to an event the is causing the spam. The actual exception should be either below or above that in the log (or if you can't find it you could post the entire log file onto gist)

**Comment by 1skandar** [comment]
[05:43:50] [NEI Item Loading/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@7c9d79d1:
java.lang.NullPointerException
	at java.util.Hashtable.containsKey(Unknown Source) ~[?:1.8.0_73]
	at DummyCore.Utils.DummyEventHandler.onDescrAdded(DummyEventHandler.java:188) ~[DummyEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_321_DummyEventHandler_onDescrAdded_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:162) [ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626) [add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162) [GuiContainerManager.class:?]
	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:166) [ItemList$1.class:?]
	at codechicken.nei.ItemList$1.execute(ItemList.java:206) [ItemList$1.class:?]
	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]

That is the missing bit. sorry, but that extra bit is on;y present the first few dozen times it throws that error into the log. The next few thousand times are just what I posted above, again and again.

I've3 dug back into my logs, and this was not present until I added Buildcraft. I'm not sure it is Buildcraft's fault, but it is decidedly at least an incompatibility.

**Comment by AEnterprise** [comment]
`at DummyCore.Utils.DummyEventHandler.onDescrAdded(DummyEventHandler.java:188)`

it's in error in the dumycore mod, BC isn't mentioned anywhere in the stacktrace. there is probably a null check missing on there side

**Comment by 1skandar** [comment]
Potentially, aye, but it is definitely cross mod as this error was not present until I added Builcraft.

**Comment by AlexIIL** [comment]
@AEnterprise keep in mind that it could be BC returning null on an item description where it shouldn’t- the best thing would be to ask DummyCore people what they think is going on. I'm not sure what the error actually is however- I can't seem to find the real source code for DummyEventHandler (line 188 isn't the same method as what’s in the error).

@1skandar I would appreciate it if you could report it to DummyCore and see what they think of it though :)

**Comment by AEnterprise** [comment]
@AlexIIL i know, but then they'll probably let us know

**Comment by 1skandar** [comment]
Done. 

Oh, and there has been work on that mod that has not made it to a public release. This should be the version in the last stable 1.7.10 release:
https://github.com/Modbder/DummyCore/blob/eddeec77b5db42b14c7d551366a8e3bc740b8709/DummyCore/Utils/DummyEventHandler.java

**Comment by AlexIIL** [comment]
@1skandar Thanks for finding that! It also means that its defiantly a BC issue, we should not be retuning null for that method.

**Comment by 1skandar** [comment]
Java isn't my language, but I'm a scratch programmer in a few others. Plus two years as a pack dev. Narrowing down the root cause of a bug has become reflexive at this point.

**Comment by asiekierka** [comment]
What items are you hovering on when this pops up? It appears it's the ItemStack which is null, and the only BC code being executed here has last been changed in September...

**Comment by 1skandar** [comment]
Nothing, it happens on opening of my inventory, regardless of what is in my inventory at the time.

**Comment by asiekierka** [comment]
I think the issue here is that DummyCore doesn't expect anyone to hover over an empty item stack.

**Comment by 1skandar** [comment]
It still odesn't cvhange the fact that this did not crop up until I added Buildcraft. Something is out of whack here, and if it isn't on your end, it is still at least an unexpected interaction
