### ISSUE TITLE
[1.8.9] Some problem about the picker robots

### ISSUE THREAD

**Issue by zhijun1997** [BuildCraft/BuildCraft#3282]
i found some new problem about the "Picker Robots"

Using mod version : 
buildcraft-7.2.4.jar
buildcraft-7.2.5-test1.jar
buildcraft-compat-7.2.1.jar

about the problem:
you can [download](https://www.dropbox.com/s/crndauwaa5zxzwz/BC%20robots.mp4?dl=0) my demo to know what it happen

**Comment by zhijun1997** [comment]
### i Found some error in console :
`[20:40:36] [Server thread/INFO] [BuildCraft]: Shutting down robot EntityRobot['Robot'/6251, l='world', x=546.50, y=67.00, z=401.50] - wrong docking station
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: java.lang.NullPointerException
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at buildcraft.robotics.ai.AIRobotGotoBlock.update(AIRobotGotoBlock.java:85)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at buildcraft.api.robots.AIRobot.cycle(AIRobot.java:123)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at buildcraft.api.robots.AIRobot.cycle(AIRobot.java:120)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at buildcraft.api.robots.AIRobot.cycle(AIRobot.java:120)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at buildcraft.api.robots.AIRobot.cycle(AIRobot.java:120)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at buildcraft.robotics.EntityRobot.func_70030_z(EntityRobot.java:344)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:279)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1564)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:228)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.world.World.redirect$onCallEntityUpdate$0(World.java:286)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.world.World.func_72866_a(World.java:1862)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.world.World.func_72870_g(World.java:1831)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.world.World.func_72939_s(World.java:1663)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
[20:40:36] [Server thread/INFO] [STDERR]: [buildcraft.api.robots.AIRobot:cycle:126]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by zhijun1997** [comment]
update 2 warning : 

> [23:17:56] [Server thread/WARN] [BuildCraft]: Robot with id %d was not unregistered properly
[23:17:56] [Server thread/WARN] [BuildCraft]: A robot entity was not properly unloaded

and ... i missing my 2 robots by none reason！

**Comment by AEnterprise** [comment]
seems to be missed and nver looked at

**Comment by AEnterprise** [comment]
the robot not getting to the items might be because the special fences you have, the robot might think he can fly through them, no idea why it's dropping them in the wrong docking station
