### ISSUE TITLE
Robot disapeard after destroying docking station

### ISSUE THREAD

**Issue by 0blu** [BuildCraft/BuildCraft#3397]
Buildcraft: 7.1.16
FTB Infinity Evolved 2.5.0

If this bug is already fixed: can someone help me to delete this robot?

---

Hey,

i destroyed a docking station (in vanilla, diamond pickaxe) while a robot was attached to it.

The Problem now is, that the robot disappeared after i destroyed the docking station and it occupies new docking stations.
I also don't know how to remove the buggy robot, it seems it had a ID Robot/1806467

```
[20:38:38] [Server thread/INFO] [BuildCraft]: Shutting down robot EntityRobot['Robot'/1806467, l='world', x=36.50, y=68.00, z=-149.50] - no docking station
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at buildcraft.robotics.DockingStationPipe.takeAsMain(DockingStationPipe.java:231)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at buildcraft.robotics.ai.AIRobotGoAndLinkToDock.start(AIRobotGoAndLinkToDock.java:39)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at buildcraft.api.robots.AIRobot.startDelegateAI(AIRobot.java:144)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at buildcraft.robotics.ai.AIRobotMain.preempt(AIRobotMain.java:46)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at buildcraft.api.robots.AIRobot.cycle(AIRobot.java:126)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at buildcraft.robotics.EntityRobot.func_70030_z(EntityRobot.java:369)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.World.func_72866_a(World.java:2070)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.World.func_72870_g(World.java:2034)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.World.func_72939_s(World.java:1887)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at fastcraft.at.a(F:978)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at fastcraft.H.aq(F:36)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[20:38:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by AEnterprise** [comment]
what do you mean with "occupies new docking stations"? is the robot still in the world? if so you should be able to pick it up with shift-right click with a wrench (normaly any wrench will work, if not try a BC wrench as that surely works)

**Comment by 0blu** [comment]
There is no Robot anymore,
it felt through the world, straight down under the badrock, it was attackable but i didn't manage to kill it.

If i place a station right at the spot where the station i destroyed was the light will appear yellow, so it's occupied.

It also seems that dis bug only appears with picker robots.

**Comment by AEnterprise** [comment]
related to #3408 for the robots falling throught the world

that new docking stations are being occupied by non existant robots is something else though

**Comment by AEnterprise** [comment]
most likely just a side effect of the robot ai that was failing to land and they fall out of the world
