### ISSUE TITLE
CRASH BC teleport pipes to condenser IC2

### ISSUE THREAD

**Issue by rlemish** [BuildCraft/BuildCraft#3420]
---- Minecraft Crash Report ----

Time: 8/26/16 7:14 PM
Description: Ticking block entity

java.lang.IllegalStateException: The fluid handler buildcraft.transport.TileGenericPipeCompat@97a58 filled inconsistently. Expected 50, got 0.
	at ic2.core.util.LiquidUtil.transfer(LiquidUtil.java:194)
	at ic2.core.util.LiquidUtil.distributeAll(LiquidUtil.java:158)
	at ic2.core.item.ItemUpgradeModule.onTick(ItemUpgradeModule.java:407)
	at ic2.core.block.machine.tileentity.TileEntityCondenser.updateEntityServer(TileEntityCondenser.java:141)
	at ic2.core.block.TileEntityBlock.func_145845_h(TileEntityBlock.java:195)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.util.LiquidUtil.transfer(LiquidUtil.java:194)
	at ic2.core.util.LiquidUtil.distributeAll(LiquidUtil.java:158)
	at ic2.core.item.ItemUpgradeModule.onTick(ItemUpgradeModule.java:407)
	at ic2.core.block.machine.tileentity.TileEntityCondenser.updateEntityServer(TileEntityCondenser.java:141)
	at ic2.core.block.TileEntityBlock.func_145845_h(TileEntityBlock.java:195)

-- Block entity being ticked --
Details:
	Name: Condenser // ic2.core.block.machine.tileentity.TileEntityCondenser
	Block type: ID #233 (blockMachine2 // ic2.core.block.machine.BlockMachine2)
	Block data value: 15 / 0xF / 0b1111
	Block location: World: (-1542,83,4571), Chunk: (at 10,5,11 in -97,285; contains blocks -1552,0,4560 to -1537,255,4575), Region: (-4,8; contains chunks -128,256 to -97,287, blocks -2048,0,4096 to -1537,255,4607)
	Actual block type: ID #233 (blockMachine2 // ic2.core.block.machine.BlockMachine2)
	Actual block data value: 15 / 0xF / 0b1111
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['HydroONE'/306, l='world', x=-1571.73, y=81.52, z=4568.24](HydroONE at -1571.729807140552,81.51966814529723,4568.244352479186)]
	Chunk stats: ServerChunkCache: 568 Drop: 0
	Level seed: -6237878241837186956
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (227,93,181), Chunk: (at 3,5,5 in 14,11; contains blocks 224,0,176 to 239,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 514316134 game time, 532434521 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3844 (now: false), thunder time: 50121 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
	Plugins: WorldEdit, Playtime, OpenInv, Block_Finder, Essentials, ClearLag, WorldBorder, BkrReload, EndlessOnline, LokiBlocker, BanManager, WorldGuard, MultiWorld, CustomServerMessages, ChunkLoader, EssentialsChat, PermissionsEx, SQLibrary, WGExtender, Vault, EssentialsSpawn, Prism, Scavenger, ShoppingCartReloaded, WGAllower, ProtocolLib, PermissionsExTabColors, ModFixNG, JSONAPI, HolographicDisplays
	Disabled Plugins: 
	Operating System: Linux (amd64) version 4.2.0-42-generic
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1023252160 bytes (975 MB) / 2075918336 bytes (1979 MB) up to 34150416384 bytes (32568 MB)
	JVM Flags: 6 total; -Xmx32G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=24 -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.17} [BuildCraft] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.17} [BC Silicon] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.17} [BC Transport] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.17} [BC Builders] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.17} [BC Energy] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.17} [BC Factory] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.6} [Additional Buildcraft Objects] (AdditionalObject4.0.6.jar) 
	UCHIJAAAA	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.2.jar) 
	UCHIJAAAA	IC2{2.2.822-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.822-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.17} [BC Robotics] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	Forestry{4.0.9.38} [Forestry for Minecraft] (forestry_1.7.10-4.0.9.38.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft-1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	colorblocks{1.4} [Color Blocks] (colorblocks-1.7.2-1.4.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	EventHelper{1.6} [EventHelper] (EventHelper-1.6.jar) 
	UCHIJAAAA	fc-dummy{0} [fc-dummy] (fastcraft-1.23.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJAAAA	IC2NuclearControl{2.3.4a} [Nuclear Control 2] (IC2NuclearControl-2.3.4a.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.0} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.0.jar) 
	UCHIJAAAA	qucra{1.7.10-1.6} [Quick Crafting] (QuickCrafting-1.7.10-1.6.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: mail
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 80; [EntityPlayerMP['HydroONE'/306, l='world', x=-1571.73, y=81.52, z=4568.24](HydroONE at -1571.729807140552,81.51966814529723,4568.244352479186)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by rlemish** [comment]
not BC
