### ISSUE TITLE
Buildcraft 7.1.18 Server Loop

### ISSUE THREAD

**Issue by Dream-Master** [BuildCraft/BuildCraft#3435]
I get this Loop on my Server

Buildcraft 7.1.18
Thermos Build 56
````````````````````
	at buildcraft.core.lib.block.BlockBuildCraftFluid.func_149695_a(BlockBuildCraftFluid.java:72) [BlockBuildCraftFluid.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:1144) [ahb.class:?]
	at net.minecraft.world.World.func_147459_d(World.java:1080) [ahb.class:?]
	at net.minecraft.world.World.func_147444_c(World.java:1045) [ahb.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:901) [ahb.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:879) [ahb.class:?]
	at net.minecraft.world.World.func_147468_f(World.java:999) [ahb.class:?]
	at net.minecraft.block.Block.onBlockExploded(Block.java:1759) [aji.class:?]
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:280) [agw.class:?]
	at net.minecraft.world.World.func_72885_a(World.java:3076) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1194) [mt.class:?]
``````````````
My Forge Log is 200 mb large now and raising.

Buildcraft 7.1.17 never have this problem

My Modpack:
https://github.com/GTNewHorizons/NewHorizons

**Comment by AEnterprise** [comment]
i'm gussing this is just log spam and not a crash? please also provide the full stacktrace or log, this stacktrace in incomplete, missing the first line(s)

**Comment by Dream-Master** [comment]
I cant log in during this phase.
So you want the wole file? I upload it to my Dropbox just a min.

**Comment by Dream-Master** [comment]
or you need this only:

``````````````````````````````
[17:15:36] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Jobs v3.3.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.56]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.56]
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:226) [agw.class:?]
	at net.minecraft.world.World.func_72885_a(World.java:3076) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1194) [mt.class:?]
	at buildcraft.core.lib.block.BlockBuildCraftFluid.func_149695_a(BlockBuildCraftFluid.java:72) [BlockBuildCraftFluid.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:1144) [ahb.class:?]
	at net.minecraft.world.World.func_147459_d(World.java:1083) [ahb.class:?]
	at net.minecraft.world.World.func_147444_c(World.java:1045) [ahb.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:901) [ahb.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:879) [ahb.class:?]
	at net.minecraft.world.World.func_147468_f(World.java:999) [ahb.class:?]
	at net.minecraft.block.Block.onBlockExploded(Block.java:1759) [aji.class:?]
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:280) [agw.class:?]
	at net.minecraft.world.World.func_72885_a(World.java:3076) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1194) [mt.class:?]
	at buildcraft.core.lib.block.BlockBuildCraftFluid.func_149695_a(BlockBuildCraftFluid.java:72) [BlockBuildCraftFluid.class:?]
``````````````````````````

**Comment by AEnterprise** [comment]
that full stack trace is indeed exactly what we need, it shows that his is a bug in bukkit, not BC

it looks like there is oil in the nether and that is trying to explode but bukkit is erroring on that for some reason, please report this to the thermos devs as there is nothing we can do about it

hint for next time: always provide the full stacktrace

**Comment by Dream-Master** [comment]
ok thanks.

**Comment by Dream-Master** [comment]
@AEnterprise 
Is anything changed in version 7.1.18 which changing the oil behavior?

**Comment by AEnterprise** [comment]
no that code has not been touched in a long while, i suspect you also updated thermos or didn't place oil in the nether before

**Comment by Dream-Master** [comment]
@AEnterprise 
We still updating Thermos and with Version 7.1.18 it placed Oil in the Nether. After all Oil explode in a chunck some big holes are in the lave. Are the nether not blacklisted for oil ?

**Comment by AEnterprise** [comment]
BC doesn't generate oil in the nether but you are running modifications like thermos and it is possible that is messing with something (or another mod)
