### ISSUE TITLE
pump crash

### ISSUE THREAD

**Issue by androx102** [BuildCraft/BuildCraft#3438]
Hi, i have a problem with pumps, when i place a pipe on pump i get kick from the server, but only on this chunk where i placed pump. i use bc 6.3.1 (i must because i use old forge because my host do not offer new)  
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 06.10.16 18:08
Description: Ticking entity

java.lang.NoSuchFieldError: tank
	at com.indemnity83.irontank.tile.TileIronTank.<init>(TileIronTank.java:25)
	at com.indemnity83.irontank.block.BlockIronTank.func_149915_a(BlockIronTank.java:46)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at com.ternsip.stabilizermod.Chargeable.<init>(Chargeable.java:37)
	at com.ternsip.stabilizermod.Container.<init>(Container.java:23)
	at com.ternsip.stabilizermod.Registrant.register(Registrant.java:69)
	at com.ternsip.stabilizermod.Stabilizermod.watchChunk(Stabilizermod.java:42)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_432_Stabilizermod_watchChunk_Watch.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:285)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.indemnity83.irontank.tile.TileIronTank.<init>(TileIronTank.java:25)
	at com.indemnity83.irontank.block.BlockIronTank.func_149915_a(BlockIronTank.java:46)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at com.ternsip.stabilizermod.Chargeable.<init>(Chargeable.java:37)
	at com.ternsip.stabilizermod.Container.<init>(Container.java:23)
	at com.ternsip.stabilizermod.Registrant.register(Registrant.java:69)
	at com.ternsip.stabilizermod.Stabilizermod.watchChunk(Stabilizermod.java:42)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_432_Stabilizermod_watchChunk_Watch.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:285)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)

-- Entity being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 4496
	Entity Name: Camper102
	Entity's Exact location: -122,15, 75,00, 257,16
	Entity's Block location: World: (-123,75,257), Chunk: (at 5,4,1 in -8,16; contains blocks -128,0,256 to -113,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0,00, -0,08, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['Camper102'/4496, l='New World', x=-122,15, y=75,00, z=257,16]]
	Chunk stats: ServerChunkCache: 961 Drop: 0
	Level seed: 3159363341117157607
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-116,64,256), Chunk: (at 12,4,0 in -8,16; contains blocks -128,0,256 to -113,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6941 game time, 6941 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 71870 (now: false), thunder time: 130867 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 277532280 bytes (264 MB) / 838418432 bytes (799 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 38, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_D1 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{IvToolkit} [1.1] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.79} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.79-universal.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x (3).jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	bookshelf{1.2.0} [Bookshelf] (Bookshelf-1.7.10-1.2.0.jar) 
	UCHIJAAAA	BuildCraft|Core{6.4.5} [BuildCraft] (buildcraft-6.4.5.jar) 
	UCHIJAAAA	BuildCraft|Transport{6.4.5} [BC Transport] (buildcraft-6.4.5.jar) 
	UCHIJAAAA	BuildCraft|Silicon{6.4.5} [BC Silicon] (buildcraft-6.4.5.jar) 
	UCHIJAAAA	BuildCraft|Builders{6.4.5} [BC Builders] (buildcraft-6.4.5.jar) 
	UCHIJAAAA	BuildCraft|Energy{6.4.5} [BC Energy] (buildcraft-6.4.5.jar) 
	UCHIJAAAA	BuildCraft|Factory{6.4.5} [BC Factory] (buildcraft-6.4.5.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAA	D3Core{1.1.1.38} [D3Core] (D3Core-1.7.10-1.1.1.38.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.1.0.18_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.18_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	IC2{2.2.821-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.821-experimental.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	UCHIJAAAA	Ic2Nei{1.0} [IC2 Nei Plugin] (IC2 Nei Plugin Version 1.1.0.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	IronTank{beta} [Iron Tank] (irontank-1.7.10-1.0.0.33-beta.jar) 
	UCHIJAAAA	Jewelrycraft{1.4.2} [Jewelrycraft] (Jewelrycraft 1.4.2 for Mc 1.7.2 (2).jar) 
	UCHIJAAAA	Lumberjack{1.1.0.21} [Lumberjack] (Lumberjack-1.7.10-1.1.0.21.jar) 
	UCHIJAAAA	Mantle{1.7.10-165.4bc3343} [Mantle] (Mantle_mc1.7.10_0.3.0.jar) 
	UCHIJAAAA	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHIJAAAA	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	NuclearCraft{1.9d} [NuclearCraft] (NuclearCraft-1.9d--1.7.10.jar) 
	UCHIJAAAA	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) 
	UCHIJAAAA	stabilizermod{3.3} [stabilizermod] (Stabilizer-3.3-1.7.10.jar) 
	UCHIJAAAA	tchelper{1.7.10-1.4} [TC Research-Helper] (tchelper-1.7.10-1.4.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct] (TConstruct-1.7.10-1.8.1.jar) 
	UCHIJAAAA	telepads{1.6.4 v5} [Teleportation Pads] (TelePads-Mod-1.7.10.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	um_tmodifiers{1.2.1} [Tinkers' Modifiers] (Tinkers' Modifiers v1.2.1.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['Camper102'/4496, l='New World', x=-122,15, y=75,00, z=257,16]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_D1
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13447 Compatibility Profile Context 16.300.2311.0
	OpenGlRenderer: AMD Radeon (TM) R7 360 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by dj3520** [comment]
Appears to be an irontank causing the crash, not the pump: `java.lang.NoSuchFieldError: tank
at com.indemnity83.irontank.tile.TileIronTank.(TileIronTank.java:25)`

Also you're using the newest 1.7.10 version of forge: `Minecraft Forge 10.13.4.1614`

**Comment by AEnterprise** [comment]
this indeed has nothing to do with BC but irontanks is crashing, please report this to them.

also please use gist or pastebin for crashlogs next time
