### ISSUE TITLE
Engine failure

### ISSUE THREAD

**Issue by EmerlandStar82** [BuildCraft/BuildCraft#3453]
The Minecraft is closed to me when putting a motor any closes to me
This is what I get
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 18-11-16 16:51
Description: Unexpected error

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyHandler.canConnectEnergy(Lnet/minecraftforge/common/util/ForgeDirection;)Z
	at buildcraft.energy.TileEngine.isPoweredTile(TileEngine.java:513)
	at buildcraft.energy.TileEngine.switchOrientationDo(TileEngine.java:375)
	at buildcraft.energy.TileEngine.switchOrientation(TileEngine.java:362)
	at buildcraft.energy.BlockEngine.func_149714_e(BlockEngine.java:220)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:214)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.energy.TileEngine.isPoweredTile(TileEngine.java:513)
	at buildcraft.energy.TileEngine.switchOrientationDo(TileEngine.java:375)
	at buildcraft.energy.TileEngine.switchOrientation(TileEngine.java:362)
	at buildcraft.energy.BlockEngine.func_149714_e(BlockEngine.java:220)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:214)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['EmerlandStar82'/147, l='MpServer', x=-5,43, y=66,29, z=7,92]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25693 game time, 25693 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityItem['item.item.redstone'/17966, l='MpServer', x=-15,88, y=64,13, z=1,22], EntityClientPlayerMP['EmerlandStar82'/147, l='MpServer', x=-5,43, y=66,29, z=7,92], EntityItem['item.item.string'/17722, l='MpServer', x=-6,53, y=64,13, z=26,34], EntityItem['item.item.redstone'/15588, l='MpServer', x=-14,13, y=64,25, z=21,56], EntityItem['item.item.diode'/17009, l='MpServer', x=-14,25, y=64,25, z=20,38]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 324720376 bytes (309 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	BuildCraft|Core{6.1.5} [BuildCraft] (_BuildCraft-Mod-Stable-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Builders{6.1.5} [BC Builders] (_BuildCraft-Mod-Stable-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Transport{6.1.5} [BC Transport] (_BuildCraft-Mod-Stable-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Silicon{6.1.5} [BC Silicon] (_BuildCraft-Mod-Stable-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Factory{6.1.5} [BC Factory] (_BuildCraft-Mod-Stable-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Energy{6.1.5} [BC Energy] (_BuildCraft-Mod-Stable-1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by AlexIIL** [comment]
You are using a *very* old version of BuildCraft - try 7.1.18 [here](http://mod-buildcraft.com/pages/download.html) Note that upgrading a 6.1.5 world to 7.1.18 may change some of the builds in your world so backup first!
