### ISSUE TITLE
Buildcraft - Enhanced Portals 3 (not compatible)

### ISSUE THREAD

**Issue by LegendeJ3asti** [BuildCraft/BuildCraft#3456]
Can someone make a fix that i can use both mods?
If i place 1 Item from Enhanced Portals 3 mod the game crashes.
The Item is called Dimansional Bridge Stabilizer.
The Minecraft Version is 1.7.10

Here is my crash-report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 11/21/16 6:47 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145)
	at enhancedportals.tileentity.TileStabilizer.<init>(TileStabilizer.java:40)
	at enhancedportals.block.BlockStabilizer.func_149915_a(BlockStabilizer.java:56)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by asiekierka** [comment]
One of your mods is providing an outdated version of the BuildCraft API - you can tell by its JAR file containing a buildcraft/api/mj directory.

Either get rid of its outdated copy of the BuildCraft API by editing the JAR - note that redistributing such a modified JAR might have licensing problems - or, preferably, report to the mod author bundling this outdated version of the API.
