### ISSUE TITLE
8.0.0 Server Crashing

### ISSUE THREAD

**Issue by forReason** [BuildCraft/BuildCraft#3476]
My Multiplayer Server is crashing here my logs (stays the same no matter which modules I load so in this case I just loaded 8.0.0-alpha-core.jar for testing purposes)

```
[16:32:31] [Server thread/DEBUG] [FML/]: Bar Finished: ServerStarted took 0.006s
[16:32:32] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@49b7c2a4:
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureAtlasSprite
	at buildcraft.lib.BCLibEventDist.serverTick(BCLibEventDist.java:99) ~[BCLibEventDist.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_BCLibEventDist_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:262) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureAtlasSprite
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 8 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@70ab2d48 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[forge.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 8 more
Caused by: java.lang.RuntimeException: Attempted to load class byz for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56) ~[forge.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) ~[forge.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 8 more
[16:32:32] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[16:32:32] [Server thread/ERROR] [FML/]: 0: NORMAL
[16:32:32] [Server thread/ERROR] [FML/]: 1: ASM: INSTANCE serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:32:32] [Server thread/ERROR] [FML/]: 2: ASM: com.minecolonies.coremod.event.FMLEventHandler@2d997d82 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:32:32] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[16:32:32] [Server thread/INFO] [FML/]: Unloading dimension 0
```

**Comment by AlexIIL** [comment]
I should really test the server first :/

**Comment by forReason** [comment]
works (at least running)  :)

Will try basic functionality 

thx for the ultra fast fix

**Comment by forReason** [comment]
Okay. Seems to work.

**Comment by AlexIIL** [comment]
There are a bunch of other issues (like if you place down a tank it will crash, and probably the same for all blocks that store fluids except for pipes)

**Comment by AEnterprise** [comment]
i got an idea on how to automate server testing, need some digging in gradle commands and minecraft stuff for that first though
