### ISSUE TITLE
[8.0.x] Disabling tanks causes a crash

### ISSUE THREAD

**Issue by unascribed** [BuildCraft/BuildCraft#3512]
```
java.lang.RuntimeException: Invalid shaped ore recipe: iri, igi, tbt, r, dustRedstone, i, ingotIron, g, gearIron, b, net.minecraft.item.ItemBucket@e154848, t, null, 1xtile.pumpBlock@0
	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:139) ~[ShapedOreRecipe.class:?]
	at buildcraft.lib.recipe.RecipeBuilderShaped.build(RecipeBuilderShaped.java:91) ~[RecipeBuilderShaped.class:?]
	at buildcraft.lib.recipe.RecipeBuilderShaped.build(RecipeBuilderShaped.java:84) ~[RecipeBuilderShaped.class:?]
	at buildcraft.factory.BCFactoryRecipes.init(BCFactoryRecipes.java:61) ~[BCFactoryRecipes.class:?]
	at buildcraft.factory.BCFactory.init(BCFactory.java:50) ~[BCFactory.class:?]
```
Fairly self-explanatory, I think.

Full crash log: https://gist.github.com/unascribed/b08d9fbfeb56acae4832438067bc2b59

**Comment by afdw** [comment]
Please try this commit from my branch: https://github.com/afdw/BuildCraft/commit/43b3d7fb23d411361341ab5fcf9bb40a5d7760d2

**Comment by unascribed** [comment]
Broken in a slightly different way:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BC Factory (buildcraftfactory)
Caused by: java.lang.RuntimeException: Invalid shaped ore recipe: igi, btb, ibi, i, ingotIron, g, gearIron, b, Block{minecraft:iron_bars}, t, null, 1xtile.floodGateBlock@0
	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:139)
	at buildcraft.lib.recipe.RecipeBuilderShaped.build(RecipeBuilderShaped.java:91)
	at buildcraft.lib.recipe.RecipeBuilderShaped.build(RecipeBuilderShaped.java:84)
	at buildcraft.factory.BCFactoryRecipes.init(BCFactoryRecipes.java:74)
	at buildcraft.factory.BCFactory.init(BCFactory.java:50)
```

Looks like there's already a recipe abstraction, couldn't you fix this at that level?

**Comment by afdw** [comment]
OK: https://github.com/afdw/BuildCraft/commit/269f9a104653a37a32fc4bf644bda1781454ff7d
