### ISSUE TITLE
REALLY SIMPLE - Just a problem with launching buildcraft

### ISSUE THREAD

**Issue by Trickster29** [BuildCraft/BuildCraft#3531]
i am making my own custom launcher, your mod works perfectly under the regular minecraft launcher. and i have tried literally everything. from reading your code to matching every library 1 by 1 to make sure my custom launcher was launching minecraft the exact same way. 

i even went as far as to read the GuideManager.java and make sure for each of your import statements that there was a matching loaded library. as far as i could tell there was.

this is the error i get when its launched using my launcher 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.NullPointerException
        at buildcraft.lib.client.guide.GuideManager.reloadLang(GuideManager.java:50)
        at buildcraft.lib.client.guide.GuideManager.load(GuideManager.java:44)
        at buildcraft.lib.BCLibProxy$ClientProxy.fmlPostInit(BCLibProxy.java:134)
        at buildcraft.lib.BCLib.postInit(BCLib.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
        at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:356)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

i read your code, on line 50 it looks like its calling some language from the Minecraft client. the main jar file for minecraft is inside of my set of libraries. meaning the method its calling should be available.  why is it saying that the command is nothing (What i believe nullpointer to be) is there something im missing. cause i cannot find it for the life of me. 

my launcher is coded in vb.net. and is a private launcher/modpack buildcraft is the only mod its having issues launching with. please enlighten me on what may be missing. ive matched all the libraries that the normal launcher launches.

this would be super easy for you to tell me whats wrong i would imagine.

**Comment by AEnterprise** [comment]
from the crash it looks your launcher is not exactly launching like the regular one

i'm not sure if we want to offer support here for custom launchers as iirc mojang does not allow those, you could make a wrapper launcher that starts the regular minecraft launcher, gives it the right params and the user only has to click play (or log in)

**Comment by AlexIIL** [comment]
The nullpointer exception means that one of the functions called in 
````java
 String lang = Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage().getLanguageCode(); 
````
is returning a null value. This is not an issue with libraries (as that would throw a exception with "class not found" or something similar.

I have no idea what would cause this, but can you test minecraft by itself and check that all of the languages are loaded? Its the only thing I can think of...

**Comment by asiekierka** [comment]
We're not going to provide support for custom launchers. We may be able to help if full and complete source code is provided to us, but it is unlikely that this issue will get priority. If you want a customized private modpack launcher, just take SKLauncher or MCUpdater and adapt it to your needs.

**Comment by asiekierka** [comment]
@AlexIIL I would like to point out that asking for the *current* language in postInit might not end well... it can change.

**Comment by Trickster29** [comment]
I hope you do change that soon. I just went ahead and reverted to 1.10.2 (because buildcraft is ahead of alot of the add-ons for IC2 and Opencomputers) . And my launcher does work with every other mod we added. Perhaps it's just that your asking for it on post initialization. I have copied the command line exactly from the regular launcher. So I'm not sure what else I can match. I thought maybe there was a specific library that you could tell me to include. Since you do the same thing in eclipse.

**Comment by AlexIIL** [comment]
@asiekierka yes, its not ideal atm - although I will add reloading later on when resources change or the language used changes.

@Trickster29 I don't know how I can really help with this - the only thing I can assume is that you don't setup the resources properly and so it doesn't load any languages. Although I can add a check in case it is null, and default to en_us.

**Comment by Trickster29** [comment]
@ALEXILL My launcher has the normal languages button at the main menu. And all languages are available for picking. But if I pick a language. It does in fact not change anything. Do you have an idea on where the language resources are stored. So that I may figure out how to add then? 

Maybe that's why the other mods load. Cause they assume english when there's nothing???

**Comment by Trickster29** [comment]
I stand corrected. It does in fact change stuff with the languages....
