### ISSUE TITLE
[8.x] Crash on multiplayer server postinitialization

### ISSUE THREAD

**Issue by kernegal** [BuildCraft/BuildCraft#3532]
The server crashes at startup. Compiled using the last [commit](https://github.com/BuildCraft/BuildCraft/commit/86470a5f718aa24dc3f8a9e88de4dae20b033965) (At this moment). Also, I'm using Forge version 13.20.0.2282 but tested in 13.20.0.2284 with same results. 
The crash log is: 
```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BC Transport (buildcrafttransport)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/storage/SaveHandlerMP
	at buildcraft.builders.snapshot.FakeWorld.<init>(FakeWorld.java:35)
	at buildcraft.builders.snapshot.FakeWorld.<clinit>(FakeWorld.java:28)
	at buildcraft.transport.plug.FacadeStateManager.getRequiredStack(FacadeStateManager.java:65)
	at buildcraft.transport.plug.FacadeStateManager.postInit(FacadeStateManager.java:94)
	at buildcraft.transport.BCTransport.init(BCTransport.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.storage.SaveHandlerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
```

**Comment by afdw** [comment]
Please retry with https://github.com/BuildCraft/BuildCraft/commit/12ba161068fe45d05d64318c6ac200a994021d0c.

**Comment by AEnterprise** [comment]
@afdw asigning to you as you seem to be looking into it, if not feel free to remove tha assignment, gona try doing this more often so we can see from the issue list what is being worked on or atleast who looked at it

**Comment by kernegal** [comment]
That solved it.
