### ISSUE TITLE
Fresh build client crash

### ISSUE THREAD

**Issue by XakepSDK** [BuildCraft/BuildCraft#3562]
```
Time: 5/10/17 12:35 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1784)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)

-- Block entity being ticked --
Details:
	Name: buildcrafttransport:pipe_holder // buildcraft.transport.tile.TilePipeHolder
	Block type: ID #417 (tile.pipeHolder // buildcraft.transport.block.BlockPipeHolder)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1271,82,-2840), Chunk: (at 9,5,8 in -80,-178; contains blocks -1280,0,-2848 to -1265,255,-2833), Region: (-3,-6; contains chunks -96,-192 to -65,-161, blocks -1536,0,-3072 to -1025,255,-2561)
	Actual block type: ID #417 (tile.pipeHolder // buildcraft.transport.block.BlockPipeHolder)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
```

**Comment by AEnterprise** [comment]
this is only a partial crashreport, could you upload the full report to gist or pastebin and link it here?

**Comment by XakepSDK** [comment]
Latest version from curseforge.
https://pastebin.com/ziBJmxfr

**Comment by XakepSDK** [comment]
Latest commit build(7.99.3) report:
https://pastebin.com/68WffGA5

**Comment by AEnterprise** [comment]
thanks for the report (and even restesting)

this is a vanilla minecraft method crashing, could you reproduce this with only BC installed? if not another mod is messing with things (most likely a coremod doing stuff it's not suposed to do)

also when does this crash? on loading your world or are you enabeling F3 for it to crash?

**Comment by XakepSDK** [comment]
I'm connecting to my server, client freezes for 1-3 sec and crashes.
Fine in local world with buildcraft.
I try to download my server world.

**Comment by XakepSDK** [comment]
Oh, after 1000 restarts. Optifine crashes client(tested: B7,B8). Maybe forge version incompatible, i don't want test this again.
