### ISSUE TITLE
Crash on update to 7.99.3

### ISSUE THREAD

**Issue by aim-gaming** [BuildCraft/BuildCraft#3564]
I'm getting a crash when I update to 7.99.3, while 7.99.1 works perfectly.

Crash report is as follows:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.85.jar)
  IC2core (industrialcraft-2-2.7.9-ex111.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 5/10/17 2:46 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:202)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:189)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:112)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:76)
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178414_a(FaceBakery.java:58)
	at BlockModelUtils.makeBakedQuad(BlockModelUtils.java:84)
	at BlockModelUtils.makeModelCube(BlockModelUtils.java:61)
	at BetterGrass.update(BetterGrass.java:73)
	at TextureUtils.resourcesReloaded(TextureUtils.java:295)
	at TextureUtils$1.func_110549_a(TextureUtils.java:338)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at TextureUtils.registerResourceListener(TextureUtils.java:342)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2751)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1282)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 209017664 bytes (199 MB) / 386695168 bytes (368 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	U	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	U	buildcraftfactory{7.99.3} [BC Factory] (buildcraft-7.99.3.jar) 
	U	buildcrafttransport{7.99.3} [BC Transport] (buildcraft-7.99.3.jar) 
	U	buildcraftlib{7.99.3} [BuildCraft Lib] (buildcraft-7.99.3.jar) 
	U	buildcraftbuilders{7.99.3} [BC Builders] (buildcraft-7.99.3.jar) 
	U	buildcraftcore{7.99.3} [BuildCraft] (buildcraft-7.99.3.jar) 
	U	buildcraftenergy{7.99.3} [BC Energy] (buildcraft-7.99.3.jar) 
	U	buildcraftrobotics{7.99.3} [BC Robotics] (buildcraft-7.99.3.jar) 
	U	buildcraftsilicon{7.99.3} [BC Silicon] (buildcraft-7.99.3.jar) 
	U	forestry{5.3.3.94} [Forestry] (forestry_1.11.2-5.3.3.94.jar) 
	U	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	U	ic2{2.7.9-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.9-ex111.jar) 
	U	inventorytweaks{1.62+beta.85.4b3a8f6} [Inventory Tweaks] (InventoryTweaks-1.62+beta.85.jar) 
	U	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	U	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar) 
	U	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	U	xaerominimap{1.12.8} [Xaero's Minimap] (Xaeros_Minimap_1.12.8_Forge_1.11.jar) 
	U	xaeroworldmap{1.9} [Xaero's World Map] (XaerosWorldMap_b1.9_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.85.jar)
  invtweaks.forge.asm.ContainerTransformer
IC2core (industrialcraft-2-2.7.9-ex111.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 860M/PCIe/SSE2'
	Launched Version: 1.11.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Default 32x32.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.161 Lite.zip
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 860M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by afdw** [comment]
Please try disabling Optifine.

**Comment by aim-gaming** [comment]
Everything works after I updated forge. I guess I should've checked for updates before posting the issue.
