### ISSUE TITLE
7.99.3 Won't work with others mods.

### ISSUE THREAD

**Issue by Aeethereus** [BuildCraft/BuildCraft#3573]
The only way the game loaded was with only forge 96 and Builcraft 7.99.3 even with optifine. It just stays in loading world...

**Comment by AEnterprise** [comment]
if it loaded with just BC then it's most likely another mod causing the issue

can you upload your client log to gist/pastebin and link it here? that might contain a clue about what's going on

**Comment by Aeethereus** [comment]
https://pastebin.com/XY9bqGc1

**Comment by Aeethereus** [comment]
[11:27:02] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V
	at net.minecraft.world.World.func_72939_s(World.java:1801) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
[11:27:02] [Thread-22/INFO]: [STDOUT]: URL requested: http://optifine.net/crashReport

**Comment by AEnterprise** [comment]
optifine issue, you need to update it, if that doesn't fix it they have not updated to recent forge changes
