### ISSUE TITLE
Crash When Launching MC

### ISSUE THREAD

**Issue by emilyseeto** [BuildCraft/BuildCraft#3585]
Minecraft crash when launching with BuildCraft.

This is the crash report
`---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2017/5/16 下午 9:32
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Lbuildcraft/energy/worldgen/BiomeGenOilDesert;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: Lbuildcraft/energy/worldgen/BiomeGenOilDesert;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
	at java.lang.Class.getDeclaredField(Class.java:2060)
	at cpw.mods.fml.common.FMLModContainer.parseSimpleFieldAnnotation(FMLModContainer.java:404)
	at cpw.mods.fml.common.FMLModContainer.processFieldAnnotations(FMLModContainer.java:358)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: buildcraft.energy.worldgen.BiomeGenOilDesert
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenDesert
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 39 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenDesert
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 206658576 bytes (197 MB) / 428093440 bytes (408 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D6 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	ImmibisMicroblocks{59.1.2} [Immibis's Microblocks] (immibis-microblocks-59.1.2.jar) 
	UC	intelliinput{2.3.2} [IntelliInput for 1.7.10] (minecraft.jar) 
	UC	OldModelLoader{1.0} [OldModelLoader] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UC	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UC	debug{1.0} [debug] (Dense-Ores-Mod-1.7.10.jar) 
	UC	net.minecraft.rosettaenchanttable{0.0.5} [Rosetta Enchant Table] (%5B1.7.10%5D%5Bforge1080%5Dmod_RosettaEnchantTable_v0.0.5.zip) 
	UC	net.minecraft.storagebox.mod_StorageBox{3.0.5} [StorageBox] (%5B1.7.10%5D%5Bforge1180%5Dmod_StorageBox_v3.0.5.zip) 
	UC	net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.0} [CutAllSMP] (%5B1.7.10%5D%5Bforge1291%5Dmod_CutAllSMP_v2.5.0.zip) 
	UC	net.minecraft.scalar.digall.mod_DigAllSMP{2.3.0} [DigAllSMP] (%5B1.7.10%5D%5Bforge1291%5Dmod_DigAllSMP_v2.3.0.zip) 
	UC	net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.1} [MineAllSMP] (%5B1.7.10%5D%5Bforge1291%5Dmod_MineAllSMP_v2.6.1.zip) 
	UC	mod_ecru_AutoSowSeed_Forge{2.0.1} [Auto sow seed] (%5B1.7.10%5DAutoSowSeed_Forge v2.0.1.jar) 
	UC	mod_ecru_MapleTree{1.1.33c} [MapleTree] (%5B1.7.10%5DMapleTree Forge v1.1.33c.jar) 
	UC	ExPContainerMod{1.2.0} [ExPContainerMod] (%5B1.7.2%5D ExPContainer 1.2.0-a.jar) 
	UC	net.minecraft.scalar.pickupwidely.mod_PickupWidelySMP{1.2.3} [PickupWidelySMP] (%5B1.7.2%5D%5Bforge1033%5Dmod_PickupWidelySMP_v1.2.3.zip) 
	UC	mod_ecru_DirectionTorch{1.0.3} [DirectionTorch] (%5B1.7.x%5DDirectionTorch v1.0.3.jar) 
	UC	mod_ecru_Faucet_Forge{1.0.2a} [Faucet] (%5B1.7.x%5DFaucet Forge v1.0.2a.zip) 
	UC	SC0_SpaceCore{0.7.14} [SpaceCore] (1.7.10-SpaceCore-0.7.14.jar) 
	UC	SC0_UsefulPets{1.3} [Useful Pets] (1.7.10-Useful_Pets-1.3.jar) 
	UC	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UC	DCsAppleMilk{1.7.10_2.9m_for1291} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.9m_for1291.jar) 
	UC	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.9m_for1291.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	ArchitectureCraft{1.4.2} [ArchitectureCraft] (ArchitectureCraft-1.4.2-mc1.7.10.jar) 
	UC	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UC	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UC	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UC	B0bGrowsOre{2.5.4} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.5.4 for 1.7.10.jar) 
	UC	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UC	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UE	BuildCraft|Core{7.1.21} [BuildCraft] (buildcraft-7.1.21.jar) 
	UE	BuildCraft|Builders{7.1.21} [BC Builders] (buildcraft-7.1.21.jar) 
	UE	BuildCraft|Energy{7.1.21} [BC Energy] (buildcraft-7.1.21.jar) 
	UE	BuildCraft|Factory{7.1.21} [BC Factory] (buildcraft-7.1.21.jar) 
	UE	BuildCraft|Robotics{7.1.21} [BC Robotics] (buildcraft-7.1.21.jar) 
	UE	BuildCraft|Silicon{7.1.21} [BC Silicon] (buildcraft-7.1.21.jar) 
	UE	BuildCraft|Transport{7.1.21} [BC Transport] (buildcraft-7.1.21.jar) 
	UC	CameraStudio{2.1710} [Camera Studio] (CameraStudioV2.1710(mc1.7.10).zip) 
	UC	cfm{3.4.8} [ｧ9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UC	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UC	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UC	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2 - 1.7.10.jar) 
	UC	desertwells{V0.1 - 1.7.10} [Desert Wells] (Desert Wells-V0.1 - 1.7.10.jar) 
	UC	fairylights{0.6} [Fairy Lights] (fairylights-0.6-1.7.10.jar) 
	UC	gravestonemod{1.7.10} [Gravestones] (GraveStones 1.7.10 -3.jar) 
	UC	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
	UC	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
	UC	handofcats{1.3f} [Hand of Cats] (HandOfCats1.7.10_v1.3f.jar) 
	UC	mod.ymt.air.HariboteAirCraft{172v3 hiten} [HariboteAirCraft] (HariboteAirCraft_172v3.zip) 
	UC	hearts{1.1.1} [Heart Crystal Mod] (Heart Crystal by NukeDuck [1.7.10][1.1.1].jar) 
	UC	IC2{2.2.817-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.817-experimental.jar) 
	UC	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UC	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UC	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UC	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UC	LittleBlocks{2.2.4.4} [Little Blocks] (LittleBlocks-2.2.4.4.jar) 
	UC	lmmx{1.0} [lmmx] (littleMaidMobX-1.7.x_0.1.1.jar) 
	UC	MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX-1.7.x_0.1.1.jar) 
	UC	zabuton{1.0} [zabuton] (littleMaidMobX-1.7.x_0.1.1.jar) 
	UC	NyankoMod{1.2.3} [NyankoMod] (NyankoMod_1.7.10_1.2.3.jar) 
	UC	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UC	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UC	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-Mod-by-grim3212-1.7.10.jar) 
	UC	mod.ymt.rndsp.RandomSpawner{17Av1} [RandomSpawner] (RandomSpawner-17Av1.zip) 
	UC	ShibainuMod{1.4.0} [ShibainuMod] (ShibainuMod_1.7.10_1.4.0.jar) 
	UC	flammpfeil.slashblade{mc1.7.10-r85} [SlashBlade] (SlashBlade-mc1.7.10-r85.jar) 
	UC	spawnchecker{2.1.4.128} [SpawnChecker] (SpawnChecker-2.1.4.128.jar) 
	UC	spawnchecker.presetmode{2.1.4.128} [SpawnChecker preset mode] (SpawnChecker-2.1.4.128.jar) 
	UC	StorageDrawers{1.7.10-1.10.8} [Storage Drawers] (Storage-Drawers-Mod-1.7.10.jar) 
	UC	TofuCraft{2.1.7-MC1.7.10} [TofuCraft] (TofuCraft-2.1.7-mc1.7.10.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	denseores{1.0} [Dense Ores] (Dense-Ores-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8`

**Comment by AEnterprise** [comment]
looks like core BC classes are missing, can you redownload from http://www.mod-buildcraft.com/pages/download.html ? if it still crashes then another mod is having a hard dependency on an older BC version and needs to be updated
