### ISSUE TITLE
Error when loading ver 7.99.3

### ISSUE THREAD

**Issue by ryamamoton** [BuildCraft/BuildCraft#3607]
--- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (Backpacks 1.11.2 - 3.1.9.jar)
  FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.99-BETA.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 5/23/17 7:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.NullPointerException
	at buildcraft.lib.list.ListOreDictionaryCache.getType(ListOreDictionaryCache.java:43)
	at buildcraft.lib.list.ListOreDictionaryCache.registerName(ListOreDictionaryCache.java:90)
	at buildcraft.lib.list.VanillaListHandlers.fmlPostInit(VanillaListHandlers.java:20)
	at buildcraft.lib.BCLib.postInit(BCLib.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1183236848 bytes (1128 MB) / 3030908928 bytes (2890 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2299 Optifine OptiFine_1.11.2_HD_U_B8 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2299.jar) 
	UCHIJ	forge{13.20.0.2299} [Minecraft Forge] (forge-1.11.2-13.20.0.2299.jar) 
	UCHIJ	backpacks16840{3.1.9} [Backpacks!] (Backpacks 1.11.2 - 3.1.9.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJ	roxatalldoors{1.11v1.6.0} [Roxa's Tall Doors Mod] (1.11v1.6.0_RoxaTallDoorsMod.jar) 
	UCHIJ	uncraftingtable{1.7.1} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1.jar) 
	UCHIJ	movillages{1.5.3} [Mo' Villages] ([1.11]MoVillages-1.5.3.jar) 
	UCHIE	actuallyadditions{1.11.2-r108} [Actually Additions] (ActuallyAdditions-1.11.2-r108.jar) 
	UCHIJ	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar) 
	UCHIJ	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCHIJ	appletrees{V2} [Apple Trees] (AppleTrees-1.11.2-V2.jar) 
	UCHIJ	armorextended{1.0.0} [Armor Extended] (Armor Extended-1.0.jar) 
	UCHIJ	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.1.4.jar) 
	UCHIJ	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.5.jar) 
	UCHIJ	biomesoplenty{6.0.2.2157} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2157-universal.jar) 
	UCHIE	buildcraftlib{7.99.3} [BuildCraft Lib] (buildcraft-7.99.3.jar) 
	UCHIE	buildcraftcore{7.99.3} [BuildCraft] (buildcraft-7.99.3.jar) 
	UCHIE	buildcraftfactory{7.99.3} [BC Factory] (buildcraft-7.99.3.jar) 
	UCHIE	buildcrafttransport{7.99.3} [BC Transport] (buildcraft-7.99.3.jar) 
	UCHIE	buildcraftbuilders{7.99.3} [BC Builders] (buildcraft-7.99.3.jar) 
	UCHIE	buildcraftenergy{7.99.3} [BC Energy] (buildcraft-7.99.3.jar) 
	UCHIE	buildcraftrobotics{7.99.3} [BC Robotics] (buildcraft-7.99.3.jar) 
	UCHIE	buildcraftsilicon{7.99.3} [BC Silicon] (buildcraft-7.99.3.jar) 
	UCHIJ	cavern{1.7.0} [Cavern] (Cavern_1.11.2-v1.7.0.jar) 
	UCHIJ	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJ	chesttransporter{2.7.9} [Chest Transporter] (ChestTransporter-1.11.2-2.7.9.jar) 
	UCHIJ	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCHIJ	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJ	chiselsbytes{0.5} [Chisel & Bytes] (ChiselsBytes-1.11.2-0.5.jar) 
	UCHIJ	coralreef{1.0} [Coral Reef] (CoralReef-1.4.jar) 
	UCHIJ	craftablehorsearmour{1.3} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmor-1.3.0-1.11.jar) 
	UCHIJ	crafteabletotemandchainmailarmormod{1.0.0} [Crafteable Totem And ChainMail Armor Mod] (Crafteable Totem And ChainMail Armor Mod.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (crayfish furniture-4.1.2-mc1.11.2.jar) 
	UCHIJ	customachievements{1.11.2-0.3.0} [Custom Achievements] (customachievements-1.11.2-0.3.0.jar) 
	UCHIJ	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2(10may17).jar) 
	UCHIJ	cyclopscore{0.10.2} [Cyclops Core] (CyclopsCore-1.11.2-0.10.2.jar) 
	UCHIJ	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (Damage-Indicator-1.11.2.jar) 
	UCHIJ	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJ	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJ	koresample{1.11.2-L1.2} [Kore Sample] (koresample-1.11.2-L1.2.jar) 
	UCHIJ	dendrology{1.11.2-L1.2.1} [Ancient Trees] (dendrology-1.11.2-L1.2.1.jar) 
	UCHIJ	dynamiclights{1.4.6} [Dynamic Lights] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_onfire{1.0.7} [Dynamic Lights on burning] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_creepers{1.0.6} [Dynamic Lights on Creepers] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_dropitems{1.1.0} [Dynamic Lights on ItemEntities] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_entityclasses{1.0.1} [Dynamic Lights on specified Entities] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_mobequipment{1.1.0} [Dynamic Lights on Mob Equipment] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_flamearrows{1.0.1} [Dynamic Lights on Flame enchanted Arrows] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_floodlights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_otherplayers{1.0.9} [Dynamic Lights Other Player Light] (DynamicLights-1.11.2.jar) 
	UCHIJ	dynamiclights_theplayer{1.1.3} [Dynamic Lights Player Light] (DynamicLights-1.11.2.jar) 
	UCHIJ	endercrop{1.11-1.3.4} [Ender Crop] (endercrop-1.11-1.3.4.jar) 
	UCHIJ	energyconverters{1.0} [Energy Converters] (energyconverters_1.11.2-0.6.0.13.jar) 
	UCHIJ	findercompass{1.11.2} [Finder Compass] (FinderCompass-1.11.2.jar) 
	UCHIJ	foodexpansion{1.3} [Food Expansion] (FoodExpansion1.3.1-1.11.2.jar) 
	UCHIJ	forestry{5.3.4.99} [Forestry] (forestry_1.11.2-5.3.4.99.jar) 
	UCHIJ	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.99-BETA.jar) 
	UCHIJ	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.99-BETA.jar) 
	UCHIJ	graves{1.11-b2-universal} [Graves Mod] (Graves-1.11-b2-universal.jar) 
	UCHIJ	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCHIJ	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJ	ironchest{1.11.2-7.0.19.803} [Iron Chest] (ironchest-1.11.2-7.0.19.803.jar) 
	UCHIJ	jaff{1.6_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6_for_1.11.2.jar) 
	UCHIJ	magistics{1.11.2-v3.0-alpha} [Magistics] (Magistics-1.11.2-v3.0-alpha.jar) 
	UCHIJ	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJ	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJ	mbm{1.6} [Master Builders Mod] (MBM-Master_Builders_Mod v.1.6_1.11.2.jar) 
	UCHIJ	minecolonies{1.11.2-0.7.811} [MineColonies] (minecolonies-universal-1.11.2-0.7.811.jar) 
	UCHIJ	missing_pieces{4.1.2} [Missing Pieces] (missing_pieces-1.11.2-4.1.2.jar) 
	UCHIJ	morefuelsmod-1.11.x{1.6.0} [§4More Fuels Mod] (morefuelsmod-1.11.x-1.6.0.jar) 
	UCHIJ	natura{1.11.2-4.2.0.16} [Natura] (natura-1.11.2-4.2.0.16.jar) 
	UCHIJ	newthings{1.6-1.11.2} [101 New Things] (newthings-1.5-1.11.2.jar) 
	UCHIJ	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJ	nuclearcraft{2.2d} [NuclearCraft] (NuclearCraft-2.2d--1.11.2.jar) 
	UCHIJ	obsidiantools{1.6.2} [Obsidian Tools & Armor] (ObsidianToolsArmor_V1.6.2.jar) 
	UCHIJ	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJ	signpost{1.05.2} [Sign Post] (signpost-1.11.2-1.05.2.jar) 
	UCHIJ	silentlib{2.1.3} [Silent Lib] (SilentLib-1.11.x-2.1.3-58.jar) 
	UCHIJ	simplecorn{2.1.5} [Simple Corn] (SimpleCorn1.11.2-2.1.5.jar) 
	UCHIJ	spawnercraft{4.0} [SpawnerCraft] (SpawnerCraft 1.11.2-4.0.0.jar) 
	UCHIJ	storageboats{2.0} [Storage Boats Mod] (StorageBoats-2.2.jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.6} [Storage Drawers] (StorageDrawers-1.11.2-4.2.6.jar) 
	UCHIJ	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.11.2-2.0.0.jar) 
	UCHIJ	subcommonlib{1.1.4.1} [Subaraki's Common Library] (sublib-1.11.2-1.1.4.1.jar) 
	UCHIJ	sugiforest{1.3.2} [SugiForest] (SugiForest_1.11.2-v1.3.2.jar) 
	UCHIJ	tconstruct{1.11.2-2.7.0.19} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.19.jar) 
	UCHIJ	telepads{1.11.2-1.0.2.0} [Telepads] (telepads-1.11.2-1.0.2.0.jar) 
	UCHIJ	tinkersaddons{1.0.5} [Tinkers' Addons] (Tinkers' Addons-1.11.x-1.0.5.jar) 
	UCHIJ	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJ	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.11-1.0.v.19.jar) 
	UCHIJ	wearablebackpacks{2.3.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.0.jar) 
	UCHIJ	xaerominimap{1.12.8} [Xaero's Minimap] (Xaeros_Minimap_1.12.8_Forge_1.11.jar) 
	UCHIJ	zeiyocraft{0.8.1} [ZeiyoCraft] (zeiyocraft-0.8.1.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (Backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.99-BETA.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DLFMLCorePlugin (DynamicLights-1.11.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 0' Renderer: 'AMD Radeon HD 7600M Series'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.11.2_HD_U_B8
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 0
	OpenGlRenderer: AMD Radeon HD 7600M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by AlexIIL** [comment]
That's odd. It looks like some mod is registering an ore with a null name. I'll add a defensive guard against that, but finding out which mod (or mods) registers that would be useful.
