### ISSUE TITLE
7.99.4 Volume Box not resizeable or removable

### ISSUE THREAD

**Issue by thefrasca** [BuildCraft/BuildCraft#3678]
When attempting to resize volume box for Filler, Master connector throws error.  Appears to be missing constructor.   Volume box can't be resized and cannot be removed once placed.

[20:49:57] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
        at buildcraft.core.marker.volume.EnumAddonSlot.getBoundingBox(EnumAddonSlot.java:47) ~[EnumAddonSlot.class:?]
        at buildcraft.core.marker.volume.EnumAddonSlot.getSelectingBoxAndSlot(EnumAddonSlot.java:59) ~[EnumAddonSlot.class:?]
        at buildcraft.core.marker.volume.EnumAddonSlot.getSelectingBoxAndSlot(EnumAddonSlot.java:75) ~[EnumAddonSlot.class:?]
        at buildcraft.core.item.ItemMarkerConnector.newVolumeCacheStuff_onItemRightClick(ItemMarkerConnector.java:138) ~[ItemMarkerConnector.class:?]
        at buildcraft.core.item.ItemMarkerConnector.func_77659_a(ItemMarkerConnector.java:47) ~[ItemMarkerConnector.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:196) ~[afj.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:360) ~[lz.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:709) ~[mi.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jn.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jn.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

**Comment by ckimes89** [comment]
This may be related:

https://github.com/Vazkii/Botania/commit/270edf5b235a9f37324dc624d404038ae5516eb8

**Comment by AlexIIL** [comment]
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)
