### ISSUE TITLE
[1.11.2] Crash when looking at Auto Workbench in F3 Debug Mode

### ISSUE THREAD

**Issue by stdio2016** [BuildCraft/BuildCraft#3721]
Steps to Reproduce:
1. Create a single player map
2. Enter F3 Debug Mode
3. Build an Auto Workbench
4. Look at it
5. `Shutting down internal server`, then crash

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/11/17 8:41 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at buildcraft.factory.tile.TileAutoWorkbenchBase.getDebugInfo(TileAutoWorkbenchBase.java:82)
	at buildcraft.core.client.RenderTickListener.renderOverlay(RenderTickListener.java:125)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_RenderTickListener_renderOverlay_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:695)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:171)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1089)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.run(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

The code:

     public void getDebugInfo(List<String> left, List<String> right, EnumFacing side) {
        left.add("");
        left.add(currentRecipe.toString());
    }

`currentRecipe` can be null

**Comment by AEnterprise** [comment]
fixed on 1.11.2 and 1.12, will do the PR for 1.11.2 later if i have some more fixes as this is just a simple one liner

**Comment by AlexIIL** [comment]
Please don't mark bugs as "fixed" unless it's fixed on the 8.0.x branch.
