### ISSUE TITLE
7.99.6 - Client Sprite related crash on startup

### ISSUE THREAD

**Issue by Bysokar** [BuildCraft/BuildCraft#3772]
Hi All,

Just starting to build my 1.11.2 pack and encountered this crash on client side as the client finishes loading up to the main menu.
Doesn't occur without BuildCraft installed.
I'm using 2429 forge.

As this occurs  when the client reaches the main menu, I'll also mention I run customMainMenu 2.0.5.. but this is unlikely to be related.

Regards,
Bysokar

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (advabcedrocketry-1.11.2.1.2.3.1.jar)
  IC2core (industrialcraft-2.2.7.81.111.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2.3.0.0.284.jar)
  TransformerLoader (OpenComputers-1.11.2.1.7.0.40.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2.4.2.7.15.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  CTMCorePlugin (CTM-0.2.1.10.jar)
Contact their authors BEFORE contacting forge
// But it works on my machine.

Time: 8/12/17 12:44 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.func_94219_l(AtlasSpriteSwappable.java:43)
	at net.minecraft.client.renderer.texture.TextureMap.func_94248_c(TextureMap.java:573)
	at net.minecraft.client.renderer.texture.TextureMap.func_110550_d(TextureMap.java:685)
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:141)
	at TextureUtils.resourcesReloaded(TextureUtils.java:318)
	at TextureUtils$1.func_110549_a(TextureUtils.java:338)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at TextureUtils.registerResourceListener(TextureUtils.java:342)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2751)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1282)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by Bysokar** [comment]
Apologies but this may be a result of using optifine. Such a shit mod sometimes :(
