### ISSUE TITLE
[7.99.12]

### ISSUE THREAD

**Issue by bhi-elliot** [BuildCraft/BuildCraft#3865]
**Buildcraft** version: 7.99.12
**Forge** version: forge-1.12.2-14.23.0.2552-universal
spongeforge-1.12.2-2529-7.0.0-BETA-2744
Singleplayer/multiplayer: multiplayer

Error produced:
```
[Server thread/ERROR] [FML]: Parsing error loading built-in advancement buildcraftcore:goggles
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'buildcraftcore:goggles'
        at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
        at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
        at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1333) ~[ForgeHooks.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1315) [ForgeHooks.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1289) [ForgeHooks.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:789) [WorldManager.class:1.12.2-2529-7.0.0-BETA-2744]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:759) [WorldManager.class:1.12.2-2529-7.0.0-BETA-2744]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3553) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by AEnterprise** [comment]
just a (harmless) warning and advancement that won't load (see https://github.com/BuildCraft/BuildCraft/issues/3849#issuecomment-346383679)

will be fixed eventually, there are just some WIP advancements for non released things

**Comment by bhi-elliot** [comment]
Thanks for the reply.
Whoops! Sorry I did not find that when I searched to see if this had already been reported.
Great work on the mod! Thanks for getting it to 1.12.2!
Peace!

**Comment by AlexIIL** [comment]
I'll leave this open as a reminder to fix advancements if the given item doesn't exist later.
