### ISSUE TITLE
Server Crashes when obsidian pips are powered but not connected

### ISSUE THREAD

**Issue by Miles-Ma** [BuildCraft/BuildCraft#3900]
**Minecraft** version: 1.11.2 (server)
**Singleplayer/multiplayer**: multiplayer
**Buildcraft** version: 7.99.8.1
**Forge** version: 13.20.1.2393
**crashreport**: 
```
java.lang.NullPointerException: Ticking block entity
	at buildcraft.transport.pipe.behaviour.PipeBehaviourObsidian.getSuckingBox(PipeBehaviourObsidian.java:110)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourObsidian.receivePower(PipeBehaviourObsidian.java:195)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourObsidian.getPowerRequested(PipeBehaviourObsidian.java:185)
	at buildcraft.lib.engine.TileEngineBase_BC8.getPowerToExtract(TileEngineBase_BC8.java:354)
	at buildcraft.lib.engine.TileEngineBase_BC8.sendPower(TileEngineBase_BC8.java:376)
	at buildcraft.lib.engine.TileEngineBase_BC8.func_73660_a(TileEngineBase_BC8.java:312)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
```
Singleplayer/multiplayer: Multiplayer

I found a bug: an independent obsidian pipe with power supply(from redstone engine or pipe pulsor) will always cause crash. If both powered and connected, it works fine.
I guess #3884 is saying the same thing, but I'm on 1.11.2 and BC 7.99.8.1

**Comment by AEnterprise** [comment]
this is indeed the same thing though there probably won't be any more 1.11 releaes now BC moved to 1.12 (and this isn't that major of a bug)

**Comment by AlexIIL** [comment]
Crashes are major :P
This can probably just be cherry picked from the commit that fixed it in 1.12

**Comment by AlexIIL** [comment]
Fixed in https://github.com/BuildCraft/BuildCraft/commit/2ee58609f55d43fa154212c4c957df94747b2ab3

**Comment by Crusher04** [comment]
This also happens in 1.12.2 version of MC. 
Buildcraft Version: 7.99.12

Crash Log:

[crash-2018-01-11_06.18.11-server.txt](https://github.com/BuildCraft/BuildCraft/files/1622320/crash-2018-01-11_06.18.11-server.txt)

**Comment by LuigiHutch** [comment]
Yes... update to 7.99.13
