### ISSUE TITLE
Glitch in Stirling Engine when using vanilla bucket as fuel

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#3938]
**Buildcraft** version: 7.99.13
**Forge** version: 14.23.1.2578
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
(It's not very long, so I decide to just paste here)
````
[12:09:18] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Attempted to set stack[0] when it was invalid! (1xitem.bucket@0)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Attempted to set stack[0] when it was invalid! (1xitem.bucket@0)
	at buildcraft.lib.tile.item.ItemHandlerSimple.setStackInSlot(ItemHandlerSimple.java:245) ~[ItemHandlerSimple.class:?]
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80) ~[SlotItemHandler.class:?]
	at net.minecraft.inventory.Container.func_190896_a(Container.java:527) ~[afr.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1191) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:50) ~[is.class:?]
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:12) ~[is.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
````

Singleplayer/multiplayer: Singleplayer 

Additional information:
* The log spam occurs when you put vanilla lava bucket in. Game does NOT crash due to this.
* The lava bucket will be consumed as intended; even though it still shows lava bucket, clicking the lava bucket will give you the empty bucket back as intended.

**Comment by AlexIIL** [comment]
I've got this bug before in testing and never realised that the log is happening on the *client* where it doesn't know the previous fuel type...

**Comment by AEnterprise** [comment]
side effect of this: upon reloading the server also doesn't know the previous fuel type and then the serverside slot is also refusing the empty bucket upon deserializing of NBT

**Comment by AlexIIL** [comment]
I think this was fixed in https://github.com/BuildCraft/BuildCraft/commit/b153d4bb370ac5e91fc7ec461e6b5021b8ba0501, so I should be able to remove the empty bucket check.
