### ISSUE TITLE
bug 1.12.2

### ISSUE THREAD

**Issue by demon57730** [BuildCraft/BuildCraft#4066]
BuildCraft version: 
buildcraft-7.99.15.jar
buildcraft-compat-7.99.14.jar

Forge version: 1.12.2 14.23.2.2624
Link to crash report or log: 
Singleplayer or multiplayer: multiplayer server

log: https://pastebin.com/qgWFSYCF

[09:52:53] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement buildcraftcore:goggles
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'buildcraftcore:goggles'
at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1342) [ForgeHooks.class:?]
at net.minecraftforge.common.ForgeHooks$$Lambda$1961/2019381141.apply(Unknown Source) [ForgeHooks.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1324) [ForgeHooks.class:?]
at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1298) [ForgeHooks.class:?]
at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:790) [WorldManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:760) [WorldManager.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3552) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by AEnterprise** [comment]
dupelicate of https://github.com/BuildCraft/BuildCraft/issues/3865
