### ISSUE TITLE
Pump crashing without energy module

### ISSUE THREAD

**Issue by HealV** [BuildCraft/BuildCraft#4109]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2611
Link to crash report or log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.166.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 4/1/18 2:44 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: buildcraft/energy/BCEnergyFluids
	at buildcraft.factory.tile.TilePump.buildQueue(TilePump.java:156)
	at buildcraft.factory.tile.TilePump.func_73660_a(TilePump.java:217)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: buildcraft.energy.BCEnergyFluids
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at buildcraft.factory.tile.TilePump.buildQueue(TilePump.java:156)
	at buildcraft.factory.tile.TilePump.func_73660_a(TilePump.java:217)

-- Block entity being ticked --
Details:
	Name: buildcraftfactory:pump // buildcraft.factory.tile.TilePump
	Block type: ID #389 (tile.pumpBlock // buildcraft.factory.block.BlockPump)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (6,63,190), Chunk: (at 6,3,14 in 0,11; contains blocks 0,0,176 to 15,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #389 (tile.pumpBlock // buildcraft.factory.block.BlockPump)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: New World-
	All players: 1 total; [GCEntityPlayerMP['Wolfie'/1800, l='New World-', x=8.23, y=64.00, z=189.02]]
	Chunk stats: ServerChunkCache: 638 Drop: 0
	Level seed: -155440033324579742
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-4,64,172), Chunk: (at 12,4,12 in -1,10; contains blocks -16,0,160 to -1,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 416 game time, 416 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 118774 (now: false), thunder time: 51142 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2404302904 bytes (2292 MB) / 3892314112 bytes (3712 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_D1 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State               | ID                  | Version      | Source                                        | Signature                                |
	|:------------------- |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | forge               | 14.23.2.2611 | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | micdoodlecore       |              | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | buildcraftlib       | 7.99.15      | buildcraft-core-7.99.15.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | buildcraftcore      | 7.99.15      | buildcraft-core-7.99.15.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | buildcrafttransport | 7.99.15      | buildcraft-transport-7.99.15.jar              | None                                     |
	| UCHIJAAAAAAAAAAAAAA | forgelin            | 1.6.0        | Forgelin-1.6.0.jar                            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | bcextrapipes        | 1            | bc-extra-pipes-1.12.2-1.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAAAAAAA | buildcraftfactory   | 7.99.15      | buildcraft-factory-7.99.15.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | buildcraftsilicon   | 7.99.15      | buildcraft-silicon-7.99.15.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | codechickenlib      | 3.1.6.339    | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | ic2                 | 2.8.16-ex112 | industrialcraft-2-2.8.16-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAAAAAAAAAAAA | galacticraftcore    | 4.0.1.166    | GalacticraftCore-1.12.2-4.0.1.166.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | galacticraftplanets | 4.0.1.166    | Galacticraft-Planets-1.12.2-4.0.1.166.jar     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | instantunify        | 1.1.1        | instantunify-1.12.2-1.1.1.jar                 | None                                     |
	| UCHIJAAAAAAAAAAAAAA | jei                 | 4.8.5.159    | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | journeymap          | 1.12.2-5.5.2 | JourneyMap-Mod-1.12.2-Unlimited.jar           | None                                     |
	| UCHIJAAAAAAAAAAAAAA | movillages          | 1.5.4        | MoVillages-1.12.2.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | nei                 | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | redstonepaste       | 1.7.5        | redstonepaste-mc1.12-1.7.5.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | bspkrscore          | at_0.9       | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | treecapitator       | at_0.9       | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | upsizer             | 4.0.1        | Upsizer-1.12.1.jar                            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | wanionlib           | 1.12.2-1.5   | WanionLib-1.12.2-1.5.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | unidict             | 1.12.2-2.4c  | UniDict-1.12.2-2.4c.jar                       | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.166.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Wolfie'/1800, l='New World-', x=8.23, y=64.00, z=189.02]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.24
	OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

Singleplayer or multiplayer: both
Steps to reproduce: place pump
Additional information: Ask anything you want

**Comment by afdw** [comment]
This happened because you haven't the Energy module. It's a know bug, thanks for reporting it on GitHub.

**Comment by HealV** [comment]
OMG
Thanks

**Comment by afdw** [comment]
And no, this isn't fixed yet.
