### ISSUE TITLE
crash with the ather II

### ISSUE THREAD

**Issue by KnightBlood** [BuildCraft/BuildCraft#4142]
BuildCraft version: 7.99.16
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information: 

Time: 4/24/18 7:47 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BC Silicon (buildcraftsilicon)
Caused by: java.lang.IllegalStateException: Scanning facade states
    State = aether:therastone_brick_decorative[variant=keystone]
    Block = aether:therastone_brick_decorative
    Stack = 1xtile.aether.therastone_brick@6
    varying-properties: {
    }
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:331)
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Read (from NBT) state was different! (
	StateInfo [id=308362695, block = Block{minecraft:air}, state =  minecraft:air]
 !=
	StateInfo [id=438245538, block = Block{aether:therastone_brick_decorative}, state =  aether:therastone_brick_decorative[variant=keystone]]
	NBT = {state:{Properties:{variant:"keystone"},Name:"aether:therastone_brick_decorative"}}
)
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:308)
	... 41 more

**Comment by AlexIIL** [comment]
Relevant Aether 2 issue: https://git.gildedgames.com/GildedGames/Aether-II/issues/796.

This really indicates an issue with how block states are saved in Aether-II, so hopefully they will fix it on their end.

**Comment by AlexIIL** [comment]
According to the Aether-II tracker they have fixed this on their end and will hopefully release a build sometime in the future.

**Comment by Rongmario** [comment]
Close this, jeez. We don't need duplicate issues and especially this was certainly an Aether issue.

**Comment by AEnterprise** [comment]
we do need an issue here as people don't know if this is an aether issue or BC issue so they will come here and people rarely check closed issues sadly

**Comment by KnightBlood** [comment]
https://git.gildedgames.com/GildedGames/Aether-II/issues/796
Fixed with 4c3be093.

**Comment by AlexIIL** [comment]
Has the fix been released in a build yet? The curseforge changelog doesn't mention it...
