### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: Could not initialize class buildcraft.core.client.RenderTickListener

### ISSUE THREAD

**Issue by min20120907** [BuildCraft/BuildCraft#4224]
BuildCraft version: 7.99.17
Forge version: 1.12.2 - 14.23.4.2705
Link to crash report or log: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/9/18 8:17 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class buildcraft.core.client.RenderTickListener
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_276_RenderTickListener_renderOverlay_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_276_RenderTickListener_renderOverlay_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CangyuLin'/134, l='MpServer', x=-180.61, y=4.00, z=64.49]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-189,4,63), Chunk: (at 3,0,15 in -12,3; contains blocks -192,0,48 to -177,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3552 game time, 3552 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['CangyuLin'/134, l='MpServer', x=-180.61, y=4.00, z=64.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.17.2-1-ARCH
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1669960944 bytes (1592 MB) / 2550136832 bytes (2432 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E1 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version                  | Source                                         | Signature                                |
	|:--------- |:-------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2                   | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                     | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | preston              | 0.3.3                    | Preston-0.3.3.jar                              | None                                     |
	| UCHIJAAAA | jei                  | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                      | None                                     |
	| UCHIJAAAA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                     | None                                     |
	| UCHIJAAAA | appliedenergistics2  | rv6-alpha-1              | appliedenergistics2-rv6-alpha-1.jar            | None                                     |
	| UCHIJAAAA | aquaculture          | 1.6.1                    | Aquaculture-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | morphtool            | 1.2-16                   | Morph-o-Tool-1.2-16.jar                        | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-18                   | AutoRegLib-1.3-18.jar                          | None                                     |
	| UCHIJAAAA | bdlib                | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                   | None                                     |
	| UCHIJAAAA | betterfishing        | 2.0                      | BetterFishing-1.12.2-2.0.jar                   | None                                     |
	| UCHIJAAAA | bookshelf            | 2.3.552                  | Bookshelf-1.12.2-2.3.552.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | buildcraftlib        | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftcore       | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftbuilders   | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftenergy     | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftfactory    | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftrobotics   | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcrafttransport  | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | buildcraftsilicon    | 7.99.17                  | buildcraft-7.99.17.jar                         | None                                     |
	| UCHIJAAAA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| UCHIJAAAA | cookingforblockheads | 6.4.40                   | CookingForBlockheads_1.12.2-6.4.40.jar         | None                                     |
	| UCHIJAAAA | extracells           | 2.5.13                   | ExtraCells-1.12.2-2.5.13a60.jar                | None                                     |
	| UCHIJAAAA | ic2                  | 2.8.16-ex112             | Industrial-Craft-2-Mod-Experimental-1.12.1.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | advgenerators        | 0.9.20.12                | generators-0.9.20.12-mc1.12.2.jar              | None                                     |
	| UCHIJAAAA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar              | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                    | None                                     |
	| UCHIJAAAA | moarfood             | 1.1.2                    | MoarFood-1.1.2.jar                             | None                                     |
	| UCHIJAAAA | moarores             | 1.1.1                    | Moarores-1.1.1.jar                             | None                                     |
	| UCHIJAAAA | mtlib                | 3.0.5                    | MTLib-3.0.5.jar                                | None                                     |
	| UCHIJAAAA | ngtlib               | 2.4.3                    | NGTLib2.4.3-20_forge-1.12.2-14.23.2.2611.jar   | None                                     |
	| UCHIJAAAA | oreexcavation        | 1.4.119                  | OreExcavation-1.4.119.jar                      | None                                     |
	| UCHIJAAAA | projecte             | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar                      | None                                     |
	| UCHIJAAAA | p455w0rdslib         | 2.0.29                   | p455w0rdslib-1.12-2.0.29.jar                   | None                                     |
	| UCHIJAAAA | harvestcraft         | 1.12.2u                  | Pam's+HarvestCraft+1.12.2u.jar                 | None                                     |
	| UCHIJAAAA | poweradapters        | 1.0.9                    | PowerAdapters-1.12.2-1.0.9.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | rtm                  | 2.4.4                    | RTM2.4.4-23_forge-1.12.2-14.23.2.2611.jar      | None                                     |
	| UCHIJAAAA | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                | None                                     |
	| UCHIJAAAA | treechopper          | 1.2.4                    | Tree-Chopper-Mod-1.12.2 (副本).jar               | None                                     |
	| UCHIJAAAA | wanionlib            | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                       | None                                     |
	| UCHIJAAAA | wct                  | 3.9.68                   | WirelessCraftingTerminal-1.12.2-3.9.68 (1).jar | None                                     |
	| UCHIJAAAA | unidict              | 1.12.2-2.5e              | UniDict-1.12.2-2.5e.jar                        | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 396.24' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	AE2 Version: alpha rv6-alpha-1 for Forge 14.23.3.2655
	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-alpha-1.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.68 (1).jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.17.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.17.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.17.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.17.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.11.0.202.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.29.jar
		* projecteapi (1.12.2-1.0.0) from ProjectE-1.12-PE1.3.0.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.68 (1).jar
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 396.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: CoterieCraft32xMC1.12rev14.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX-8370 Eight-Core Processor
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 396.24
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
Singleplayer or multiplayer: Single Player
Steps to reproduce: 
Additional information: 
It broke when I join the world

**Comment by min20120907** [comment]
and I guess it is the conflict between realtrain mod and this mod, because they can exist independently...

**Comment by AlexIIL** [comment]
Can you upload your full client log (I think it's called "latest.log" or something like that) to https://gist.github.com/ and post a link to it back here?

**Comment by min20120907** [comment]
Ok

**Comment by min20120907** [comment]
https://gist.github.com/min20120907/1741701847fe311b1de16a791ac7cd67

**Comment by AlexIIL** [comment]
That's the crash report. I think the log files are stored in the "logs" folder, can you find the latest one that has a crash at the end of it?

**Comment by min20120907** [comment]
Oh, let me search for a whike

**Comment by min20120907** [comment]
While

**Comment by min20120907** [comment]
um...my log is empty...

**Comment by MegaBait163** [comment]
Have the same problem, and yeah, if I delete RealTrainMod all works fine. Only this was in my logs folder 
[latest.log](https://github.com/BuildCraft/BuildCraft/files/2251572/latest.log)
[debug.log](https://github.com/BuildCraft/BuildCraft/files/2251573/debug.log)
