### ISSUE TITLE
buildcraft no sense  Error: java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by PePe-Pe** [BuildCraft/BuildCraft#4260]
BuildCraft version: 7.99.17
Forge version: LiteLoader 1.12.2 with Forge 1.12.2
Singleplayer 
I just get this problem when put buildcraft in the mods folder 

GAME CRASH
![screenshot crash](https://user-images.githubusercontent.com/43116377/45266966-0df40980-b43a-11e8-9e28-5187e0683f91.jpg)

The game crashed whilst generating mipmaps for frame
Error: java.lang.ArithmeticException: / by zero

"crash report"
---- Minecraft Crash Report ----

`---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/9/18 2:07 PM
Description: Generating mipmaps for frame

java.lang.ArithmeticException: / by zero
	at net.minecraft.client.renderer.texture.TextureUtil.func_147949_a(TextureUtil.java:91)
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:487)
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.func_147963_d(AtlasSpriteSwappable.java:130)
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.swapWith(AtlasSpriteSwappable.java:77)
	at buildcraft.lib.client.sprite.AtlasSpriteVariants.reload(AtlasSpriteVariants.java:119)
	at buildcraft.lib.client.sprite.AtlasSpriteVariants.load(AtlasSpriteVariants.java:88)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:213)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_147949_a(TextureUtil.java:91)

-- Frame being iterated --
Details:
	Frame index: 0
	Frame sizes: 64, null, null, null, null
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:487)
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.func_147963_d(AtlasSpriteSwappable.java:130)
	at buildcraft.lib.client.sprite.AtlasSpriteSwappable.swapWith(AtlasSpriteSwappable.java:77)
	at buildcraft.lib.client.sprite.AtlasSpriteVariants.reload(AtlasSpriteVariants.java:119)
	at buildcraft.lib.client.sprite.AtlasSpriteVariants.load(AtlasSpriteVariants.java:88)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:213)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 386279904 bytes (368 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E2 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                        | Signature                                |
	|:----- |:-------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCH   | mcp                  | 9.42         | minecraft.jar                                 | None                                     |
	| UCH   | FML                  | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | buildcraftlib        | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftcore       | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftbuilders   | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftenergy     | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftfactory    | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftrobotics   | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcrafttransport  | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftsilicon    | 7.99.17      | buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | codechickenlib       | 3.1.5.331    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | growthcraft          | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_apples   | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_bamboo   | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_cellar   | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_bees     | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_fishtrap | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_grapes   | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_hops     | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | growthcraft_milk     | 4.0.3.100    | GrowthCraft-Mod-1.12.2.jar                    | None                                     |
	| UCH   | hardcoreore          | 0.1.7b       | Hardcore-ORE-Mod-1.12.2.jar                   | None                                     |
	| UCH   | hardcorearmor        | 0.1.4        | hardcorearmor-1.12.2-0.1.4.jar                | None                                     |
	| UCH   | hardcoretools        | 0.0.5        | hardcoretools-1.12.2-0.0.5.jar                | None                                     |
	| UCH   | ic2                  | 2.8.98-ex112 | industrialcraft-2-2.8.98-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | jei                  | 4.12.0.216   | jei_1.12.2-4.12.0.216.jar                     | None                                     |
	| UCH   | radixcore            | 1.12.x-2.2.1 | RadixCore-1.12.2.jar                          | None                                     |
	| UCH   | mca                  | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
	| UCH   | torohealthmod        | 1.12.2-11    | torohealth-1.12.2-11.jar                      | None                                     |
	| UCH   | of                   | 0.9          | Useful+Interior+-+0.9+[1.12.2].jar            | None                                     |
	| UCH   | wearablebackpacks    | 3.1.3        | WearableBackpacks-1.12.2-3.1.3.jar            | None   `

**Comment by AlexIIL** [comment]
I'm not really sure what could have caused this as the only division in that method is wrapped around a conditional to ensure that it is never 0... so maybe a different mod is changing that method?

Either way can you test without optifine? (Or try disabling mipmaps temporarily?)

**Comment by PePe-Pe** [comment]
without optifine works perfectly. thank you

**Comment by AlexIIL** [comment]
@sp614x do you have any idea what might be going on here? Does optifine replace or change `TextureUtil.generateMipmapData()` in any way? it looks like forge adds a check to avoid a crash like this so might that be related? (Or might this be caused by more than just buildcraft + optifine together?)

(in `TextureUtil.generateMipmapData()`)
````java
if (j > 0) { // FORGE: forcing higher mipmap levels on odd textures needs this check
int k = aint2.length / j; // Assumed crash here
int l = j << 1;
````
