### ISSUE TITLE
Quarry crashes game 

### ISSUE THREAD

**Issue by EpicTurtleMonster** [BuildCraft/BuildCraft#4265]
As soon as my quarry mines a block the game crashes and the world isn't recoverable unless the quarry is deleted with MCEdit. Note that my quarry made it around 20 blocks down before starting to crash, and that it's trying to mine a Lead Ore.

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 9/19/18 12:55 AM
Description: Ticking tile entity

java.lang.NullPointerException
	at buildcraft.core.inventory.InventoryIteratorSided$1.hasNext(InventoryIteratorSided.java:30)
	at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:23)
	at buildcraft.core.inventory.Transactor.add(Transactor.java:15)
	at buildcraft.core.utils.Utils.addToRandomInventoryAround(Utils.java:72)
	at buildcraft.factory.TileQuarry.mineStack(TileQuarry.java:463)
	at buildcraft.factory.TileQuarry.positionReached(TileQuarry.java:431)
	at buildcraft.factory.TileQuarry.moveHead(TileQuarry.java:774)
	at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:158)
	at net.minecraft.world.World.func_72939_s(World.java:2209)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.core.inventory.InventoryIteratorSided$1.hasNext(InventoryIteratorSided.java:30)
	at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:23)
	at buildcraft.core.inventory.Transactor.add(Transactor.java:15)
	at buildcraft.core.utils.Utils.addToRandomInventoryAround(Utils.java:72)
	at buildcraft.factory.TileQuarry.mineStack(TileQuarry.java:463)
	at buildcraft.factory.TileQuarry.positionReached(TileQuarry.java:431)
	at buildcraft.factory.TileQuarry.moveHead(TileQuarry.java:774)
	at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:158)

-- Tile entity being ticked --
Details:
	Name: Machine // buildcraft.factory.TileQuarry
	Block type: ID #519 (tile.machineBlock // buildcraft.factory.BlockQuarry)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-16,62,-34), Chunk: (at 0,3,14 in -1,-3; contains blocks -16,0,-48 to -1,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #519 (tile.machineBlock // buildcraft.factory.BlockQuarry)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2209)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)

-- Affected level --
Details:
	Level name: 9_18
	All players: 1 total; [GCCorePlayerMP['Markiplierfan115'/395, l='9_18', x=-13.05, y=62.75, z=-32.08]]
	Chunk stats: ServerChunkCache: 862 Drop: 0
	Level seed: 1470642794660714131
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-172,64,32), Chunk: (at 4,4,0 in -11,2; contains blocks -176,0,32 to -161,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 458 game time, 458 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 111195 (now: false), thunder time: 89633 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3590654936 bytes (3424 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 6513 (364728 bytes; 0 MB) allocated, 6148 (344288 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 64
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 109 mods loaded, 109 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{6.4.49.965} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{9.11.1.965} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{0.9.0.7} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ImmibisMicroblocks{57.6.3} [Immibis's Microblocks] (immibis-microblocks-57.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.6.1.8} [Not Enough Items] (notenoughitems 1.6.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.4} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PowerCrystalsCore{1.1.8} [PowerCrystals Core] (powercrystalscore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap] ([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{4.2.2} [BuildCraft] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UniversalElectricity{3.1.0} [Universal Electricity] (universal-electricity-3.1.0.66-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CalclaviaCore{1.2.0} [CalclaviaCore] (calclavia core-1.2.0.299-main.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AtomicScience{1.2.0} [Atomic Science] (atomic-science-1.2.0.63-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Autoutils{1.0.1} [Autoutils] (autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{1.28.37} [Backpack] (backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.58} [ComputerCraft] (ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{4.2.2} [BC Builders] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{4.2.2} [BC Energy] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{4.2.2} [BC Factory] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{4.2.2} [BC Transport] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded{1.6.4R2.7.8} [MineFactory Reloaded] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{2.0.0.5} [CoFH Core] (cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.6.2R2.2.2} [Nether Ores] (netherores-2.2.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.0.0.250} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{3.0.0.6} [Thermal Expansion] (thermalexpansion-3.0.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BigReactors{0.3.0A} [Big Reactors] (bigreactors-0.3.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] (bspkrscorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{4.2.2} [BC Silicon] (BUILDCRAFT-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Additional-Buildcraft-Objects{1.0.7.560} [Additional Buildcraft Objects] (buildcraft-Z-additional-buildcraft-objects-1.0.7.560.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{2.0.8} [Carpenter's Blocks] (carpentersblocks v2.0.8 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.3.3} [ChickenChunks] (ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHLoot{2.0.0.5} [CoFH Loot] (cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHSocial{2.0.0.5} [CoFH Social] (cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHWorld{2.0.0.5} [CoFH World] (cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CCTurtle{1.58} [ComputerCraft Turtles] (ComputerCraft1.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ImmibisCore{57.1.94} [Immibis Core] (immibis-core-57.1.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DimensionalAnchors{57.1.95} [Dimensional Anchors] (dimensional-anchor-57.1.95.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	dimdoors{1.6.4-R2.2.3} [Dimensional Doors] (dimensionaldoors-2.2.3-336.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.3.5} [EnderStorage] (EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EE3{0.1} [Equivalent Exchange 3] (equivalentexchange3-1.6.4-0.1.140.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LogisticsPipes|Main{0.7.4.dev.205} [Logistics Pipes] (logisticspipes-mc1.6.4-0.7.4.dev.205.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.2a} [Waila] (waila_1.5.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	extracells{1.6.8f} [ExtraCells] (extracells-1.6.8f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.10.12.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.4} [OpenMods] (openmodslib-0.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.3.7.32} [ProjectRed] (projectredbase-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission] (projectredintegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheralCore{0.3.3} [OpenPeripheralCore] (openperipheralcore-0.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.0.1} [Extra Utilities] (extrautils-1.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{2.0.12} [Galacticraft Core] (galacticraft-1.6.4-2.0.12.1026.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{2.0.12} [Galacticraft Mars] (galacticraft-planets-1.6.4-2.0.12.1026.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GregsLighting{1.9.1} [Greg's Lighting] (GregsLighting-1.9.1-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{5.4.1.697} [Iron Chest] (ironchest-universal-1.6.4-5.4.1.697.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.8} [MFR Compat: Applied Energistics] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAtum{1.6.4R2.7.8} [MFR Compat: Atum] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBackTools{1.6.4R2.7.8} [MFR Compat: BackTools] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.8} [MFR Compat: BuildCraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatChococraft{1.6.4R2.7.8} [MFR Compat: Chococraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.8} [MFR Compat: ExtraBiomes] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForestry{1.6.4R2.7.8} [MFR Compat: Forestry] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.8} [MFR Compat: Forestry (part 2)] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.8} [MFR Compat: ForgeMicroblock] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatIC2{1.6.4R2.7.8} [MFR Compat: IC2] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.8} [MFR Compat: Mystcraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatPams{1.6.4R2.7.8} [MFR Compat: Pam's Mods] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Exploration{4.3.7.32} [ProjectRed-Exploration] (projectredworld-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatProjRed{1.6.4R2.7.8} [MFR Compat ProjectRed] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.8} [MFR Compat: Railcraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRP2{1.6.4R2.7.8} [MFR Compat: RP2] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.8} [MFR Compat: Sufficient Biomes] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.8} [MFR Compat: Thaumcraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.8} [MFR Compat: Thermal Expansion] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.8} [MFR Compat: TwilightForest] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatVanilla{1.6.4R2.7.8} [MFR Compat: Vanilla] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.8} [MFR Compat: XyCraft] (minefactoryreloaded-2.7.8-482.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MFFS{3.6.2} [Modular Force Field System] (modular-force-field-system-3.6.2.56-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	numina{0.1.2-55} [Numina] (numina-1.6.2-0.1.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	powersuits{0.10.0-91} [MachineMuse's Modular Powersuits] (modularpowersuits-1.6.4-0.10.0-91.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIPlugins{1.1.0.6} [NEI Plugins] (neiplugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OCS{1.6.4.1} [OpenCCSensors] (OPENCCSENSORS-1.6.4.1B.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenPeripheral{0.1.3} [OpenPeripheralAddons] (openperipheraladdons-0.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	powersuitaddons{@VERSION@} [Andrew's Modular Powersuits Addons] (powersuitaddons-1.6.4-884.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bau5_ProjectBench{1.8.0} [Project Bench] (ProjectBench-1.6.2-v1.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation] (projectredmechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Compatibility{4.3.7.32} [ProjectRed-Compatibility] (projectredcompat-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.3.7.32} [ProjectRed-Integration] (projectredintegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination] (projectredlighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion] (projectredmechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	QuantumCraft{1.1} [qCraft] (qcraft1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Redstone Arsenal{1.0.0.0} [Redstone Arsenal] (RedstoneArsenal-1.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JAKJ_RedstoneInMotion{2.3.0.0} [Redstone In Motion] (redstoneinmotion_2.3.0.0_mc1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{0.1.4} [Simply Jetpacks] (simplyjetpacks-0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StevesCarts{2.0.0.b10} [Steve's Carts 2] (stevescarts2.0.0.b10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	tradeboothmod{0.6.4.2} [Trade Booth Mod] (tradebooth.0.6.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TreeCapitator{Forge 1.6.4.r09} [Treecapitator] (TREECAPITATOR.FORGE.1.6.4.R09.UNIVERSAL.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Vending{1.1.1} [Vending] (vending-1.6.4-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{1.6.2 v1.13.5} [Balkon's WeaponMod] (WeaponMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WR-CBE|Core{1.4.0.6} [WR-CBE Core] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WR-CBE|Addons{1.4.0.6} [WR-CBE Addons] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WR-CBE|Logic{1.4.0.6} [WR-CBE Logic] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.0.0.250} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.0.0.250} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 1717 (96152 bytes; 0 MB) allocated, 1487 (83272 bytes; 0 MB) used
	Player Count: 1 / 8; [GCCorePlayerMP['Markiplierfan115'/395, l='9_18', x=-13.05, y=62.75, z=-32.08]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by asiekierka** [comment]
But what is the quarry connected to?

**Comment by EpicTurtleMonster** [comment]
the quarry is connected to a Nuclear Reactor. Also in messing with it I lost the world, and I didn't have a backup, so the whole point is moot, but if I messed something up I'd love to know so I don't do it again.
