### ISSUE TITLE
[1.12.2] Crash BCBuildersEventDist

### ISSUE THREAD

**Issue by bigenergy** [BuildCraft/BuildCraft#4294]
BuildCraft version: 7.99.18
Forge version: 14.23.5.2772
Link to crash report or log: https://pastebin.com/B0RTLfeq
Singleplayer or multiplayer: both
Steps to reproduce: unknown..

**Comment by scagood** [comment]
Have you tried the same mods and configs on a vanilla server?

Maybe similar to #4225 -- But someone may need to check that one :)

Error:
```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at buildcraft.builders.BCBuildersEventDist.onGetCollisionBoxesForQuarry(BCBuildersEventDist.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_492_BCBuildersEventDist_onGetCollisionBoxesForQuarry_GetCollisionBoxesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641)
	at net.minecraft.world.World.func_184144_a(World.java:1390)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:657)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1951)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2386)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zio000(NetHandlerPlayServer.java:2050)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```
Stacktrace:
```
	at buildcraft.builders.BCBuildersEventDist.onGetCollisionBoxesForQuarry(BCBuildersEventDist.java:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_492_BCBuildersEventDist_onGetCollisionBoxesForQuarry_GetCollisionBoxesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641)
	at net.minecraft.world.World.func_184144_a(World.java:1390)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:657)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1951)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2386)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zio000(NetHandlerPlayServer.java:2050)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
```

**Comment by AEnterprise** [comment]
this could also just be the server being laggy in general, in 1.12 having a general laggy world then then watchdog will kill it much sooner then it's supposed to
https://bugs.mojang.com/browse/MC-121586

**Comment by bigenergy** [comment]
Not fixed, close...
