### ISSUE TITLE
NPE SpriteFluidFrozen

### ISSUE THREAD

**Issue by The28AWG** [BuildCraft/BuildCraft#4354]
BuildCraft version: 7.99.21
Forge version: 1.12.2-forge1.12.2-14.23.5.2811
Link to crash report or log: https://pastebin.com/BEZJ0hSh
Singleplayer or multiplayer: --
Steps to reproduce: crash in start
Additional information: --

**Comment by The28AWG** [comment]
Hm...
If remove bytedrives and appliedintegrations game not crashed.
If remove only buildcraft crash error:

> java.lang.IllegalArgumentException: Location cannot be null!
> 	at net.minecraft.client.renderer.texture.TextureMap.func_174942_a(TextureMap.java:707)
> 	at java.lang.Iterable.forEach(Iterable.java:75)
> 	at net.minecraftforge.client.model.ModelLoader.lambda$setupModelRegistry$0(ModelLoader.java:159)

Its not buildcraft bug.
Я не знаю почему buildcraft так реагирует на ошибки из других модов.
