### ISSUE TITLE
Incomplete owner error | 1.12.2

### ISSUE THREAD

**Issue by trunkyredstone** [BuildCraft/BuildCraft#4473]
- Forge Version: 1.12.2 - 14.23.5.2768
 - BuildCraft Version (Add Hash if from github): 7.99.24.2
 **Aditional Mods*
- Micdoodle8 Core
- Moving world Core
- Biomes O' Plenty
- Carpenter's Blocks
- code chicken lib
- CC; tweaked 
- davinci's vessels
- mantle
- JEI
- Tinker's Construct
- Galacticraft core
- ^ planets
- inventory tweaks
-  journey map
- nei
- bspkrs core
- treecapitator
- What are we looking at

**To Reproduce**
1. Go to a world
2. Place down a fluid pipe or machine (i tested pump) 
3. Notice how pipes dont connect
4. See error in launcher :

```
[09:19:01] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Incomplete owner! ( GCEntityPlayerMP[''/2007, l='New World', x=-107.84, y=63.00, z=142.38] -> com.mojang.authlib.GameProfile@700387f[id=fc5bc365-aedf-30a8-8b89-04e462e29bde,name=,properties={},legacy=false] )
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Incomplete owner! ( GCEntityPlayerMP[''/2007, l='New World', x=-107.84, y=63.00, z=142.38] -> com.mojang.authlib.GameProfile@700387f[id=fc5bc365-aedf-30a8-8b89-04e462e29bde,name=,properties={},legacy=false] )
	at buildcraft.lib.tile.TileBC_Neptune.onPlacedBy(TileBC_Neptune.java:316) ~[TileBC_Neptune.class:?]
	at buildcraft.transport.tile.TilePipeHolder.onPlacedBy(TilePipeHolder.java:178) ~[TilePipeHolder.class:?]
	at buildcraft.lib.block.BlockBCTile_Neptune.func_180633_a(BlockBCTile_Neptune.java:66) ~[BlockBCTile_Neptune.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186) ~[ahb.class:?]
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[ahb.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:876) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:481) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 5 more
```

**Comment by AlexIIL** [comment]
That's odd, for some reason your profile doesn't have a name? I'm not sure if this is a bug with galacticraft or not because no-one else has reported this?

**Comment by AlexIIL** [comment]
Either way this is still something that I can fix in buildcraft...

**Comment by simon816** [comment]
The player UUID `fc5bc365-aedf-30a8-8b89-04e462e29bde` is not a valid player (Mojang API returns `204 No Content` when querying it).

**Comment by trunkyredstone** [comment]
Yeah I use cracked. Didn't realise this would affect the mod

**Comment by trunkyredstone** [comment]
This should be it
