### ISSUE TITLE
Game startup error

### ISSUE THREAD

**Issue by Kevin19281** [BuildCraft/BuildCraft#4485]
https://paste.dimdev.org/vevapuralo.mccrash

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2019-09-14 00:33:11 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)
Caused by: java.lang.IllegalStateException: Scanning facade states
    State = minecraft:double_stone_slab[seamless=false,variant=quartz]
    Block = minecraft:double_stone_slab
    Stack = 1xtile.stoneSlab@7
    varying-properties: {
        PropertyBool{name=seamless, clazz=class java.lang.Boolean, values=[true, false]} = null
    }
    at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:354)
    at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:213)
    at buildcraft.silicon.BCSilicon.init(BCSilicon.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.block.Block.handler$isFullBlock$zdg000(Block.java:3202)
    at net.minecraft.block.Block.isFullBlock(Block.java)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isFullBlock(BlockStateContainer.java:307)
    at net.minecraft.block.Block.isSideSolid(Block.java:1071)
    at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.optifine.reflect.Reflector.callBoolean(Reflector.java:848)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:519)
    at buildcraft.silicon.plug.FacadeBlockStateInfo.<init>(FacadeBlockStateInfo.java:41)
    at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:319)
    ... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 265288680 bytes (252 MB) / 1342177280 bytes (1280 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 56 mods loaded, 56 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                     | Version                  | Source                                            | Signature                                |
       |:----- |:---------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft              | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHI  | mcp                    | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHI  | FML                    | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                  | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | aether_legacy          | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                   | None                                     |
       | LCHI  | akashictome            | 1.2-12                   | AkashicTome-1.2-12.jar                            | None                                     |
       | LCHI  | jei                    | 4.15.0.268               | jei_1.12.2-4.15.0.268 (2).jar                     | None                                     |
       | LCHI  | appleskin              | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | LCHI  | aroma1997core          | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHI  | aromabackup            | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHI  | aromabackuprecovery    | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHI  | autoreglib             | 1.3-32                   | AutoRegLib-1.3-32.jar                             | None                                     |
       | LCHI  | baubles                | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
       | LCHI  | betteranimalsplus      | 7.1.0                    | betteranimalsplus-1.12.2-7.1.0.jar                | None                                     |
       | LCHI  | betterbuilderswands    | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
       | LCHI  | buildcraftlib          | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCHI  | buildcraftcore         | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCHI  | buildcraftbuilders     | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCHI  | buildcrafttransport    | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCHE  | buildcraftsilicon      | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCH   | buildcraftcompat       | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCH   | buildcraftenergy       | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCH   | buildcraftfactory      | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCH   | buildcraftrobotics     | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                      | None                                     |
       | LCH   | chesttransporter       | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                 | None                                     |
       | LCH   | codechickenlib         | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | chickenchunks          | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | forgelin               | 1.8.4                    | Forgelin-1.8.4.jar                                | None                                     |
       | LCH   | chickendropfeathersmod | 1.0                      | ChickenDropFeathers-1.0.jar                       | None                                     |
       | LCH   | controlling            | 3.0.7                    | Controlling-3.0.7.jar                             | None                                     |
       | LCH   | cosmeticarmorreworked  | 1.12.2-v4a               | CosmeticArmorReworked-1.12.2-v4a.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | doggytalents           | 1.15.1.4                 | DoggyTalents-1.12.2-1.15.1.4-universal.jar        | None                                     |
       | LCH   | elevatorid             | 1.3.11                   | ElevatorMod-1.12.2-1.3.11.jar                     | None                                     |
       | LCH   | enderstorage           | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | mantle                 | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
       | LCH   | tconstruct             | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
       | LCH   | extrautils2            | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
       | LCH   | fastleafdecay          | v14                      | FastLeafDecay-v14.jar                             | None                                     |
       | LCH   | cfm                    | 6.3.1                    | furniture-6.3.1-1.12.2.jar                        | None                                     |
       | LCH   | waila                  | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCH   | inventorytweaks        | 1.63+release.109.220f184 | InventoryTweaks-1.63 (2).jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | journeymap             | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                       | None                                     |
       | LCH   | jeresources            | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
       | LCH   | lumberjack             | 1.4.1                    | lumberjack-1.4.1.jar                              | None                                     |
       | LCH   | morpheus               | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
       | LCH   | naturescompass         | 1.5.1                    | NaturesCompass-1.12.2-1.5.1 (1).jar               | None                                     |
       | LCH   | neat                   | 1.4-17                   | Neat+1.4-17.jar                                   | None                                     |
       | LCH   | norecipebook           | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                | None                                     |
       | LCH   | flammpfeil.slashblade  | mc1.12-r28               | SlashBlade-mc1.12-r28.jar                         | None                                     |
       | LCH   | slashbladetic          | V1.0.9.2-MC1.12.2        | SlashBladeTic-V1.0.9.2-MC1.12.2.jar               | None                                     |
       | LCH   | tinkertoolleveling     | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
       | LCH   | vanillafix             | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCH   | waystones              | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                       | None                                     |
       | LCH   | worldedit              | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
       | LCH   | xlfoodmod              | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                      | None                                     |
       | LCH   | reauth                 | 3.6.0                    | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
  Loaded coremods (and transformers): RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63 (2).jar)
                                        invtweaks.forge.asm.ContainerTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13570 Compatibility Profile Context 19.7.2 26.20.13001.16003' Renderer: 'Radeon RX Vega'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Suspected Mods: BuildCraft Builders (buildcraftbuilders), BuildCraft Factory (buildcraftfactory), BuildCraft Energy (buildcraftenergy), BuildCraft Transport (buildcrafttransport), BuildCraft Robotics (buildcraftrobotics), BuildCraft (buildcraftcore), BuildCraft Silicon (buildcraftsilicon), BuildCraft Compat (buildcraftcompat), BuildCraft Lib (buildcraftlib)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: Radeon RX Vega GL version 4.6.13570 Compatibility Profile Context 19.7.2 26.20.13001.16003, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x AMD Ryzen 5 1600 Six-Core Processor

**Comment by AlexIIL** [comment]
It looks like the version of optifine you're using is incompatible with buildcraft's facades - you can either try downgrading optifine, or disabling facades in buildcraft's objects.cfg configuration file.

**Comment by Kevin19281** [comment]
Alright thank you
