### ISSUE TITLE
"Already tessalating" crash

### ISSUE THREAD

**Issue by Aspenpaw** [BuildCraft/BuildCraft#4498]
I get this from time to time and it really gets to me. Sometimes it might not happen at all, sometimes it will happen a minute after I start the game. anyway, through the crash report I pinpointed the block causing it: a water pump. I don't know why this is causing a problem, but I really need it fixed.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 16/10/19 5:18 PM
Description: Rendering entity in world

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:394)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:384)
	at buildcraft.core.lib.render.RenderEntityBlock.renderBlock(RenderEntityBlock.java:203)
	at buildcraft.core.lib.render.RenderEntityBlock.doRenderBlock(RenderEntityBlock.java:191)
	at buildcraft.core.lib.render.RenderEntityBlock.func_76986_a(RenderEntityBlock.java:142)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:313)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:291)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:264)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:737)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1712)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:394)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:384)
	at buildcraft.core.lib.render.RenderEntityBlock.renderBlock(RenderEntityBlock.java:203)
	at buildcraft.core.lib.render.RenderEntityBlock.doRenderBlock(RenderEntityBlock.java:191)
	at buildcraft.core.lib.render.RenderEntityBlock.func_76986_a(RenderEntityBlock.java:142)

-- Entity being rendered --
Details:
	Entity Type: null (buildcraft.core.lib.EntityBlock)
	Entity ID: 51
	Entity Name: unknown
	Entity's Exact location: 408.25, 61.00, 1373.25
	Entity's Block location: World: (408,61,1373), Chunk: (at 8,3,13 in 25,85; contains blocks 400,0,1360 to 415,255,1375), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Entity's Momentum: 0.00, 0.00, 0.00

-- Renderer details --
Details:
	Assigned renderer: buildcraft.core.lib.render.RenderEntityBlock@7f637ad1
	Location: -9.26,-4.62,-20.02 - World: (-10,-5,-21), Chunk: (at 6,-1,11 in -1,-2; contains blocks -16,0,-32 to -1,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 0.0
	Delta: 0.14363682
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:313)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:291)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:264)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:737)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1712)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['****'/228, l='MpServer', x=417.51, y=65.62, z=1393.27]]
	Chunk stats: MultiplayerChunkCache: 95, 95
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-23700,64,13476), Chunk: (at 12,4,4 in -1482,842; contains blocks -23712,0,13472 to -23697,255,13487), Region: (-47,26; contains chunks -1504,832 to -1473,863, blocks -24064,0,13312 to -23553,255,13823)
	Level time: 13542757 game time, 122978 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 18 total; [EntityCartChest['entity.MinecartChest.name'/256, l='MpServer', x=509.66, y=29.69, z=1379.69], EntityCartChest['entity.MinecartChest.name'/257, l='MpServer', x=502.50, y=32.85, z=1380.50], EntityCartChest['entity.MinecartChest.name'/258, l='MpServer', x=500.50, y=32.85, z=1388.50], EntityCartChest['entity.MinecartChest.name'/259, l='MpServer', x=465.50, y=22.69, z=1455.50], EntityCartChest['entity.MinecartChest.name'/260, l='MpServer', x=456.50, y=21.85, z=1469.50], EntityCartChest['entity.MinecartChest.name'/261, l='MpServer', x=461.50, y=25.69, z=1461.91], EntityCartChest['entity.MinecartChest.name'/262, l='MpServer', x=512.50, y=33.85, z=1408.50], EntityCartChest['entity.MinecartChest.name'/263, l='MpServer', x=542.50, y=29.85, z=1366.50], EntityCartChest['entity.MinecartChest.name'/264, l='MpServer', x=551.50, y=37.85, z=1439.50], GCEntityClientPlayerMP['*'/228, l='MpServer', x=417.51, y=65.62, z=1393.27], EntityItem['item.tile.gcBlockCore.decoblock1'/229, l='MpServer', x=418.47, y=63.13, z=1384.78], EntityItem['item.tile.dirt.default'/230, l='MpServer', x=417.88, y=61.13, z=1385.69], EntityItem['item.item.snowball'/233, l='MpServer', x=422.13, y=64.13, z=1379.31], EntityBlock['unknown'/51, l='MpServer', x=408.25, y=61.00, z=1373.25], EntityCartChest['entity.MinecartChest.name'/252, l='MpServer', x=461.50, y=9.85, z=1418.50], EntityCartChest['entity.MinecartChest.name'/253, l='MpServer', x=473.50, y=19.85, z=1420.50], EntityCartChest['entity.MinecartChest.name'/254, l='MpServer', x=412.50, y=19.85, z=1448.50], EntityCartChest['entity.MinecartChest.name'/255, l='MpServer', x=480.50, y=25.85, z=1417.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 750203224 bytes (715 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 103
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_E7 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	OpenComputers|Core{1.7.4.1265} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJA	securitycraft{v1.8.12} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.12.jar) 
	UCHIJA	bis{3.1.5} [Back in Slime Mod] (Back+in+Slime-1.7.10-3.1.5.jar) 
	UCHIJA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJA	BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(19jun17).jar) 
	UCHIJA	dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
	UCHIJA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-jrddunbr-1.15.2.jar) 
	UCHIJA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJA	gwycraft{0.1.10} [GwyCraft] (gwycraft-mc1710-0.1.10.jar) 
	UCHIJA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJA	OpenComputers{1.7.4.1265} [OpenComputers] (OpenComputers-MC1.7.10-1.7.4.1265-universal.jar) 
	UCHIJA	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCHIJA	Railcraft{9.12.2.1} [Railcraft] (Railcraft_1.7.10-9.12.2.1.jar) 
	UCHIJA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJA	JAKJ_RedstoneInMotion{2.8.9} [Remain In Motion] (RemainInMotion-2.8.9.jar) 
	UCHIJA	tc{4.3.2_009} [Traincraft] (Traincraft-4.3.2_009.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GT 710/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 430.86
	OpenGlRenderer: GeForce GT 710/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by AEnterprise** [comment]
could you try without optifine?

**Comment by MrSliTraP2716Lua** [comment]
java.lang.IllegalStateException: Not tesselating! - similar offset to NV 552
