### ISSUE TITLE
Quarry Crash

### ISSUE THREAD

**Issue by sci4me** [BuildCraft/BuildCraft#4520]
Here's the main relevant bit of the log:
```
java.lang.NullPointerException: Ticking entity
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at buildcraft.builders.BCBuildersEventDist.onGetCollisionBoxesForQuarry(BCBuildersEventDist.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_797_BCBuildersEventDist_onGetCollisionBoxesForQuarry_GetCollisionBoxesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_184144_a(World.java:1393)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:721)
	at net.minecraft.client.entity.EntityPlayerSP.func_70091_d(EntityPlayerSP.java:1054)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1819)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
And here's the full crash report: https://gist.github.com/sci4me/d98bf799c517486f7cc2ae2b8a8fdc42

Minecraft: 1.12.2
Forge: 14.23.5.2847
Buildcraft: 7.99.24.2

**Comment by AlexIIL** [comment]
I think this has been fixed in the prerelease version [7.99.24.6-pre.2](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.24.6-pre.2/buildcraft-all-7.99.24.6-pre.2.jar) from the [tests page](https://mod-buildcraft.com/pages/tests.html), can you try that?
