### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aryan4441** [BuildCraft/BuildCraft#4536]
Sorry how can i remove universal-electricity-4.0.0.1-dev.jar

**Comment by AlexIIL** [comment]
Can you find and upload your crash report? That should tell us exactly what the problem is

**Comment by aryan4441** [comment]
Ok sorry

**Comment by aryan4441** [comment]
When i lunch minecraft in the end of loading it crashs my version is 1.12.2

**Comment by aryan4441** [comment]
I know that its because of my universal-electricity-4.0.0.1-dev.jar

**Comment by aryan4441** [comment]
Because I read the issues and you said that its your universal-electricity-4.0.0.1-dev.jar

**Comment by AlexIIL** [comment]
Ok. What are you using to launch minecraft? The vanilla launcher, or something else?

**Comment by aryan4441** [comment]
Team xtream

**Comment by AlexIIL** [comment]
...oh. In which care I'm not sure, but you'd need to find your "mods" folder and find the `universal-electricity-4.0.0.1-dev.jar` inside of it (and then delete it)

**Comment by aryan4441** [comment]
Wow thank you so much you are great👌

**Comment by aryan4441** [comment]
Sorry something else if I delete that and it doesn't open i should send you my crash report

**Comment by AlexIIL** [comment]
Uploading the crash report will probably be quickest?

**Comment by aryan4441** [comment]
Ok i will

**Comment by aryan4441** [comment]
Actually I don't have universal-electricity-4.0.0.1-dev.jar 😅

**Comment by aryan4441** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/6/20 10:44 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at com.stc.pattysmoretools.blocks.BlockOre.getSpecialName(BlockOre.java:163)
	at com.stc.pattysmoretools.blocks.ItemBlockVariants.func_77667_c(ItemBlockVariants.java:18)
	at net.minecraft.item.Item.func_77657_g(Item.java:292)
	at net.minecraft.item.Item.func_77653_i(Item.java:362)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at buildcraft.silicon.item.ItemPluggableFacade.getFacadeStateDisplayName(ItemPluggableFacade.java:152)
	at buildcraft.silicon.item.ItemPluggableFacade.func_77653_i(ItemPluggableFacade.java:143)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 404757496 bytes (386 MB) / 1097150464 bytes (1046 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                  | Version         | Source                             | Signature                                |
	|:------- |:------------------- |:--------------- |:---------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft           | 1.12.2          | minecraft.jar                      | None                                     |
	| LCHIJA  | mcp                 | 9.42            | minecraft.jar                      | None                                     |
	| LCHIJA  | FML                 | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar      | None                                     |
	| LCHIJAE | forge               | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar      | None                                     |
	| LCHIJA  | atum                | 2.0.16          | Atum-1.12.2-2.0.16.jar             | None                                     |
	| LCHIJA  | battletowers        | 1.6.4           | BattleTowers-Mod-1.12.2.jar        | None                                     |
	| LCHIJA  | bibliocraft         | 2.4.5           | BiblioCraft-Mod-1.12.2.jar         | None                                     |
	| LCHIJA  | bookshelf           | 2.3.585         | Bookshelf-1.12.2.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | buildcraftlib       | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftcore      | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftbuilders  | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcrafttransport | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftsilicon   | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftcompat    | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftenergy    | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftfactory   | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | buildcraftrobotics  | 7.99.24.5-pre.1 | buildcraft-all-7.99.24.5-pre.1.jar | None                                     |
	| LCHIJA  | corerm              | 1.3.3           | RikMuldsCore-1.12.2.jar            | None                                     |
	| LCHIJA  | camping             | 2.4.3           | Camping-Mod-1.12.2.jar             | None                                     |
	| LCHIJA  | damageindicatorsmod | 1.0             | Damage-Indicators-Mod-1.12.2.jar   | None                                     |
	| LCHIJA  | eplus               | 5.0.176         | Enchanting-Plus-Mod-1.12.2.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA  | cfm                 | 6.3.1           | furniture-6.3.1-1.12.2.jar         | None                                     |
	| LCHIJA  | ichunutil           | 7.2.2           | iChun-Util-Mod-1.12.2.jar          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA  | jei                 | 4.15.0.293      | jei_1.12.2-4.15.0.293.jar          | None                                     |
	| LCHIJA  | keepinginventory    | 2.4             | KeepingInventory-1.12.2-2.4.jar    | None                                     |
	| LCHIJA  | mo_swords           | v4              | MoSwords-Mod-1.12.2.jar            | None                                     |
	| LCHIJA  | pattysmoretools     | 1.12.2-1.7      | PattysMoreTools-2-Mod-1.12.2.jar   | None                                     |
	| LCHIJA  | radixcore           | 1.12.x-2.2.1    | RadixCore-1.12.2.jar               | None                                     |
	| LCHIJA  | tropicraft          | 7.1.9.115       | Tropicraft-Mod-1.12.2.jar          | None                                     |
	| LCHIJA  | twilightforest      | 3.9.888         | Twilight-Forest-Mod-1.12.2.jar     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.57' Renderer: 'GeForce 610M/PCIe/SSE2'

**Comment by aryan4441** [comment]
This is my crash report

**Comment by AlexIIL** [comment]
Ah ok, in which case this is a completely different issue - and it's a bug with `pattysmoretools` - you'd need to open an issue up with them instead.

**Comment by aryan4441** [comment]
You mean that i should delete pattysmoretools

**Comment by AlexIIL** [comment]
That would make it launch, yes

**Comment by aryan4441** [comment]
Sorry i should add something else when i delete buildcraft my minecraft lunch correctly but when i add buildcraft it crashs☹️

**Comment by aryan4441** [comment]
Oh thank you so much for your suggestions it is working very well
