### ISSUE TITLE
Crashed server once quarry started,ist here a way to fix

### ISSUE THREAD

**Issue by Totti51091** [BuildCraft/BuildCraft#4539]
[16:39:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
at buildcraft.transport.net.MessageMultiPipeItem.(MessageMultiPipeItem.java:130) ~[MessageMultiPipeItem.class:?]
at buildcraft.transport.net.PipeItemMessageQueue.lambda$appendTravellingItem$1(PipeItemMessageQueue.java:48) ~[PipeItemMessageQueue.class:?]
at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_232]
at buildcraft.transport.net.PipeItemMessageQueue.appendTravellingItem(PipeItemMessageQueue.java:48) ~[PipeItemMessageQueue.class:?]
at buildcraft.transport.pipe.flow.PipeFlowItems.sendItemDataToClient(PipeFlowItems.java:155) ~[PipeFlowItems.class:?]
at buildcraft.transport.pipe.flow.PipeFlowItems.onItemReachCenter(PipeFlowItems.java:392) ~[PipeFlowItems.class:?]
at buildcraft.transport.pipe.flow.PipeFlowItems.onTick(PipeFlowItems.java:299) ~[PipeFlowItems.class:?]
at buildcraft.transport.pipe.Pipe.onTick(Pipe.java:251) ~[Pipe.class:?]
at buildcraft.transport.tile.TilePipeHolder.update(TilePipeHolder.java:243) ~[TilePipeHolder.class:?]
at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38) ~[McHooks.class:?]
at net.minecraft.world.World.updateEntities(World.java:1835) ~[amu.class:?]
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
at buildcraft.transport.net.MessageMultiPipeItem.(MessageMultiPipeItem.java:130) ~[MessageMultiPipeItem.class:?]
at buildcraft.transport.net.PipeItemMessageQueue.lambda$appendTravellingItem$1(PipeItemMessageQueue.java:48) ~[PipeItemMessageQueue.class:?]
at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_232]
at buildcraft.transport.net.PipeItemMessageQueue.appendTravellingItem(PipeItemMessageQueue.java:48) ~[PipeItemMessageQueue.class:?]
at buildcraft.transport.net.PipeItemMessageQueue.lambda$appendTravellingItem$1(PipeItemMessageQueue.java:48) ~[PipeItemMessageQueue.class:?]
at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_232]
at buildcraft.transport.net.PipeItemMessageQueue.appendTravellingItem(PipeItemMessageQueue.java:48) ~[PipeItemMessageQueue.class:?]
at buildcraft.transport.pipe.flow.PipeFlowItems.sendItemDataToClient(PipeFlowItems.java:155) ~[PipeFlowItems.class:?]
at buildcraft.transport.pipe.flow.PipeFlowItems.onItemReachCenter(PipeFlowItems.java:392) ~[PipeFlowItems.class:?]
at buildcraft.transport.pipe.flow.PipeFlowItems.onTick(PipeFlowItems.java:299) ~[PipeFlowItems.class:?]
at buildcraft.transport.pipe.Pipe.onTick(Pipe.java:251) ~[Pipe.class:?]
at buildcraft.transport.tile.TilePipeHolder.update(TilePipeHolder.java:243) ~[TilePipeHolder.class:?]
at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38) ~[McHooks.class:?]
at net.minecraft.world.World.updateEntities(World.java:1835) ~[amu.class:?]
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
... 4 more
[16:39:35] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/service/./crash-reports/crash-2020-03-21_16.39.35-server.txt
[16:39:35] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[16:39:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[16:39:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[16:39:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'BIOMESOP'/overworld
[16:39:36] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 0
[16:39:37] [Server thread/INFO] [FML]: Unloading dimension 0
[16:39:37] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[16:39:37] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server

**Comment by AlexIIL** [comment]
Yes, update BC to 7.99.24.1 or later - I'd recommend 7.99.24.4 ATM, because 7.99.24.5 has a quarry bug that's fixed in the (unreleased) [7.99.24.6-pre.2](https://mod-buildcraft.com/pages/tests.html).

(At least I'm assuming you're using 7.99.24(.0) as this was fixed in 7.99.24.1)
