### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NeonNobility** [BuildCraft/BuildCraft#4558]
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/15/20 2:35 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Lbuildcraft/energy/worldgen/BiomeGenOilDesert;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: Lbuildcraft/energy/worldgen/BiomeGenOilDesert;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at cpw.mods.fml.common.FMLModContainer.parseSimpleFieldAnnotation(FMLModContainer.java:404)
	at cpw.mods.fml.common.FMLModContainer.processFieldAnnotations(FMLModContainer.java:358)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:513)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more
Caused by: java.lang.ClassNotFoundException: buildcraft.energy.worldgen.BiomeGenOilDesert
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/biome/BiomeGenDesert
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 35 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenDesert
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.0-1062.18.1.el7.x86_64
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 684859688 bytes (653 MB) / 1284505600 bytes (1225 MB) up to 3728736256 bytes (3556 MB)
	JVM Flags: 2 total; -Xmx4000M -Xms128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 207 mods loaded, 206 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UC	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UC	additionalresources{0.0.2} [Additional Resources] (additionalresources-1.7.10_0.1.0.unknown.jar) 
	UC	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	gasesCore{1.6.7} [Glenn's Gases Core] (minecraft.jar) 
	UC	gasesFrameworkCore{1.2.4} [Gases Framework Core] (minecraft.jar) 
	UC	infinitefluids{1.0.1} [InfiniteFluids] (minecraft.jar) 
	UC	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UC	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UC	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UC	technomCore{0.12.5} [Technomancy Core] (minecraft.jar) 
	UC	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	dynamicswordskills{1.7.10-1.7.1} [Dynamic Sword Skills] (1.7.10-DynamicSwordSkills-1.7.1.jar) 
	UC	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UC	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UC	Backpack{2.0.1} [Backpack] (122_Backpacks-Mod.jar) 
	UC	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10]+SecurityCraft+v1.8.13.jar) 
	UC	movillages{1.4.2} [Mo' Villages] ([1.7.10]MoVillages-1.4.2.jar) 
	UC	TorchBowMod{1.7} [TorchBowMod] ([1.7.10]TorchBowMod_v1.7.jar) 
	UE	abyssalcraft{1.9.1.3} [AbyssalCraft] (AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
	UE	acintegration{1.4.7} [AbyssalCraft Integration] (AbyssalCraft+Integration-1.7.10-1.4.7.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UC	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UC	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UE	BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar) 
	UC	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UC	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UE	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UC	arcanearteries{5} [Arcane Arteries] (ArcaneArteries0.8.2.jar) 
	UC	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (Archimedes-Ships-Mod-1.7.10.jar) 
	UC	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-399.jar) 
	UC	wizardry{1.1.5} [Electroblob's Wizardry] (Electroblob's+Wizardry+-+1.1.5+-+MC+1.7.10.jar) 
	UC	aef{0.0.1} [Art's Effect Pack] (ArtsEffectsSpellPack.jar) 
	UC	barkifier{0.5} [Barkifier] (Barkifier_v0.5.jar) 
	UE	BetterArcheryReborn{0.0} [Better Archery Reborn] (Better-Archery-Mod-1.7.10.jar) 
	UC	binocular{1.2} [Binocular] (binocular-1.7.10-1.2.jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UC	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UC	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UC	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UC	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UC	BloodArsenal{1.2-5} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-5.jar) 
	UC	bonetorch{0.0.1.20151209052122} [Bone Torch Mod] (BoneTorch-1.7.10-0.0.1b1-universal.jar) 
	UC	Botania{r1.8-249} [Botania] (Botania+r1.8-249.jar) 
	UC	BotaniaVisualizer{1.7.2-1.0a} [BotaniaVisualizer] (BotaniaVisualizer-1.7.2-1.0a.jar) 
	UC	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UC	redgear_core{2.2.2} [Red Gear Core] (RedGearCore-1.7.10-2.2.2.jar) 
	UC	redgear_brewcraft{1.3.3} [Brewcraft] (Brewcraft-1.7.10-1.3.3.jar) 
	UC	speedytoolsmod{2.0.0} [Build Faster Mod] (Build-Faster-Mod-1.7.10.zip) 
	UE	BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar) 
	UE	BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar) 
	UE	BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar) 
	UE	BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar) 
	UE	BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar) 
	UE	BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar) 
	UE	butterflymania{1.3.2} [Butterfly Mania] (butterflymania-1.7.10-1.3.2.jar) 
	UC	CamouflageCreepers{1.4} [Camouflage Creepers] (CamouflageCreepers-1.7.10-1.4.jar) 
	UC	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.1+-+MC+1.7.10.jar) 
	UC	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UC	cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
	UC	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry+1.1.3.jar) 
	UC	CreeperConfetti{1.0} [CreeperConfetti] (CreeperConfetti-1.0.jar) 
	UC	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UC	dualhotbar{1.5} [Dual Hotbar] (Dual-Hotbars-Mod-1.7.10.jar) 
	UC	ElementalMelons{1.7.10-1.2} [Elemental Melons] (ElementalMelons-1.7.10-1.2.jar) 
	UC	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UC	Enchiridion{1.3} [Enchiridion] (Enchiridion+2-1.7.10-2.0.2a.jar) 
	UC	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion+2-1.7.10-2.0.2a.jar) 
	UC	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UC	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UC	enderioaddons{0.10.13} [Ender IO Addons] (EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta.jar) 
	UC	epm{1.8-fixed1 for 1.7.10} [???4Dot_???fSilver's ???2Essence ???aPowder ???2Mod] (epm-v1.8-fixed1-mcv1.7.10.jar) 
	UC	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UE	equivalentenergistics{0.8.3} [Equivalent Energistics] (EquivalentEnergistics-1.7.10-0.8.3.jar) 
	UC	evilcraft{0.9.13} [EvilCraft] (EvilCraft-1.7.10-0.9.13.jar) 
	UC	exnihilo{1.38-53} [Ex Nihilo] (Ex-Nihilo-1.38-53.jar) 
	UC	exastris{MC1.7.10-1.16-36} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-36.jar) 
	UC	excompressum{1.2.0} [Ex Compressum] (excompressum-mc1.7.10-1.2.0.jar) 
	UC	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UC	exparmory{1.4.1} [Expanded Armory] (ExpandedArmory-1.7.10-1.4.1.jar) 
	UC	examplemod{1.0} [examplemod] (Extra-Doors-Mod-1.7.10.jar) 
	UC	extradoors{1.5.1} [Extra Doors] (Extra-Doors-Mod-1.7.10.jar) 
	UC	extrae{1.0} [ExtraE] (ExtraE-1.7.10-1.2.jar) 
	UC	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UC	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UC	ftfloocraft{1.7.10-1.7} [Floocraft] (Floocraft-1.7.10-1.7.jar) 
	UC	forgeendertech{1.7.10-1.9.2.0} [Forge Endertech] (ForgeEndertech-1.7.10-1.9.2.0-build.0061.jar) 
	UC	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UC	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
	UC	Steamcraft{0.29.3} [Flaxbeard's Steam Power] (FSP-1.7.10-0.29.3.jar) 
	UC	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UC	Project_Alchemy{1.0.18} [FullThrottle Alchemist] (FullThrottle_Alchemist-1.7.10-1.0.18a.jar) 
	UC	fullthrottlenei{1.7.10-0.0.8} [FullThrottle NEI] (FullThrottleNEI-1.7.10-0.0.8.jar) 
	UC	gasesFramework{1.2.4} [Gases Framework] (gasesFramework-1.7.10-1.2.4.jar) 
	UC	gases{1.6.7} [Glenn's Gases] (gases-1.7.10-1.6.7.jar) 
	UC	grapplemod{1.7.10-v10} [Grappling hook mod] (grapplemod-1.7.10-v10.jar) 
	UE	Growthcraft{1.7.10-2.7.2} [Growthcraft] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Cellar{1.7.10-2.7.2} [Growthcraft Cellar] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Apples{1.7.10-2.7.2} [Growthcraft Apples] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Bamboo{1.7.10-2.7.2} [Growthcraft Bamboo] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Bees{1.7.10-2.7.2} [Growthcraft Bees] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Fishtrap{1.7.10-2.7.2} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Grapes{1.7.10-2.7.2} [Growthcraft Grapes] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Hops{1.7.10-2.7.2} [Growthcraft Hops] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Milk{1.7.10-2.7.2} [Growthcraft Milk] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UE	Growthcraft|Rice{1.7.10-2.7.2} [Growthcraft Rice] (growthcraft-1.7.10-2.7.2-complete.jar) 
	UC	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UC	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UC	hearts{1.0} [Hearts] (Heart-Crystals-Mod-1.7.10.zip) 
	UC	ImmibisCore{59.1.4} [Immibis Core] (Immibis-Core-1.7.10.jar) 
	UC	infusedring{1.0.4} [Infused Ring Mod] (infusedring-1.7.10-1.0.4.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UC	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.7.10-2.1.jar) 
	UC	lance{2.6.1.1710} [Lance Mod] (Lance-Mod-1.7.10.jar) 
	UC	lovemod{0.1} [Love Mod] (LoveMod-0.1.jar) 
	UC	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UC	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UC	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UC	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UC	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UC	mowziesmobs{1.2.9} [Mowzie's Mobs] (MowziesMobs-1.2.99.jar) 
	UC	MysticalMobs{0.1.1} [Mystical Mobs] (mysticalmobs-0.1.1.jar) 
	UC	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
	UC	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.7.10-1.3.1.jar) 
	UC	necromancy{1.7.2} [Necromancy] (Necromancy-1.7.10.jar) 
	UC	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UC	yurtmod{1.12.1} [Nomadic Tents] (NomadicTents[1.7.10]-1.12.1.jar) 
	UC	NOVA{2015-10-09} [NOVA] (NOVA-2015-10-09-universal.jar) 
	UC	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UC	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UC	clayspawn{1.7.10b} [Pam's Clayspawn] (Pam's+Clay+Spawn+1.7.10b.jar) 
	UC	getalltheseeds{1.7.10a} [Pam's Get all the Seeds!] (Pam's+Get+all+the+Seeds+1.7.10a.jar) 
	UC	mobdropcrops{1.7.2a} [Pam's Mob Drop Crops] (Pam's+Mob+Drop+Crops+1.7.10a.zip) 
	UC	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.2.jar) 
	UC	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UC	packchevsky{b5} [Potion Packs] (PotionPacks_1.7.10_b5.zip) 
	UC	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UC	projectbench{0.5.0} [Project Bench Updated] (ProjectBench-Update-1.7.10-0.5.jar) 
	UC	quantumflux{1.7.10-1.3.4} [QuantumFlux] (QuantumFlux-1.7.10-1.3.4.jar) 
	UC	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UC	rebind{2.7.5} [ReBind] (rebind-1.7.10-2.7.5-0.jar) 
	UC	RedLogic{59.1.13} [RedLogic] (RedLogic-Mod-1.7.10.jar) 
	UC	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UC	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UC	JAKJ_RedstoneInMotion{2.8.9} [Remain In Motion] (RemainInMotion-2.8.9.jar) 
	UC	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UC	RottenFleshToLeather{1.7.10-2.0} [Rotten Flesh to Leather] (RottenFleshToLeather-2.1-1.7.10.jar) 
	UC	runesofwizardry{1.7.10-0.3.1} [Runes of Wizardry] (Runes-of-Wizardry-1.7.10-0.3.1.jar) 
	UE	runicdungeons{1.1.7b} [Runic Dungeons] (RunicDungeons-1.1.7b.jar) 
	UC	Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-35.jar) 
	UC	SanguineExtras{1.3.2} [Sanguine Utilities] (Sanguine+Utilities-1.3.2.jar) 
	UC	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) 
	UC	sereneseasons{1.2.18} [Serene Seasons] (SereneSeasons-1.7.10-1.2.18.jar) 
	UC	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UC	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UC	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UC	smoothbedrock{2.2.0.9} [SmoothBedrock] (Smooth-Bedrock-Mod-1.7.10.jar) 
	UC	SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
	UC	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UC	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UC	Sync{4.0.1} [Sync] (Sync-4.0.1.jar) 
	UC	tinker_io{release 1.5.0} [Tinker I/O] (tinker_io-1.7.10-release+1.5.0.jar) 
	UC	tinkersdefense{1.3.7} [Tinkers' Defense] (tinkersdefense-1.3.7.jar) 
	UC	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UC	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UC	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UC	trueinvisibility{0.3.0} [True Invisibility] (TrueInvisibility-0.3.0-1.7.10.jar) 
	UC	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UC	vampirism{0.7.9} [Vampirism] (Vampirism-1.7.10-0.7.9.jar) 
	UC	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.37.jar) 
	UC	wildcaves3{1.7.10} [Wild Caves 3] (Wild-Caves-Mod-1.7.10.jar) 
	UC	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UC	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	ZDoctorBB{1.2} [Blood Baubles] (ZDoctorBB-1.7.10-Server.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	ExFusile{1.4} [Ex Fusile] (ExFusile-1.4.jar) 
	UC	technom{0.12.5} [Technomancy] (Technomancy+-+0.12.5+-+1.7.10.jar) 
	UC	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	equivalentenergisticsCore{0.8.3} [Equivalent Energistics Core] (minecraft.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: found misbehaving transformers: sereneseasons.asm.transformer.ColorTransformer(sereneseasons.asm.transformer.ColorTransformer@3b74ba96) crashed with java.lang.NullPointerException(null),sereneseasons.asm.transformer.WeatherTransformer(sereneseasons.asm.transformer.WeatherTransformer@74184e1d) crashed with java.lang.NullPointerException(null)
	CoFHCore: -[1.7.10]3.1.4-329
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by NeonNobility** [comment]
I would appreciate help as soon as possible, this server cost a lot of money to setup and I really wanna play with my friends

**Comment by AEnterprise** [comment]
looks like an core BC class is missing, most likely cause is that another mod is shipping classes from BC it shouldn't, or some mod is dependant on an older version of BC

**Comment by asiekierka** [comment]
This issue has not received additional information; it looks like a coremod-related crash to me, but I can't be sure with this information.
