### ISSUE TITLE
Exception ticking world with ICBM-Classic and Crash

### ISSUE THREAD

**Issue by Harchvertelol** [BuildCraft/BuildCraft#4565]
Crash Report or Log: 

My BC: buildcraft-all-7.99.24.6.jar

Adding buildcraft breaks ICBM-Classic.

Link: https://github.com/BuiltBrokenModding/ICBM-Classic/issues/312

**Comment by AEnterprise** [comment]
i'm not sure why you are reporting this here? looking at the linked report there are cases where it crashes without buildcraft?

the stacktrace is pointing to some mod screwing chunks on the wrong thread, my guess is that it's ICBM-classic itself that is doing this, hence why this also happens without buildcraft and with just sponge

**Comment by Harchvertelol** [comment]
Because only these two modes are so influential. It's clear about the sponge - it's a server. And the buildcraft, what does it change in general in processing chunks? Maybe this is the case?

**Comment by AEnterprise** [comment]
buildcraft doesn't change anything at all about chunks or processing them, buildcraft is and does not have a coremod

most likely it's just something that happens when buildcraft requests forge to keep some chunks loaded or so? i don't know and it's quite impossible to determine from just a stacktrace. the trace only tells us that 2 changed the list at the same time but it doesn't identify who the 2nd is at all, or who is the one doing it from the wrong thread

**Comment by AlexIIL** [comment]
It looks like this can happen even without buildcraft: https://github.com/BuiltBrokenModding/ICBM-Classic/issues/295

**Comment by Harchvertelol** [comment]
By reference, the error is not similar to mine. In any case, let's see what the creators of the mod ICBM-Classic.

**Comment by AlexIIL** [comment]
295:
> java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at icbm.classic.lib.radar.RadarMap.collectEntitiesInChunk(RadarMap.java:228)
at icbm.classic.content.entity.missile.MissileEventHandler.chunkUnload(MissileEventHandler.java:43)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_MissileEventHandler_chunkUnload_Unload.invoke(.dynamic)

Yours:
> Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_251]
at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_251]
at icbm.classic.lib.radar.RadarMap.collectEntitiesInChunk(RadarMap.java:228) ~[RadarMap.class:1.12.2-4.0.1b20200328215453]
at icbm.classic.content.entity.missile.MissileEventHandler.chunkUnload(MissileEventHandler.java:43) ~[MissileEventHandler.class:1.12.2-4.0.1b20200328215453]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_MissileEventHandler_chunkUnload_Unload.invoke(.dynamic) ~[?:?]

They look pretty similar to me. Either way it's unlikely that this is related to buildcraft.
