### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Demskillz9955** [BuildCraft/BuildCraft#4566]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2020-04-27 19:03:48 EDT
Description: Ticking block entity

java.lang.NullPointerException
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:844)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:283)
    at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:288)
    at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:272)
    at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_396_CoreEvents_blockBreakEvent_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at buildcraft.lib.misc.BlockUtil.harvestBlock(BlockUtil.java:122)
    at buildcraft.lib.misc.BlockUtil.breakBlockAndGetDrops(BlockUtil.java:220)
    at buildcraft.builders.tile.TileQuarry$TaskBreakBlock.finish(TileQuarry.java:1030)
    at buildcraft.builders.tile.TileQuarry$Task.addPower(TileQuarry.java:944)
    at buildcraft.builders.tile.TileQuarry.update(TileQuarry.java:575)
    at net.minecraft.world.World.redirect$zbe000$tileEntityUpdate(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: buildcraftbuilders:quarry // buildcraft.builders.tile.TileQuarry
  Block type: ID #1581 (tile.quarryBlock // buildcraft.builders.block.BlockQuarry // buildcraftbuilders:quarry)
  Block data value: 1 / 0x1 / 0b0001
  Block location: World: (-182,67,139), Chunk: (at 10,4,11 in -12,8; contains blocks -192,0,128 to -177,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Actual block type: ID #1581 (tile.quarryBlock // buildcraft.builders.block.BlockQuarry // buildcraftbuilders:quarry)
  Actual block data value: 1 / 0x1 / 0b0001
  Block Entity NBT: {owner:{Id:"8c9956d0-59a5-4458-9b54-bc14f73d74ae",Properties:{textures:[{Signature:"AN8RqDbI4iw3OHCrx0U/Zh5xm9B+1Z1/5QCoz47CNlNgC+ZiYVVs08ehi6Y8nc3DST6qaJ3YuyGP5VG/st/9TPY6nV8Jf8DcO569VWfiKI5U/kruNyu8YNRzAKt6v6Hg5qZASX2eVE3Ou8fTX0JCsI/fty+U7dphcq5IpnYw2nLvm32OaG3TrZEyjeO5M97ye0/DJmpoknYgNgTDDLneu3L5V2Wsq+XsVWxHgQizVeICIPHh6C3Ca4IaWAm5ZOk+WyixfzIcmbV52kC/V1wYzqOF69hOPR9l9HBgdw71sMvIjicvou9RZhKrdUEZVQVgXvP9LEd/H/Ns18AOihTAtW89AOx53mtrTAxx8K/Zy8pb95g9TUDJEoWjCS42NamvjtFNM6YNz0HK4Pt+YpVvX23CJOjCQnYszODuV5EC7hyve6p26pVyUnkJBHJRRYhPjuD46Pnq8pYlCF9AGhtyggK7Z4Zk3lpDDAA3AAyANTGDTxPN3MUP31BuzPKDLUv/ZGsM7AR4kqZPYApPGpMoE45k7iULrhsZ8BiqWqZqfbvbf7MXP/WIEEgWFhpZz53XK4xavqe0oiFYIXle1M8elq1fIAjyYdpFQQ/s3uloUd3bCubsJSdZ6uiRV8yvbHo5/hIidJClXGJomz3VaTKbmh6AUZDkRuNkrk0HLGjNCo8=",Value:"eyJ0aW1lc3RhbXAiOjE1ODgwMjgwNzQyMzksInByb2ZpbGVJZCI6IjhjOTk1NmQwNTlhNTQ0NTg5YjU0YmMxNGY3M2Q3NGFlIiwicHJvZmlsZU5hbWUiOiJCaWdfUmVkMDkzMjYiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I5MmU1ZGZjMzA3NmEwOTYwNDk1MTUzYzJmYWU1Y2YwODg4M2NjMjA3YWRmMDQzOTVkNTQ0Mzc4ZTAwZjhmNTQifX19"}]},Name:"Big_Red09326"},currentTaskId:0b,box:{min:[I;-180,0,91],max:[I;-131,70,142]},battery:{stored:511717462L},firstChecked:1b,drillPos:[-169.0d,62.0d,140.0d],boxIterator:{current:[I;-169,62,140],min:[I;-180,0,91],invert:1b,max:[I;-131,70,142],order:{inversion:"NNN",order:"XZY"}},x:-182,y:67,z:139,id:"buildcraftbuilders:quarry",deltas:{},data-version:2,frame:{min:[I;-181,67,90],max:[I;-130,71,143]},currentTaskData:{power:80000000L,breakPos:[I;-169,62,140]}}

-- Affected level --
  Level name: !.12.2 space survival yay
  All players: 1 total; [EntityPlayerMP['Big_Red09326'/412, l='!.12.2 space survival yay', x=-230.44, y=64.00, z=98.79]]
  Chunk stats: ServerChunkCache: 381 Drop: 0
  Level seed: -8135448147399081419
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-224,64,212), Chunk: (at 0,4,4 in -14,13; contains blocks -224,0,208 to -209,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 190168 game time, 190168 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2746126320 bytes (2618 MB) / 4966055936 bytes (4736 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 54 mods loaded, 54 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version              | Source                                               | Signature                                |
       |:------ |:--------------------- |:-------------------- |:---------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2               | minecraft.jar                                        | None                                     |
       | LCHIJA | mcp                   | 9.42                 | minecraft.jar                                        | None                                     |
       | LCHIJA | FML                   | 8.0.99.99            | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
       | LCHIJA | forge                 | 14.23.5.2847         | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
       | LCHIJA | advancedrocketrycore  | 1                    | minecraft.jar                                        | None                                     |
       | LCHIJA | obfuscate             | 0.2.6                | minecraft.jar                                        | None                                     |
       | LCHIJA | forgeendertech        | 1.12.2-4.5.0.0       | ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar         | None                                     |
       | LCHIJA | adlods                | 1.12.2-1.0.7.1       | AdLods-1.12.2-1.0.7.1-build.0441.jar                 | None                                     |
       | LCHIJA | anvilfix              | 1.0.5                | AnvilFix-1.12.2-1.0.5.jar                            | None                                     |
       | LCHIJA | backpack              | 3.0.2                | backpack-3.0.2-1.12.2.jar                            | None                                     |
       | LCHIJA | betterbedrockgen      | 6.0.2                | BetterBedrockGenerator-1.12-6.1.1.jar                | None                                     |
       | LCHIJA | bookshelf             | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | spawnermod            | 1.0-1.12.2           | branders-enhanced-mob-spawners-v1.12.2-1.4.4.jar.jar | None                                     |
       | LCHIJA | buildcraftlib         | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftcore        | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftbuilders    | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcrafttransport   | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftsilicon     | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftcompat      | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftenergy      | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftfactory     | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | buildcraftrobotics    | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCHIJA | chiselsandbits        | 14.33                | chiselsandbits-14.33.jar                             | None                                     |
       | LCHIJA | craftstudioapi        | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar                | None                                     |
       | LCHIJA | customxp              | 1.3                  | customxp-1.3.jar                                     | None                                     |
       | LCHIJA | effortlessbuilding    | 1.12.2-2.16          | effortlessbuilding-1.12.2-2.16.jar                   | None                                     |
       | LCHIJA | eplus                 | 5.0.176              | EnchantingPlus-1.12.2-5.0.176.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enchdesc              | 1.1.15               | EnchantmentDescriptions-1.12.2-1.1.15.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | golems                | 7.1.9                | ExtraGolems-1.12-7.1.9.jar                           | None                                     |
       | LCHIJA | extreme_ores          | 1.0.0                | EXtraOres1.12.2 2.0.0.jar                            | None                                     |
       | LCHIJA | forgelin              | 1.8.3                | Forgelin-1.8.3.jar                                   | None                                     |
       | LCHIJA | llibrary              | 1.7.17               | llibrary-1.7.17-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                | 8.0.4                | fossilsarcheology-8.0.4.jar                          | None                                     |
       | LCHIJA | cgm                   | 0.15.2               | guns-0.15.2-1.12.2.jar                               | None                                     |
       | LCHIJA | increasemobs          | 1.1.0                | IncreaseMobs_1.12.2-v1.1.0.jar                       | None                                     |
       | LCHIJA | imsm                  | 1.12                 | Instant-Massive-Structures-Mod-1.12.2.jar            | None                                     |
       | LCHIJA | jei                   | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                            | None                                     |
       | LCHIJA | libvulpes             | 0.4.2.-74            | LibVulpes-1.12.2-0.4.2-74-universal.jar              | None                                     |
       | LCHIJA | mantle                | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                             | None                                     |
       | LCHIJA | advancedrocketry      | 1.7.0.-209           | movingworld-1.12-5.341-full.jar                      | None                                     |
       | LCHIJA | progressiveautomation | 1.7.8                | ProgressiveAutomation-1.12.2-1.7.8.jar               | None                                     |
       | LCHIJA | somanyenchantments    | 0.4.3                | somanyenchantments+V0.4.31.jar                       | None                                     |
       | LCHIJA | sparkstools           | @VERSION@            | sparkstools-1.12.2-1.1.1.jar                         | None                                     |
       | LCHIJA | tconstruct            | 1.12.2-2.13.0.179    | TConstruct-1.12.2-2.13.0.179.jar                     | None                                     |
       | LCHIJA | tektopia              | 1.1.0                | tektopia-1.1.0.jar                                   | None                                     |
       | LCHIJA | timehud               | 7.3.1                | TimeHUD-1.12.2-7.3.1.jar                             | None                                     |
       | LCHIJA | tinymobfarm           | 1.0.5                | TinyMobFarm-1.12.2-1.0.5.jar                         | None                                     |
       | LCHIJA | uniquee               | 1.8.0                | Unique+Enchantments+V1.12.2-1.8.jar                  | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-150           | VanillaFix-1.0.10-150.jar                            | None                                     |
       | LCHIJA | veinminer             | 0.38.0               | VeinMiner-1.12-0.38.0.633+f768836.jar                | None                                     |
       | LCHIJA | veinminermodsupport   | 0.38.0               | VeinMiner-1.12-0.38.0.633+f768836.jar                | None                                     |
       | LCHIJA | worldedit             | 6.1.10-SNAPSHOT      | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar    | None                                     |
       | LCHIJA | xaerominimap          | 1.16                 | Xaeros_Minimap_1.16_Forge_1.12.jar                   | None                                     |
       | LCHIJA | structurize           | 1.12.2-0.10.154-BETA | structurize-1.12.2-0.10.154-BETA.jar                 | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar)
                                        
                                      llibrary (llibrary-core-1.0.10-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      AdvancedRocketryPlugin (movingworld-1.12-5.341-full.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
  Suspected Mods: Mod Support (veinminermodsupport), Vein Miner (veinminer), BuildCraft Silicon (buildcraftsilicon), BuildCraft Factory (buildcraftfactory), BuildCraft Builders (buildcraftbuilders), BuildCraft Energy (buildcraftenergy), BuildCraft Transport (buildcrafttransport), BuildCraft Lib (buildcraftlib), BuildCraft Compat (buildcraftcompat), BuildCraft (buildcraftcore), BuildCraft Robotics (buildcraftrobotics)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Big_Red09326'/412, l='!.12.2 space survival yay', x=-230.44, y=64.00, z=98.79]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 2

**Comment by AEnterprise** [comment]
looks like veinmeiner is doing something weird when the quarry breaks a block. please report this to them instead

**Comment by AlexIIL** [comment]
Reported here: https://github.com/portablejim/VeinMiner/issues/161
