### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mc-xp** [BuildCraft/BuildCraft#4591]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2020-07-28 14:51:16 GMT
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: javax/vecmath/Tuple3f
    at buildcraft.lib.misc.data.Box.<init>(Box.java:61)
    at buildcraft.energy.generation.OilGenerator.onPopulatePre(OilGenerator.java:65)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_723_OilGenerator_onPopulatePre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:769)
    at net.minecraft.world.gen.ChunkGeneratorOverworld.populate(ChunkGeneratorOverworld.java:395)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3f
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    ... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
  Java Version: 1.8.0_242, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 831732336 bytes (793 MB) / 2013790208 bytes (1920 MB) up to 4660396032 bytes (4444 MB)
  JVM Flags: 2 total; -Xmx5000M -Xms128M
  IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 96
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 63 mods loaded, 63 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                  | Version           | Source                                        | Signature                                |
       |:------ |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge               | 14.23.5.2854      | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | micdoodlecore       |                   | minecraft.jar                                 | None                                     |
       | LCHIJA | foamfixcore         | 7.7.4             | minecraft.jar                                 | None                                     |
       | LCHIJA | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
       | LCHIJA | abyssalcraft        | 1.10.2            | AbyssalCraft-1.12.2-1.10.2.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | forgeendertech      | 1.12.2-4.5.1.0    | ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar  | None                                     |
       | LCHIJA | adlods              | 1.12.2-1.0.7.1    | AdLods-1.12.2-1.0.7.1-build.0441.jar          | None                                     |
       | LCHIJA | aether_legacy       | 1.4.4             | aether-1.4.4.jar                              | None                                     |
       | LCHIJA | quark               | r1.6-179          | Quark-r1.6-179.jar                            | None                                     |
       | LCHIJA | autoreglib          | 1.3-32            | AutoRegLib-1.3-32 (1).jar                     | None                                     |
       | LCHIJA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCHIJA | biomesoplenty       | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
       | LCHIJA | bookshelf           | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | buildcraftlib       | 7.99.24.6         | buildcraft-core-7.99.24.6.jar                 | None                                     |
       | LCHIJA | buildcraftcore      | 7.99.24.6         | buildcraft-core-7.99.24.6.jar                 | None                                     |
       | LCHIJA | buildcraftbuilders  | 7.99.24.6         | buildcraft-builders-7.99.24.6.jar             | None                                     |
       | LCHIJA | buildcrafttransport | 7.99.24.6         | buildcraft-transport-7.99.24.6.jar            | None                                     |
       | LCHIJA | crafttweaker        | 4.1.20            | CraftTweaker2-1.12-4.1.20.574.jar             | None                                     |
       | LCHIJA | buildcraftcompat    | 7.99.24.6         | buildcraft-compat-7.99.24.6.jar               | None                                     |
       | LCHIJA | buildcraftenergy    | 7.99.24.6         | buildcraft-energy-7.99.24.6.jar               | None                                     |
       | LCHIJA | buildcraftfactory   | 7.99.24.6         | buildcraft-factory-7.99.24.6.jar              | None                                     |
       | LCHIJA | buildcraftrobotics  | 7.99.24.6         | buildcraft-robotics-7.99.24.6.jar             | None                                     |
       | LCHIJA | chisel              | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
       | LCHIJA | clumps              | 3.1.2             | Clumps-3.1.2.jar                              | None                                     |
       | LCHIJA | crafttweakerjei     | 2.0.3             | CraftTweaker2-1.12-4.1.20.574.jar             | None                                     |
       | LCHIJA | customspawner       | 3.11.4            | CustomMobSpawner-3.11.5.jar                   | None                                     |
       | LCHIJA | damageindicatorsmod | 1.0               | DamageIndicatorsMod-3.5.1.jar                 | None                                     |
       | LCHIJA | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | LCHIJA | darkutils           | 1.8.230           | DarkUtils-1.12.2-1.8.230.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | dldungeonsjbg       | 1.13.2            | DoomlikeDungeons-1.13.2-MC1.12.2.jar          | None                                     |
       | LCHIJA | ic2                 | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | galacticraftcore    | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
       | LCHIJA | orelib              | 3.6.0.1           | OreLib-3.6.0.1.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround           | 3.6.1.0           | DynamicSurroundings-3.6.1.0.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dynamictrees        | 1.12.2-0.9.8      | DynamicTrees-1.12.2-0.9.8.jar                 | None                                     |
       | LCHIJA | dynamictreesbop     | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
       | LCHIJA | thaumcraft          | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
       | LCHIJA | dynamictreestc      | 1.12.2-1.4.1e     | DynamicTreesTC-1.12.2-1.4.1e.jar              | None                                     |
       | LCHIJA | eplus               | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | farlanders          | 1.0.1             | farlanders-1.12.2-1.0.1.jar                   | None                                     |
       | LCHIJA | fastbench           | 1.7.3             | FastWorkbench-1.7.3.jar                       | None                                     |
       | LCHIJA | foamfix             | 0.10.10-1.12.2    | foamfix-0.10.10.jar                           | None                                     |
       | LCHIJA | galacticraftplanets | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
       | LCHIJA | gravestone          | 1.10.3            | gravestones.jar                               | None                                     |
       | LCHIJA | llibrary            | 1.7.19            | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire          | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
       | LCHIJA | ironbackpacks       | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
       | LCHIJA | ironchest           | 1.12.2-7.0.67.844 | ironchest-7.0.72.847.jar                      | None                                     |
       | LCHIJA | lootbags            | 2.5.8.5           | LootBags-1.12.2-2.5.8.5.jar                   | None                                     |
       | LCHIJA | mocreatures         | 12.0.5            | mocreatures.jar                               | None                                     |
       | LCHIJA | numina              | 1.12.2-1.0.38     | Numina-1.12.2-1.0.38.jar                      | None                                     |
       | LCHIJA | powersuits          | 1.12.2-1.0.46     | ModularPowersuits-1.12.2-1.0.46.jar           | None                                     |
       | LCHIJA | mowziesmobs         | 1.5.6             | mowziesmobs-1.5.6.jar                         | None                                     |
       | LCHIJA | placebo             | 1.6.0             | Placebo-1.6.0.jar                             | None                                     |
       | LCHIJA | stg                 | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                          | None                                     |
       | LCHIJA | twilightforest      | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
       | LCHIJA | vanillafix          | 1.0.10-150        | VanillaFix-1.0.10-150.jar                     | None                                     |
       | LCHIJA | waystones           | 4.1.0             | Waystones-4.1.0.jar                           | None                                     |
       | LCHIJA | xpbook              | v1.1.4            | xptome-1.12.2-v1.1.4.jar                      | None                                     |
       | LCHIJA | jurassicraft        | 2.1.23            | JurassiCraft-1.12.2-2.1.23.jar                | None                                     |
  Loaded coremods (and transformers): CorePlugin (ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      TransformLoader (DynamicSurroundings-3.6.1.0.jar)
                                        
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
  Suspected Mods: BuildCraft (buildcraftcore), BuildCraft Energy (buildcraftenergy)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 100
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by mc-xp** [comment]
This mod-pack works fine on singleplayer btw. I was thinking there might be a client-side mod in there messing with things but I'm pretty sure I removed them all.
