### ISSUE TITLE
Quarry crashes minecraft

### ISSUE THREAD

**Issue by arsik228** [BuildCraft/BuildCraft#4617]
When I put a quarry, power it up, minecraft crashes and I can't go to the map again until I delete Buildcraft

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020-11-15 19:28:10 KRAT
Description: Ticking block entity

net.journey.util.exception.WrongSideException: Shouldn't be called on side: CLIENT
    at net.journey.common.capability.JourneyPlayerImpl.sendUpdates(JourneyPlayerImpl.java:71)
    at net.journey.common.knowledge.JourneyKnowledgeEventListener.onBlockHarvested(JourneyKnowledgeEventListener.java:51)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2116_JourneyKnowledgeEventListener_onBlockHarvested_HarvestDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
    at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:572)
    at net.minecraft.block.Block.dropBlockAsItem(Block.java:564)
    at net.minecraft.block.Block.harvestBlock(Block.java:735)
    at buildcraft.lib.misc.BlockUtil.harvestBlock(BlockUtil.java:135)
    at buildcraft.lib.misc.BlockUtil.breakBlockAndGetDrops(BlockUtil.java:220)
    at buildcraft.builders.tile.TileQuarry$TaskBreakBlock.finish(TileQuarry.java:1018)
    at buildcraft.builders.tile.TileQuarry$Task.addPower(TileQuarry.java:932)
    at buildcraft.builders.tile.TileQuarry.update(TileQuarry.java:564)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by arsik228** [comment]
A detailed walkthrough of the error, its code path and all known details is as follows:
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: buildcraftbuilders:quarry // buildcraft.builders.tile.TileQuarry
  Block type: ID #4624 (tile.quarryBlock // buildcraft.builders.block.BlockQuarry // buildcraftbuilders:quarry)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-535,67,1023), Chunk: (at 9,4,15 in -34,63; contains blocks -544,0,1008 to -529,255,1023), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
  Actual block type: ID #4624 (tile.quarryBlock // buildcraft.builders.block.BlockQuarry // buildcraftbuilders:quarry)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {owner:{Id:"00000000-0000-0000-0000-000000000000",Name:"Ring2000"},currentTaskId:0b,box:{min:[I;-539,0,1013],max:[I;-531,70,1021]},battery:{stored:12774266652L},firstChecked:1b,drillPos:[-539.0d,66.0d,1013.0d],boxIterator:{current:[I;-539,66,1013],min:[I;-539,0,1013],invert:1b,max:[I;-531,70,1021],order:{inversion:"PPN",order:"XZY"}},x:-535,y:67,z:1023,id:"buildcraftbuilders:quarry",deltas:{},data-version:2,frame:{min:[I;-540,67,1012],max:[I;-530,71,1022]},currentTaskData:{power:48000000L,breakPos:[I;-539,66,1013]}}

-- Affected level --
  Level name: Новый мир
  All players: 0 total; []
  Chunk stats: ServerChunkCache: 2 Drop: 0
  Level seed: 7050498624771462710
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (152,64,256), Chunk: (at 8,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 190775 game time, 292981 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 8172 (now: false), thunder time: 5640 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 7680611088 bytes (7324 MB) / 10536091648 bytes (10048 MB) up to 10536091648 bytes (10048 MB)
  JVM Flags: 8 total; -Xmn128M -Xmx10022M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 15, tcache: 1, allocated: 5, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 189 mods loaded, 187 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version                  | Source                                             | Signature                                |
       |:------ |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                             | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | advmachinespatchcore              | 1.0                      | minecraft.jar                                      | None                                     |
       | LCHIJA | advsolarpatchcore                 | 1.0                      | minecraft.jar                                      | None                                     |
       | LCHIJA | smoothfontcore                    | mc1.12.2-2.1.2           | minecraft.jar                                      | None                                     |
       | LCHIJA | openmodscore                      | 0.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCHIJA | smoothfont                        | mc1.12.2-2.1.2           | SmoothFont_mc1.12.2_2.1.2.jar                      | None                                     |
       | LCHIJA | customskinloader                  | 14.13-SNAPSHOT-199       | CustomSkinLoader_Forge-14.13-SNAPSHOT-199.jar      | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
       | LCHIJA | bspkrscore                        | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
       | LCHIJA | ic2                               | 2.8.221-ex112            | industrialcraft_2_2.8.221_ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | advanced_machines                 | 61.0.1                   | Advanced+Machines-61.0.1.jar                       | None                                     |
       | LCHIJA | advanced_solar_panels             | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                    | None                                     |
       | LCHIJA | advmachinespatch                  | 1.0                      | advmachinespatch-1.0.jar                           | None                                     |
       | LCHIJA | advsolarpatch                     | 1.1                      | advsolarpatch-1.1.jar                              | None                                     |
       | LCHIJA | ctm                               | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
       | LCHIJA | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
       | LCHIJA | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
       | LCHIJA | appliedintegrations               | 8.0.16.7                 | AppliedIntegrations-1.12.2-e2884e6f.jar            | None                                     |
       | LCHIJA | armorstatushud                    | 1.43.0                   | ArmorStatusHUD-1.43.0.jar                          | None                                     |
       | LCHIJA | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
       | LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
       | LCHIJA | modtweaker                        | 4.0.18                   | modtweaker-4.0.18.jar                              | None                                     |
       | LCHIJA | jei                               | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                          | None                                     |
       | LCHIJA | chisel                            | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                       | None                                     |
       | LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.73            | EnderCore-1.12.2-0.5.73.jar                        | None                                     |
       | LCHIJA | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
       | LCHIJA | brandonscore                      | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | LCHIJA | cofhworld                         | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalfoundation                 | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | draconicevolution                 | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LCHIJA | thermalexpansion                  | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tweakersconstruct                 | 1.12.2-1.5.1             | tweakersconstruct-1.12.2-1.5.2.jar                 | None                                     |
       | LCHIJA | enderio                           | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | twilightforest                    | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LCHIJA | conarm                            | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | botania                           | r1.10-363                | Botania.r1.10-363.jar                              | None                                     |
       | LCHIJA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | extrabotany                       | 58                       | ExtraBotany-r1.1-58r.jar                           | None                                     |
       | LCHIJA | armoryexpansion                   | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | armoryexpansion-custommaterials   | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | hammercore                        | 2.0.6.23                 | HammerLib-1.12.2-2.0.6.23.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | avaritia                          | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar             | None                                     |
       | LCHIJA | solarflux                         | 4.35r                    | SolarFluxReborn_1.12.2-4.35r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | thaumadditions                    | 12.6.6                   | ThaumicAdditions-1.12.2-12.6.6.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | llibrary                          | 1.7.19                   | llibrary_1.7.19_1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                        | 1.9.0                    | iceandfire_1.12.2_1.9.0.jar                        | None                                     |
       | LCHIJA | armoryexpansion-iceandfire        | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | armoryexpansion-matteroverdrive   | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | wanionlib                         | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                           | None                                     |
       | LCHIJA | avaritiaddons                     | 1.12.2-1.1               | Avaritiaddons-1.12.2-1.1.jar                       | None                                     |
       | LCHIJA | bettercombatmod                   | 1.5.2                    | BetterCombat_1.12.2_1.5.2.jar                      | None                                     |
       | LCHIJA | betterquesting                    | 3.5.320                  | BetterQuesting-3.5.320.jar                         | None                                     |
       | LCHIJA | patchouli                         | 1.0-20                   | Patchouli-1.0-20.jar                               | None                                     |
       | LCHIJA | bewitchment                       | 0.21.10                  | bewitchment-1.12.2-0.0.21.10.jar                   | None                                     |
       | LCHIJA | buildcraftlib                     | 7.99.24.5                | buildcraft-core-7.99.24.5.jar                      | None                                     |
       | LCHIJA | buildcraftcore                    | 7.99.24.5                | buildcraft-core-7.99.24.5.jar                      | None                                     |
       | LCHIJA | buildcraftenergy                  | 7.99.24.5                | buildcraft-energy-7.99.24.5.jar                    | None                                     |
       | LCHIJA | forestry                          | 5.8.2.387                | forestry1.12.2-5.8.2.387.jar                       | None                                     |
       | LCHIJA | binniecore                        | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                   | None                                     |
       | LCHIJA | binniedesign                      | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                   | None                                     |
       | LCHIJA | genetics                          | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                   | None                                     |
       | LCHIJA | botany                            | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                   | None                                     |
       | LCHIJA | extrabees                         | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                   | None                                     |
       | LCHIJA | extratrees                        | 2.5.1.198                | binnie-mods-1.12.2-2.5.1.198.jar                   | None                                     |
       | LCHIJA | biomesoplenty                     | 7.0.1.2444               | BiomesOPlenty_1.12.2_7.0.1.2444_universal (1).jar  | None                                     |
       | LCHIJA | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | bloodmagic                        | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
       | LCHIJA | bloodarsenal                      | 1.12.2-2.2.2-31          | BloodArsenal-1.12.2-2.2.2-31.jar                   | None                                     |
       | LCHIJA | bookshelf                         | 2.3.590                  | Bookshelf_1.12.2_2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | buildcraftbuilders                | 7.99.24.5                | buildcraft-builders-7.99.24.5.jar                  | None                                     |
       | LCHIJA | buildcraftfactory                 | 7.99.24.5                | buildcraft-factory-7.99.24.5.jar                   | None                                     |
       | LCHIJA | buildcrafttransport               | 7.99.24.5                | buildcraft-transport-7.99.24.5.jar                 | None                                     |
       | LCHIJA | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHIJA | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
       | LCHIJA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
       | LCHIJA | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
       | LCHIJA | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
       | LCHIJA | denseneutroncollectors            | @VERSION@                | denseneutroncollectors-1.1.jar                     | None                                     |
       | LCHIJA | divinerpg                         | 1.7.1                    | DivineRPG_1.12.2_1.7.1.jar                         | None                                     |
       | LCHIJA | draconicadditions                 | 1.10.1                   | Draconic-Additions-1.12.2-1.10.1.29-universal.jar  | None                                     |
       | LCHIJA | dragon_enchants                   | 1.0                      | dragonenchantments_1.0.0.jar                       | None                                     |
       | LCHIJA | drpg_addon                        | 1.0.0                    | drpg_addon_1.3.jar                                 | None                                     |
       | LCHIJA | dummycore                         | 2.4.112.5.               | dummycoreunofficial-2.4.112.5.jar                  | None                                     |
       | LCHIJA | emt                               | 12.2.0                   | emt-12.2.4.jar                                     | None                                     |
       | LCHIJA | eplus                             | 5.0.178                  | EnchantingPlus_1.12.2_5.0.178.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enderiobase                       | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderioconduits                   | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | ftblib                            | 5.4.4.5                  | FTBLib-5.4.4.5.jar                                 | None                                     |
       | LCHIJA | enderiomachines                   | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderiopowertools                 | 5.1.51                   | EnderIO-1.12.2-5.1.51.jar                          | None                                     |
       | LCHIJA | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | energyconverters                  | 1.3.6.24                 | energyconverters_1.12.2-1.3.6.24.jar               | None                                     |
       | LCHIJA | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
       | LCHIJA | environmentaltech                 | 1.12.2-2.0.20.1          | environmentaltech-1.12.2-2.0.20.1.jar              | None                                     |
       | LCHIJA | extracells                        | 2.6.5                    | ExtraCells-1.12.2-2.6.5.jar                        | None                                     |
       | LCHIJA | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCHIJA | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
       | LCHIJA | bigreactors                       | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                | None                                     |
       | LCHIJA | fluxnetworks                      | 4.0.14                   | fluxnetworks_1.12.2_4.0.15_32.jar                  | None                                     |
       | LCHIJA | foamfix                           | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | LCHIJA | forgelin                          | 1.8.3                    | Forgelin-1.8.3.jar                                 | None                                     |
       | LCHIJA | forgemultipartcbe                 | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe                     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
       | LCHIJA | minecraftmultipartcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
       | LCHIJA | gravisuite                        | 3.1.1                    | Gravitation+Suite-3.1.1.jar                        | None                                     |
       | LCHIJA | ichunutil                         | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | railcraft                         | 12.0.0                   | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | immersiveengineering              | 0.12-92                  | ImmersiveEngineering-0.12-92.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | immersivepetroleum                | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
       | LCHIJA | tesla                             | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
       | LCHIJA | infernalmobs                      | 1.7.3                    | InfernalMobs_1.12.2 (1).jar                        | None                                     |
       | LCHIJA | mysticalagriculture               | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
       | LCHIJA | mysticalagradditions              | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
       | LCHIJA | integrationforegoing              | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHIJA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCHIJA | jeibees                           | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
       | LCHIJA | journey                           | 1.0.6.3                  | Journey_Into_The_Light_1.12.2_1.0.6.3.jar          | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.5.8             | journeymap-1.12.2-5.5.8.jar                        | None                                     |
       | LCHIJA | jee                               | 1.0.8                    | JustEnoughEnergistics-1.12.2-1.0.8.jar             | None                                     |
       | LCHIJA | jeid                              | 1.0.3-48                 | JustEnoughIDs-1.0.3-48.jar                         | None                                     |
       | LCHIJA | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHIJA | mm                                | 0.4                      | MaelstromMod_1.12.2_0.4.jar                        | None                                     |
       | LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | LCHIJA | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                            | None                                     |
       | LCHIJA | mclib                             | 2.1                      | mclib-2.1-1.12.2.jar                               | None                                     |
       | LCHIJA | immersivetech                     | 1.8.86                   | MCTImmersiveTechnology-1.12.2-1.8.86.jar           | None                                     |
       | LCHIJA | mdecore                           | 1.12-1.1                 | mdecore-1.12-1.1.jar                               | None                                     |
       | LCHIJA | metamorph                         | 1.2.3                    | metamorph-1.2.3-1.12.2.jar                         | None                                     |
       | LCHIJA | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCHIJA | mowziesmobs                       | 1.5.8                    | mowziesmobs_1.12.2_1.5.8.jar                       | None                                     |
       | LCHIJA | mrtjpcore                         | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
       | LCHIJA | mutantbeasts                      | 1.12.2-1.0.1             | MutantBeasts_1.12.2_1.0.1.jar                      | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
       | LCHIJA | neat                              | 1.4-17                   | neat1.4-17.jar                                     | None                                     |
       | LCHIJA | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openfm                            | 0.1.0.19                 | OpenFM-1.12.2-0.1.0.19.jar                         | None                                     |
       | LCHIJA | plustic                           | 7.1.6.1                  | plustic-7.1.6.1.jar                                | None                                     |
       | LCHIJA | rats                              | 3.2.14                   | rats_3.2.14_1.12.2.jar                             | None                                     |
       | LCHIJA | redstonearsenal                   | 2.6.3                    | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | bq_standard                       | 3.4.173                  | StandardExpansion-3.4.173.jar                      | None                                     |
       | LCHIJA | storagedrawers                    | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
       | LCHIJA | surge                             | 2.0.77                   | surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tc6aspects4jei                    | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                          | None                                     |
       | LCHIJA | texfix                            | 4.0                      | TexFixV_1.12_4.0.jar                               | None                                     |
       | LCHIJA | tg                                | 0.1.5.0                  | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar           | None                                     |
       | LCHIJA | thaumicaugmentation               | 1.12.2-1.1.17            | ThaumicAugmentationCorePlugin.jar                  | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicbases                      | 3.3.500.6r               | thaumicbases-3.3.500.6r.jar                        | None                                     |
       | LCHIJA | tcinventoryscan                   | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
       | LCHIJA | thaumictinkerer                   | 1.12.2-5.0-620a0c5       | thaumictinkerer-1.12.2-5.0-620a0c5.jar             | None                                     |
       | LCHIJA | thaumicwonders                    | 1.8.2                    | thaumicwonders-1.8.2.jar                           | None                                     |
       | LCHIJA | thermaldynamics                   | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation                 | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
       | LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | LCHIJA | tlauncher_custom_cape_skin        | 1.4                      | tlskincape_1.12.2-1.4.jar                          | None                                     |
       | LCHIJA | traverse                          | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                       | None                                     |
       | LCHIJA | tweakergui                        | 0.5-beta                 | tweakergui-1.12.2-0.5-beta.jar                     | None                                     |
       | LCHIJA | unloader                          | 1.2.0                    | unloader-1.2.0.jar                                 | None                                     |
       | LCHIJA | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
       | LCHIJA | vampirism                         | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
       | LCHIJA | teamlapen-lib                     | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
       | LCHIJA | vampirism_integrations            | vampirism_integrations   | VampirismIntegrations-1.12.2-1.3.0.jar             | None                                     |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | xnet                              | 1.8.2                    | xnet-1.12-1.8.2.jar                                | None                                     |
       | LCHIJA | shetiphiancore                    | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar                    | None                                     |
       | LCHIJA | armoryexpansion-conarm            | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
       | LCHIJA | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
       | UD     | mdecore-core                      | 1.0                      | minecraft.jar                                      | None                                     |
       | UD     | mclib_core                        | 2.1                      | minecraft.jar                                      | None                                     |
