### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rev0lt1** [BuildCraft/BuildCraft#4631]
Hello,
I encountered this crash.

Minecraft launcher error message:
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: no such constructor: buildcraft.api.statements.StatementParameterItemStack.<init>(NBTTagCompound)void/newInvokeSpecial
Ukončovací kód: -1`

Crash log:

`---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 30.1.21 18:44
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: no such constructor: buildcraft.api.statements.StatementParameterItemStack.<init>(NBTTagCompound)void/newInvokeSpecial
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: no such constructor: buildcraft.api.statements.StatementParameterItemStack.<init>(NBTTagCompound)void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483)
	at buildcraft.api.statements.StatementManager.<clinit>(StatementManager.java:29)
	at buildcraft.core.statements.BCStatement.<init>(BCStatement.java:24)
	at buildcraft.core.statements.TriggerMachine.<init>(TriggerMachine.java:33)
	at buildcraft.BuildCraftCore.<clinit>(BuildCraftCore.java:234)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 39 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 401790568 bytes (383 MB) / 1260388352 bytes (1202 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 70 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UC	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	DamageIndicatorsMod{3.3.2} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.3.2.jar) 
	UC	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UC	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UC	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) 
	UC	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UC	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UC	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UE	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22-core.jar) 
	UC	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UE	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UC	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UC	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner-3.3.0.jar) 
	UC	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks-MoCreatures-Mod-v6.3.1.jar) 
	UC	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UC	ExtrabiomesXL{3.16.4} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.4.jar) 
	UC	GalacticraftCore{3.0.12} [Galacticraft Core] (Galacticraft-Mod-1.7.10.jar) 
	UC	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UC	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UC	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
	UC	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UC	LightBridgesAndDoors{0.1.8} [kris91268's Light Bridges and Doors] (Light-Bridges-and-Doors-Mod-1.7.2.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UC	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UC	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
	UC	MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	tc{4.4.1_021} [Traincraft] (Traincraft-4.4.1_021.jar) 
	UC	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
	UC	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UC	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UC	numina{1.7.10} [Numina] (Numina-0.4.1.106.jar) 
	UC	powersuits{1.7.10-0.11.1.114} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.7.10-0.11.1.114.jar) 
	UC	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UC	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UC	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UC	Torched{4.0.0} [Torched] (Torched-4.0.0.jar) 
	UC	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UC	XaeroMinimap{21.1.1} [Xaero's Minimap] (Xaeros_Minimap_21.1.1_Forge_1.7.10.jar) 
	UC	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UC	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	UD	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 460.89' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	MineFactoryReloaded: -[1.7.10]2.8.2B1-201
	TConstruct Environment: Environment healthy.`

**Comment by PhantomSoul07** [comment]
im probably wrong but i think optifine is the cause
