### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sinnero** [BuildCraft/BuildCraft#4649]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 8/6/21 11:23 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Energy (buildcraftenergy)
Caused by: java.lang.NoClassDefFoundError: buildcraft/energy/generation/OilGenerator
	at buildcraft.energy.BCEnergyWorldGen.init(BCEnergyWorldGen.java:22)
	at buildcraft.energy.BCEnergy.init(BCEnergy.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: buildcraft.energy.generation.OilGenerator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@7577e803 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.objectweb.asm.tree.LabelNode.getLabel(LabelNode.java:60)
	at org.objectweb.asm.tree.LabelNode.accept(LabelNode.java:67)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:121)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at buildcraft.energy.BCEnergyWorldGen.init(BCEnergyWorldGen.java:22)
	at buildcraft.energy.BCEnergy.init(BCEnergy.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 45061112 bytes (42 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                            | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHI  | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHI  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHI  | betterbuilderswands  | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
	| LCHI  | biomesoplenty        | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
	| LCHI  | bonsaitrees          | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                        | None                                     |
	| LCHI  | bookshelf            | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | crafttweaker         | 4.1.20                   | CraftTweaker2-1.12-4.1.20.656.jar                 | None                                     |
	| LCHI  | jei                  | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                         | None                                     |
	| LCHI  | botania              | r1.10-364                | Botania+r1.10-364.4.jar                           | None                                     |
	| LCHI  | buildcraftlib        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHI  | buildcraftcore       | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHI  | buildcraftbuilders   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHI  | buildcrafttransport  | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHI  | buildcraftsilicon    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHI  | buildcraftcompat     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHE  | buildcraftenergy     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCH   | buildcraftfactory    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCH   | buildcraftrobotics   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCH   | chiselsandbits       | 14.33                    | chiselsandbits-14.33.jar                          | None                                     |
	| LCH   | codechickenlib       | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | craftstudioapi       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| LCH   | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.20.656.jar                 | None                                     |
	| LCH   | crafttweakerjei      | 2.0.3                    | CraftTweaker2-1.12-4.1.20.656.jar                 | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
	| LCH   | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCH   | flansmod             | 5.10.0                   | Flan's+Mod-1.12.2-5.10.0.jar                      | None                                     |
	| LCH   | gravestone           | 1.10.3                   | gravestone-1.10.3.jar                             | None                                     |
	| LCH   | hbm                  | hbm-1.4.4A-1.12.2        | hbm-1.4.4a.jar                                    | None                                     |
	| LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCH   | inventorypets        | 2.0.15                   | inventorypets-1.12-2.0.15.jar                     | None                                     |
	| LCH   | ironbackpacks        | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCH   | ironchest            | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCH   | jeiintegration       | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar                   | None                                     |
	| LCH   | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                       | None                                     |
	| LCH   | jeresources          | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
	| LCH   | keywizard            | 1.12.2-1.7.3             | keywizard-1.12.2-1.7.3.jar                        | None                                     |
	| LCH   | libraryex            | 1.2.2                    | LibraryEx-1.12.2-1.2.2.jar                        | None                                     |
	| LCH   | mekanism             | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                     | None                                     |
	| LCH   | mekanismgenerators   | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar           | None                                     |
	| LCH   | movingelevators      | 1.2.34                   | movingelevators-1.2.34-mc1.12.jar                 | None                                     |
	| LCH   | netherportalfix      | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                 | None                                     |
	| LCH   | examplemod           | 1.0                      | NuclearCraft-2.18z-1.12.2.jar                     | None                                     |
	| LCH   | nuclearcraft         | 2.18z                    | NuclearCraft-2.18z-1.12.2.jar                     | None                                     |
	| LCH   | additionalstructures | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar  | None                                     |
	| LCH   | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCH   | simplyjetpacks       | 1.12.2-2.2.20.0          | SimplyJetpacks2-1.12.2-2.2.20.0.jar               | None                                     |
	| LCH   | stevekung's_lib      | 1.1.10                   | SteveKunG's-Lib-1.12.2-1.1.10.jar                 | None                                     |
	| LCH   | storagedrawers       | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                   | None                                     |
	| LCH   | storagedrawersextra  | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar               | None                                     |
	| LCH   | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCH   | veinminer            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCH   | veinminermodsupport  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LCH   | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |

	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.38' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.38
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
@Sinnero
 
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About

**Comment by Sinnero** [comment]
I have no clue about this

**Comment by AlexIIL** [comment]
Line 67: `Caused by: java.lang.OutOfMemoryError: Java heap space` means you'll probably need to allocate more RAM to minecraft.

**Comment by Sinnero** [comment]
> Line 67: `Caused by: java.lang.OutOfMemoryError: Java heap space` means you'll probably need to allocate more RAM to minecraft.

This was the issue. Thanks 😄

**Comment by AlexIIL** [comment]
Ok :)
